package services

import (
	"context"
	openapiChat "mw-general-bff/apiAutogenerated/mw-chat"
	"mw-general-bff/internal/config"
)

type ChatService struct {
	chatAPI *openapiChat.APIClient
	config  *config.Config
}

func newChatService(chatAPI *openapiChat.APIClient, config *config.Config) *ChatService {
	return &ChatService{chatAPI, config}
}

type CreateMessageParams struct {
	RoomId string
}

// Viktar's prod user id
var GreetingChatUserId = "ec3e7405-02d2-fdd4-e0ac-f9b1e2082f76"

func (ms *ChatService) CreateGreetingMessage(ctx context.Context, params *CreateMessageParams) error {
	args := openapiChat.MwChatInternalSchemasCreateGreetingMessagePayload{
		RoomId: params.RoomId,
	}

	_, err := ms.chatAPI.MessageAPI.CreateGreetingMessage(ctx).Request(args).Execute()
	if err != nil {
		return err
	}

	return nil
}

type CreateRoomParams struct {
	Name     *string
	RoomType string
	UserId   *string
}

func (ms *ChatService) CreateRoom(ctx context.Context, params *CreateRoomParams) (roomId string, err error) {
	name := openapiChat.NullableString{}
	name.Set(params.Name)

	userId := openapiChat.NullableString{}
	userId.Set(params.UserId)

	args := openapiChat.MwChatInternalSchemasCreateRoomPayload{
		Name:     name,
		RoomType: params.RoomType,
		UserId:   userId,
	}

	roomRaw, _, err := ms.chatAPI.RoomAPI.FindOrCreateRoom(ctx).Request(args).Execute()
	if err != nil {
		return "", err
	}

	return roomRaw.Room.RoomId, nil
}
