package services

import (
	"context"

	"mw-general-bff/internal/schemas"
	"mw-general-bff/pkg/utils"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/samber/lo"

	openapiGeneral "mw-general-bff/apiAutogenerated/general"

	"github.com/google/uuid"
)

type GeneralService struct {
	generalAPI *openapiGeneral.APIClient
}

func newGeneralService(generalAPI *openapiGeneral.APIClient) *GeneralService {
	return &GeneralService{generalAPI}
}

func (gs *GeneralService) CreateComment(ctx context.Context, payload *schemas.CreateCommentPayload) (*schemas.CommentPopulatedResponse, error) {
	commentRaw, response, err := gs.generalAPI.CommentAPI.CreateComment(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateCommentPayload{
		DayReportUuid: payload.DayReportUuid,
		Description:   payload.Description,
		OwnerUuid:     payload.OwnerUuid,
	}).Execute()
	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	comment := &schemas.CommentPopulatedResponse{
		Uuid:          commentRaw.Uuid,
		Description:   commentRaw.Description,
		OwnerUuid:     commentRaw.OwnerUuid,
		OwnerName:     commentRaw.OwnerName,
		CreatedAt:     commentRaw.CreatedAt,
		UpdatedAt:     commentRaw.UpdatedAt,
		DayReportUuid: commentRaw.DayReportUuid,
		WayUUID:       commentRaw.WayUuid,
		WayName:       commentRaw.WayName,
	}

	return comment, nil
}

type UpdateCommentParams struct {
	CommentID        string
	Description      *string
	ModifierUserUuid string
}

func (gs *GeneralService) UpdateComment(ctx context.Context, params *UpdateCommentParams) (*schemas.CommentPopulatedResponse, error) {
	updateReq := openapiGeneral.MwServerInternalSchemasUpdateCommentPayload{
		Description: params.Description,
	}

	updatedCommentRaw, response, err := gs.generalAPI.CommentAPI.UpdateComment(ctx, params.CommentID).Request(updateReq).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	updatedComment := &schemas.CommentPopulatedResponse{
		Uuid:          updatedCommentRaw.Uuid,
		Description:   updatedCommentRaw.Description,
		OwnerUuid:     updatedCommentRaw.OwnerUuid,
		OwnerName:     updatedCommentRaw.OwnerName,
		CreatedAt:     updatedCommentRaw.CreatedAt,
		UpdatedAt:     updatedCommentRaw.UpdatedAt,
		DayReportUuid: updatedCommentRaw.DayReportUuid,
		WayUUID:       updatedCommentRaw.WayUuid,
		WayName:       updatedCommentRaw.WayName,
	}

	return updatedComment, nil
}

func (gs *GeneralService) DeleteCommentById(ctx context.Context, commentID string) error {
	response, err := gs.generalAPI.CommentAPI.DeleteComment(ctx, commentID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

type AddWayToCompositeWayParams struct {
	ChildWayID  string
	ParentWayID string
}

func (gs *GeneralService) AddWayToCompositeWay(ctx context.Context, params *schemas.AddWayToCompositeWayPayload) (*schemas.CompositeWayRelation, error) {
	relationRaw, response, err := gs.generalAPI.CompositeWayAPI.CreateCompositeWay(ctx).Request(openapiGeneral.MwServerInternalSchemasAddWayToCompositeWayPayload{
		ChildWayUuid:  params.ChildWayUuid,
		ParentWayUuid: params.ParentWayUuid,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	relation := &schemas.CompositeWayRelation{
		ChildWayUuid:  relationRaw.ChildWayUuid,
		ParentWayUuid: relationRaw.ParentWayUuid,
	}

	return relation, nil
}

func (gs *GeneralService) DeleteCompositeWayRelation(ctx context.Context, parentWayID, childWayID string) error {
	response, err := gs.generalAPI.CompositeWayAPI.DeleteCompositeWayRelation(ctx, parentWayID, childWayID).Execute()
	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

//type DayReportService struct {
//	dayReportRepository IDayReportRepository
//}
//
//func NewDayReportService(dayReportRepository IDayReportRepository) *DayReportService {
//	return &DayReportService{dayReportRepository}
//}

type GetDayReportsByWayIdParams struct {
	WayUUID string
	Page    int
	Limit   int
}

func (gs *GeneralService) GetDayReportsByWayID(ctx context.Context, params *GetDayReportsByWayIdParams) (*openapiGeneral.MwServerInternalSchemasListDayReportsResponse, error) {
	reports, response, err := gs.generalAPI.DayReportAPI.GetDayReports(ctx, params.WayUUID).Page(int32(params.Page)).Limit(int32(params.Limit)).Execute()
	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}
	return reports, nil
}

type GetLastDayReportDateResponse struct {
	TotalStartDate time.Time
	EndDate        time.Time
}

func (gs *GeneralService) CreateDayReport(ctx context.Context, wayID string) (*openapiGeneral.MwServerInternalSchemasCompositeDayReportPopulatedResponse, error) {
	dayReports, response, err := gs.generalAPI.DayReportAPI.CreateDayReport(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateDayReportPayload{
		WayId: wayID,
	}).Execute()
	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}
	return dayReports, nil
}

func (gs *GeneralService) CreateFavoriteUser(ctx context.Context, payload *schemas.CreateFavoriteUserPayload) error {
	response, err := gs.generalAPI.FavoriteUserAPI.CreateFavoriteUser(ctx).
		Request(openapiGeneral.MwServerInternalSchemasCreateFavoriteUserPayload{
			DonorUserUuid:    payload.DonorUserUuid.String(),
			AcceptorUserUuid: payload.AcceptorUserUuid.String(),
		}).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) DeleteFavoriteUserById(ctx context.Context, donorUserUuid, acceptorUserUuid string) error {
	response, err := gs.generalAPI.FavoriteUserAPI.DeleteFavoriteUser(ctx, donorUserUuid, acceptorUserUuid).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreateFavoriteUserWay(ctx context.Context, userUUID, wayUUID uuid.UUID) error {
	response, err := gs.generalAPI.FavoriteUserWayAPI.CreateFavoriteUserWay(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateFavoriteUserWayPayload{
		UserUuid: userUUID.String(),
		WayUuid:  wayUUID.String(),
	}).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (fuws *GeneralService) DeleteFavoriteUserWayById(ctx context.Context, userID, wayID string) error {
	response, err := fuws.generalAPI.FavoriteUserWayAPI.DeleteFavoriteUserWay(ctx, userID, wayID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreateFromUserMentoringRequest(ctx context.Context, userID, wayID string) (*schemas.FromUserMentoringRequestResponse, error) {
	fromUserMentoringRaw, response, err := gs.generalAPI.FromUserMentoringRequestAPI.CreateFromUserMentoringRequest(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateFromUserMentoringRequestPayload{
		UserUuid: userID,
		WayUuid:  wayID,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	result := &schemas.FromUserMentoringRequestResponse{
		UserID: fromUserMentoringRaw.UserId,
		WayID:  fromUserMentoringRaw.WayId,
	}

	return result, nil
}

func (gs *GeneralService) DeleteFromUserMentoringRequestById(ctx context.Context, userID, wayID string) error {
	response, err := gs.generalAPI.FromUserMentoringRequestAPI.DeleteFromUserMentoringRequest(ctx, userID, wayID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreateMetricsPrompt(ctx context.Context, payload *schemas.GenerateMetricsPayload) (*schemas.GenerateMetricsResponse, error) {
	metricsRow, response, err := gs.generalAPI.GeminiAPI.GenerateMetrics(ctx).Request(openapiGeneral.MwServerInternalSchemasGenerateMetricsPayload{
		GoalDescription: payload.GoalDescription,
		Metrics:         payload.Metrics,
		WayName:         payload.WayName,
		Language:        payload.Language,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	metrics := &schemas.GenerateMetricsResponse{
		Metrics: &metricsRow.Metrics,
	}

	return metrics, nil
}

func (gs *GeneralService) AIChat(ctx context.Context, payload *schemas.AIChatPayload) (*schemas.AIChatResponse, error) {
	aiChatRow, response, err := gs.generalAPI.GeminiAPI.AiChat(ctx).Request(openapiGeneral.MwServerInternalSchemasAIChatPayload{
		Message:  payload.Message,
		Language: payload.Language,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}
	aiChat := &schemas.AIChatResponse{
		Message: aiChatRow.Message,
	}

	return aiChat, nil
}

func (gs *GeneralService) GeneratePlansByMetric(ctx context.Context, payload *schemas.AIGeneratePlansByMetricPayload) (*schemas.AIGeneratePlansByMetricResponse, error) {
	plansRaw, response, err := gs.generalAPI.GeminiAPI.AiPlansByMetrics(ctx).Request(openapiGeneral.MwServerInternalSchemasAIGeneratePlansByMetricPayload{
		Goal:     payload.Goal,
		Metric:   payload.Metric,
		Language: payload.Language,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	plans := &schemas.AIGeneratePlansByMetricResponse{
		Plans: plansRaw.Plans,
	}

	return plans, nil
}

func (gs *GeneralService) CommentIssue(ctx context.Context, payload *schemas.AICommentIssuePayload) (*schemas.AICommentIssueResponse, error) {
	commentRaw, response, err := gs.generalAPI.GeminiAPI.AiCommentIssue(ctx).Request(openapiGeneral.MwServerInternalSchemasAICommentIssuePayload{
		Goal:     payload.Goal,
		Message:  payload.Message,
		Language: payload.Language,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	comment := &schemas.AICommentIssueResponse{
		Comment: commentRaw.Goal,
	}

	return comment, nil
}

func (gs *GeneralService) DecomposeIssue(ctx context.Context, payload *schemas.AIDecomposeIssuePayload) (*schemas.AIDecomposeIssueResponse, error) {
	plansRaw, response, err := gs.generalAPI.GeminiAPI.AiDecomposeIssue(ctx).Request(openapiGeneral.MwServerInternalSchemasAIDecomposeIssuePayload{
		Goal:     payload.Goal,
		Message:  payload.Message,
		Language: payload.Language,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	decompose := &schemas.AIDecomposeIssueResponse{
		Plans: plansRaw.Plans,
	}

	return decompose, nil
}

func (gs *GeneralService) EstimateIssue(ctx context.Context, payload *schemas.AIEstimateIssuePayload) (*schemas.AIEstimateIssueResponse, error) {
	estimateRaw, response, err := gs.generalAPI.GeminiAPI.AiEstimateIssue(ctx).Request(openapiGeneral.MwServerInternalSchemasAIEstimateIssuePayload{
		Goal:     payload.Goal,
		Issue:    payload.Issue,
		Language: payload.Language,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	estimate := &schemas.AIEstimateIssueResponse{
		Estimation: estimateRaw.Estimation,
	}

	return estimate, nil
}

type GenerateTopicsForTrainingParams struct {
	TopicsAmount               int32
	TrainingName               string
	TrainingDescription        string
	Language                   string
	FullParentTopicDescription *string
}

func (gs *GeneralService) GenerateTopicsForTraining(ctx context.Context, payload *GenerateTopicsForTrainingParams) (*openapiGeneral.MwServerInternalSchemasAIGenerateTopicsForTrainingResponse, error) {
	var fullParentTopicDescription = openapiGeneral.NullableString{}
	fullParentTopicDescription.Set(payload.FullParentTopicDescription)

	estimateRaw, response, err := gs.generalAPI.GeminiAPI.AiTopicForTraining(ctx).Request(openapiGeneral.MwServerInternalSchemasAIGenerateTopicsForTrainingPayload{
		TopicsAmount:               payload.TopicsAmount,
		TrainingName:               payload.TrainingName,
		Goal:                       payload.TrainingDescription,
		Language:                   payload.Language,
		FullParentTopicDescription: fullParentTopicDescription,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return estimateRaw, nil
}

type GenerateTheoryMaterialForTrainingParams struct {
	ExistentPracticeMaterials []string
	ExistentTheoryMaterials   []string
	TopicName                 string
	TrainingDescription       string
	TrainingName              string
	Language                  string
}

func (gs *GeneralService) GenerateTheoryMaterialForTraining(ctx context.Context, payload *GenerateTheoryMaterialForTrainingParams) (*openapiGeneral.MwServerInternalSchemasAIGenerateTheoryMaterialForTopicResponse, error) {
	theoryMaterialsRaw, response, err := gs.generalAPI.GeminiAPI.AiTheoryMaterialForTopic(ctx).Request(openapiGeneral.MwServerInternalSchemasAIGenerateTheoryMaterialForTopicPayload{
		ExistentPracticeMaterials: payload.ExistentPracticeMaterials,
		ExistentTheoryMaterials:   payload.ExistentTheoryMaterials,
		TopicName:                 payload.TopicName,
		TrainingName:              payload.TrainingName,
		TrainingDescription:       payload.TrainingDescription,
		Language:                  payload.Language,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return theoryMaterialsRaw, nil
}

type GeneratePracticeMaterialForTrainingPayload struct {
	ExistentPracticeMaterials []string
	ExistentTheoryMaterials   []string
	TopicName                 string
	TrainingDescription       string
	TrainingName              string
	GenerateAmount            int32
	Language                  string
}

func (gs *GeneralService) GeneratePracticeMaterialForTraining(ctx context.Context, payload *GeneratePracticeMaterialForTrainingPayload) (*schemas.AIGeneratePracticeMaterialsForTrainingResponse, error) {
	practiceMaterialsRaw, response, err := gs.generalAPI.GeminiAPI.AiPracticeMaterialForTopic(ctx).Request(openapiGeneral.MwServerInternalSchemasAIGeneratePracticeMaterialForTopicPayload{
		ExistentPracticeMaterials: payload.ExistentPracticeMaterials,
		ExistentTheoryMaterials:   payload.ExistentTheoryMaterials,
		TopicName:                 payload.TopicName,
		TrainingName:              payload.TrainingName,
		TrainingDescription:       payload.TrainingDescription,
		GenerateAmount:            payload.GenerateAmount,
		Language:                  payload.Language,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	partialGeneratedPracticeMaterials := lo.Map(practiceMaterialsRaw.GetPracticeMaterials(), func(material openapiGeneral.MwServerInternalSchemasGeneratedPracticeMaterial, _ int) schemas.GeneratedPracticeMaterial {
		return schemas.GeneratedPracticeMaterial{
			Name:            material.Name,
			Answer:          material.Answer,
			TaskDescription: material.TaskDescription,
			TimeToAnswer:    material.TimeToAnswer,
		}
	})

	GeneratedPracticeMaterials := &schemas.AIGeneratePracticeMaterialsForTrainingResponse{
		PracticeMaterials: partialGeneratedPracticeMaterials,
	}

	return GeneratedPracticeMaterials, nil
}

func (gs *GeneralService) CreateJobDone(ctx context.Context, payload *schemas.CreateJobDonePayload) (*openapiGeneral.MwServerInternalSchemasJobDonePopulatedResponse, error) {
	jobDone, response, err := gs.generalAPI.JobDoneAPI.CreateJobDone(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateJobDonePayload{
		DayReportUuid: payload.DayReportUuid,
		Description:   payload.Description,
		JobTagUuids:   payload.JobTagUuids,
		OwnerUuid:     payload.OwnerUuid,
		Time:          payload.Time,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return jobDone, nil
}

type UpdateJobDoneParams struct {
	JobDoneID        string
	Description      *string
	Time             *int32
	ModifierUserUuid string
}

func (gs *GeneralService) UpdateJobDone(ctx context.Context, params *UpdateJobDoneParams) (*openapiGeneral.MwServerInternalSchemasJobDonePopulatedResponse, error) {
	jobDone, response, err := gs.generalAPI.JobDoneAPI.UpdateJobDone(ctx, params.JobDoneID).Request(openapiGeneral.MwServerInternalSchemasUpdateJobDone{
		Description: params.Description,
		Time:        params.Time,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return jobDone, nil
}

func (gs *GeneralService) DeleteJobDoneByID(ctx context.Context, jobDoneID string) error {
	response, err := gs.generalAPI.JobDoneAPI.DeleteJobDone(ctx, jobDoneID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreateJobDoneJobTag(ctx context.Context, payload *schemas.CreateJobDoneJobTagPayload) error {
	response, err := gs.generalAPI.JobDoneJobTagAPI.CreateJobDoneJobTag(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateJobDoneJobTagPayload{
		JobDoneUuid: payload.JobDoneUuid,
		JobTagUuid:  payload.JobTagUuid,
	}).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) DeleteJobDoneJobTagById(ctx context.Context, jobDoneID, jobTagID string) error {
	response, err := gs.generalAPI.JobDoneJobTagAPI.DeleteJobDoneJobTag(ctx, jobDoneID, jobTagID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreateJobTag(ctx context.Context, payload *schemas.CreateJobTagPayload) (*schemas.JobTagResponse, error) {
	jobTagRaw, response, err := gs.generalAPI.JobTagAPI.CreateJobTag(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateJobTagPayload{
		Color:       payload.Color,
		Description: payload.Description,
		Name:        payload.Name,
		WayUuid:     payload.WayUuid,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	jobTag := &schemas.JobTagResponse{
		Uuid:        jobTagRaw.Uuid,
		Name:        jobTagRaw.Name,
		Description: jobTagRaw.Description,
		Color:       jobTagRaw.Color,
	}

	return jobTag, nil

}

type UpdateJobTagParams struct {
	JobTagID    string
	Name        string
	Description string
	Color       string
}

func (gs *GeneralService) UpdateJobTag(ctx context.Context, params *UpdateJobTagParams) (*schemas.JobTagResponse, error) {
	jobTagRaw, response, err := gs.generalAPI.JobTagAPI.UpdateJobTag(ctx, params.JobTagID).Request(openapiGeneral.MwServerInternalSchemasUpdateJobTagPayload{
		Name:        &params.Name,
		Description: &params.Description,
		Color:       &params.Color,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	jobTag := &schemas.JobTagResponse{
		Uuid:        jobTagRaw.Uuid,
		Name:        jobTagRaw.Name,
		Description: jobTagRaw.Description,
		Color:       jobTagRaw.Color,
	}

	return jobTag, nil
}

func (gs *GeneralService) DeleteJobTagById(ctx context.Context, jobTagID string) error {
	response, err := gs.generalAPI.JobTagAPI.DeleteJobTag(ctx, jobTagID).Execute()
	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) AddMentorUserWay(ctx context.Context, userID, wayID string) error {
	response, err := gs.generalAPI.MentorUserWayAPI.CreateMentorUserWay(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateMentorUserWayPayload{
		UserUuid: userID,
		WayUuid:  wayID,
	}).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) DeleteMentorUserWay(ctx context.Context, userID, wayID string) error {
	response, err := gs.generalAPI.MentorUserWayAPI.DeleteMentorUserWay(ctx).Request(openapiGeneral.MwServerInternalSchemasDeleteMentorUserWayPayload{
		UserUuid: userID,
		WayUuid:  wayID,
	}).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreateMetric(ctx context.Context, payload *schemas.CreateMetricPayload) (*openapiGeneral.MwServerInternalSchemasMetricResponse, error) {
	var DoneDate, ParentUuid openapiGeneral.NullableString

	DoneDate.Set(payload.DoneDate)
	ParentUuid.Set(payload.ParentUuid)

	metric, response, err := gs.generalAPI.MetricAPI.CreateMetric(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateMetricPayload{
		Description:    payload.Description,
		DoneDate:       DoneDate,
		EstimationTime: payload.MetricEstimation,
		IsDone:         payload.IsDone,
		WayUuid:        payload.WayUuid,
		ParentUuid:     ParentUuid,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return metric, nil
}

type UpdateMetricParams struct {
	MetricID         string
	Description      *string
	IsDone           *bool
	MetricEstimation *int32
}

func (gs *GeneralService) UpdateMetric(ctx context.Context, params *UpdateMetricParams) (*openapiGeneral.MwServerInternalSchemasMetricResponse, error) {
	metric, response, err := gs.generalAPI.MetricAPI.UpdateMetric(ctx, params.MetricID).Request(openapiGeneral.MwServerInternalSchemasUpdateMetricPayload{
		Description:    params.Description,
		EstimationTime: params.MetricEstimation,
		IsDone:         params.IsDone,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return metric, nil
}

func (gs *GeneralService) DeleteMetricById(ctx context.Context, metricID string) error {
	response, err := gs.generalAPI.MetricAPI.DeleteMetric(ctx, metricID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreatePlan(ctx context.Context, payload *schemas.CreatePlanPayload) (*openapiGeneral.MwServerInternalSchemasPlanPopulatedResponse, error) {
	plan, response, err := gs.generalAPI.PlanAPI.CreatePlan(ctx).Request(openapiGeneral.MwServerInternalSchemasCreatePlanPayload{
		DayReportUuid: payload.DayReportUuid,
		Description:   payload.Description,
		IsDone:        payload.IsDone,
		OwnerUuid:     payload.OwnerUuid,
		Time:          payload.Time,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return plan, nil
}

type UpdatePlanParams struct {
	PlanID           string
	Description      *string
	Time             *int32
	IsDone           *bool
	ModifierUserUuid string
}

func (gs *GeneralService) UpdatePlan(ctx context.Context, params *UpdatePlanParams) (*openapiGeneral.MwServerInternalSchemasPlanPopulatedResponse, error) {
	plan, response, err := gs.generalAPI.PlanAPI.UpdatePlan(ctx, params.PlanID).Request(openapiGeneral.MwServerInternalSchemasUpdatePlanPayload{
		Description: params.Description,
		IsDone:      params.IsDone,
		Time:        params.Time,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return plan, nil
}

func (gs *GeneralService) DeletePlanById(ctx context.Context, planID string) error {
	response, err := gs.generalAPI.PlanAPI.DeletePlan(ctx, planID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreatePlanJobTag(ctx context.Context, payload *schemas.CreatePlanJobTagPayload) error {
	response, err := gs.generalAPI.PlanJobTagAPI.CreatePlanJobTag(ctx).Request(openapiGeneral.MwServerInternalSchemasCreatePlanJobTagPayload{
		JobTagUuid: payload.JobTagUuid,
		PlanUuid:   payload.PlanUuid,
	}).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil

}

func (gs *GeneralService) DeletePlanJobTagById(ctx context.Context, planID, jobTagID string) error {
	response, err := gs.generalAPI.PlanJobTagAPI.DeletePlanJobTag(ctx, jobTagID, planID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreateProblem(ctx context.Context, payload *schemas.CreateProblemPayload) (*openapiGeneral.MwServerInternalSchemasProblemPopulatedResponse, error) {
	problem, response, err := gs.generalAPI.ProblemAPI.CreateProblem(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateProblemPayload{
		DayReportUuid: payload.DayReportUuid,
		Description:   payload.Description,
		IsDone:        payload.IsDone,
		OwnerUuid:     payload.OwnerUuid,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return problem, nil
}

type UpdateProblemParams struct {
	ProblemID        string
	Description      *string
	IsDone           *bool
	ModifierUserUuid string
}

func (gs *GeneralService) UpdateProblem(ctx context.Context, params *UpdateProblemParams) (*openapiGeneral.MwServerInternalSchemasProblemPopulatedResponse, error) {
	problem, response, err := gs.generalAPI.ProblemAPI.UpdateProblem(ctx, params.ProblemID).Request(openapiGeneral.MwServerInternalSchemasUpdateProblemPayload{
		Description: params.Description,
		IsDone:      params.IsDone,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return problem, nil
}

func (gs *GeneralService) DeleteProblemById(ctx context.Context, problemID string) error {
	response, err := gs.generalAPI.ProblemAPI.DeleteProblem(ctx, problemID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) CreateProject(ctx context.Context, payload *schemas.CreateProjectPayload) (*openapiGeneral.MwServerInternalSchemasProjectPopulatedResponse, error) {
	project, response, err := gs.generalAPI.ProjectAPI.CreateProject(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateProjectPayload{
		Name:    payload.Name,
		OwnerId: payload.OwnerID,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return project, nil
}

type UpdateProjectParams struct {
	ID        string
	Name      *string
	IsPrivate *bool
}

func (gs *GeneralService) UpdateProject(ctx context.Context, params *UpdateProjectParams) (*openapiGeneral.MwServerInternalSchemasProjectPopulatedResponse, error) {
	project, response, err := gs.generalAPI.ProjectAPI.UpdateProject(ctx, params.ID).Request(openapiGeneral.MwServerInternalSchemasUpdateProjectPayload{
		IsPrivate: params.IsPrivate,
		Name:      params.Name,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return project, nil
}

func (gs *GeneralService) GetProjectByID(ctx context.Context, projectID string) (*openapiGeneral.MwServerInternalSchemasProjectPopulatedResponse, error) {
	project, response, err := gs.generalAPI.ProjectAPI.GetProject(ctx, projectID).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return project, nil
}

func (gs *GeneralService) DeleteProjectByID(ctx context.Context, projectID string) error {
	response, err := gs.generalAPI.ProjectAPI.DeleteProject(ctx, projectID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}
	return nil
}

func (gs *GeneralService) CreateToUserMentoringRequest(ctx context.Context, payload *schemas.CreateToUserMentoringRequestPayload) (*openapiGeneral.MwServerInternalSchemasToUserMentoringRequestResponse, error) {
	userMentoringRequest, response, err := gs.generalAPI.ToUserMentoringRequestAPI.CreateUserMentoringRequest(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateToUserMentoringRequestPayload{
		UserUuid: payload.UserUuid,
		WayUuid:  payload.WayUuid,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return userMentoringRequest, nil
}

func (gs *GeneralService) DeleteToUserMentoringRequestById(ctx context.Context, userID, wayID string) error {
	response, err := gs.generalAPI.ToUserMentoringRequestAPI.DeleteToUserMentoringRequest(ctx, userID, wayID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

type UpdateUserParams struct {
	UserID      string
	Name        *string
	Description *string
	ImageUrl    *string
	IsMentor    *bool
}

func (gs *GeneralService) UpdateUser(ctx context.Context, params *UpdateUserParams) (*openapiGeneral.MwServerInternalSchemasUserPlainResponse, error) {
	user, response, err := gs.generalAPI.UserAPI.UpdateUser(ctx, params.UserID).Request(openapiGeneral.MwServerInternalSchemasUpdateUserPayload{
		Description: params.Description,
		ImageUrl:    params.ImageUrl,
		IsMentor:    params.IsMentor,
		Name:        params.Name,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return user, nil
}

type GetAllUsersParams struct {
	MentorStatus string
	UserName     string
	UserEmail    string
	Page         int
	Limit        int
}

func (gs *GeneralService) GetAllUsers(ctx context.Context, params *GetAllUsersParams) (*openapiGeneral.MwServerInternalSchemasGetAllUsersResponse, error) {
	users, response, err := gs.generalAPI.UserAPI.GetAllUsers(ctx).
		MentorStatus(params.MentorStatus).
		Name(params.UserName).
		Email(params.UserEmail).
		Page(int32(params.Page)).
		Limit(int32(params.Limit)).
		Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return users, nil
}

type dbWay struct {
	Uuid                uuid.UUID
	Name                string
	OwnerUuid           uuid.UUID
	GoalDescription     string
	UpdatedAt           time.Time
	CreatedAt           time.Time
	EstimationTime      int32
	CopiedFromWayUuid   uuid.UUID
	ProjectUuid         uuid.UUID
	IsCompleted         bool
	IsPrivate           bool
	WayMetricsTotal     int64
	WayMetricsDone      int64
	WayFavoriteForUsers int64
	WayDayReportsAmount int64
	ChildrenUuids       []string
}

func (gs *GeneralService) GetPopulatedUserById(ctx context.Context, userUuid uuid.UUID) (*openapiGeneral.MwServerInternalSchemasUserPopulatedResponse, error) {
	user, response, err := gs.generalAPI.UserAPI.GetUserByUuid(ctx, userUuid.String()).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return user, nil
}

func mapWayCollection(collection openapiGeneral.MwServerInternalSchemasWayCollectionPopulatedResponse) schemas.WayCollectionPopulatedResponse {
	return schemas.WayCollectionPopulatedResponse{
		Uuid:      collection.Uuid,
		Name:      collection.Name,
		Ways:      lo.Map(collection.Ways, mapWayPlainResponse),
		CreatedAt: collection.CreatedAt,
		UpdatedAt: collection.UpdatedAt,
		OwnerUuid: collection.OwnerUuid,
		Type:      collection.Type,
	}
}

func mapWayPlainResponse(way openapiGeneral.MwServerInternalSchemasWayPlainResponse, _ int) schemas.WayPlainResponse {
	return schemas.WayPlainResponse{
		Uuid:              way.Uuid,
		Name:              way.Name,
		GoalDescription:   way.GoalDescription,
		UpdatedAt:         way.UpdatedAt,
		CreatedAt:         way.CreatedAt,
		EstimationTime:    way.EstimationTime,
		IsCompleted:       way.IsCompleted,
		Owner:             mapUserPlainResponse(way.Owner, 1),
		CopiedFromWayUuid: way.CopiedFromWayUuid.Get(),
		ProjectUuid:       way.ProjectUuid.Get(),
		IsPrivate:         way.IsPrivate,
		FavoriteForUsers:  way.FavoriteForUsers,
		DayReportsAmount:  way.DayReportsAmount,
		Mentors:           lo.Map(way.Mentors, mapUserPlainResponse),
		WayTags:           lo.Map(way.WayTags, mapWayTagResponse),
		MetricsDone:       way.MetricsDone,
		MetricsTotal:      way.MetricsTotal,
		ChildrenUuids:     way.ChildrenUuids,
	}
}

func mapUserPlainResponse(user openapiGeneral.MwServerInternalSchemasUserPlainResponse, _ int) schemas.UserPlainResponse {
	return schemas.UserPlainResponse{
		Uuid:        user.Uuid,
		Name:        user.Name,
		Email:       user.Email,
		Description: user.Description,
		CreatedAt:   user.CreatedAt,
		ImageUrl:    user.ImageUrl,
		IsMentor:    user.IsMentor,
	}
}

func mapUserTagResponse(tag openapiGeneral.MwServerInternalSchemasUserTagResponse, _ int) schemas.UserTagResponse {
	return schemas.UserTagResponse{
		Uuid: tag.Uuid,
		Name: tag.Name,
	}
}

func mapWayTagResponse(tag openapiGeneral.MwServerInternalSchemasWayTagResponse, _ int) schemas.WayTagResponse {
	return schemas.WayTagResponse{
		Uuid: tag.Uuid,
		Name: tag.Name,
	}
}

func mapProjectPlainResponse(project openapiGeneral.MwServerInternalSchemasProjectPlainResponse, _ int) schemas.ProjectPlainResponse {
	return schemas.ProjectPlainResponse{
		ID:        project.Id,
		Name:      project.Name,
		UserIDs:   project.UserIds,
		IsPrivate: project.IsPrivate,
	}
}

func (gs *GeneralService) CreateUserProject(ctx context.Context, userID, projectID string) error {
	response, err := gs.generalAPI.UserProjectAPI.CreateUserProject(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateUserProjectPayload{
		ProjectId: projectID,
		UserId:    userID,
	}).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) DeleteUserProject(ctx context.Context, projectID, userID string) error {
	response, err := gs.generalAPI.UserProjectAPI.DeleteUserProject(ctx, projectID, userID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) AddUserTagByName(ctx context.Context, payload *schemas.CreateUserTagPayload) (*openapiGeneral.MwServerInternalSchemasUserTagResponse, error) {
	userTag, response, err := gs.generalAPI.UserTagAPI.CreateUserTag(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateUserTagPayload{
		Name:      payload.Name,
		OwnerUuid: payload.OwnerUuid,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return userTag, nil
}

func (gs *GeneralService) DeleteUserTagByFromUserByTag(ctx context.Context, userTagID, userID string) error {
	response, err := gs.generalAPI.UserTagAPI.DeleteUserTag(ctx, userTagID, userID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

type GetPopulatedWayByIdParams struct {
	WayUuid              uuid.UUID
	CurrentChildrenDepth int32
}

func (gs *GeneralService) CreateWay(ctx context.Context, payload *schemas.CreateWayPayload) (*openapiGeneral.MwServerInternalSchemasWayPlainResponse, error) {
	var CopiedFromWayID, ProjectID openapiGeneral.NullableString

	CopiedFromWayID.Set(payload.CopiedFromWayID)
	ProjectID.Set(payload.ProjectID)

	way, response, err := gs.generalAPI.WayAPI.CreateWay(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateWayPayload{
		CopiedFromWayId: CopiedFromWayID,
		EstimationTime:  payload.EstimationTime,
		GoalDescription: payload.GoalDescription,
		IsCompleted:     payload.IsCompleted,
		IsPrivate:       payload.IsPrivate,
		Name:            payload.Name,
		OwnerId:         payload.OwnerID,
		ProjectId:       ProjectID,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return way, nil
}

func mapOwner(ownerRaw openapiGeneral.MwServerInternalSchemasUserPlainResponse) schemas.UserPlainResponse {
	return schemas.UserPlainResponse{
		Uuid:        ownerRaw.Uuid,
		Name:        ownerRaw.Name,
		Email:       ownerRaw.Email,
		Description: ownerRaw.Description,
		CreatedAt:   ownerRaw.CreatedAt,
		ImageUrl:    ownerRaw.ImageUrl,
		IsMentor:    ownerRaw.IsMentor,
	}
}

func mapMentors(mentorsRaw []openapiGeneral.MwServerInternalSchemasUserPlainResponse) []schemas.UserPlainResponse {
	mentors := make([]schemas.UserPlainResponse, len(mentorsRaw))
	for i, mentor := range mentorsRaw {
		mentors[i] = schemas.UserPlainResponse{
			Uuid:        mentor.Uuid,
			Name:        mentor.Name,
			Email:       mentor.Email,
			Description: mentor.Description,
			CreatedAt:   mentor.CreatedAt,
			ImageUrl:    mentor.ImageUrl,
			IsMentor:    mentor.IsMentor,
		}
	}
	return mentors
}

func mapWayTags(tagsRaw []openapiGeneral.MwServerInternalSchemasWayTagResponse) []schemas.WayTagResponse {
	wayTags := make([]schemas.WayTagResponse, len(tagsRaw))
	for i, tag := range tagsRaw {
		wayTags[i] = schemas.WayTagResponse{
			Uuid: tag.Uuid,
			Name: tag.Name,
		}
	}
	return wayTags
}

type UpdateWayParams struct {
	WayID           string
	Name            string
	GoalDescription string
	EstimationTime  int32
	IsPrivate       *bool
	IsCompleted     bool
}

func (gs *GeneralService) UpdateWay(ctx context.Context, params *UpdateWayParams) (*openapiGeneral.MwServerInternalSchemasWayPlainResponse, error) {
	way, response, err := gs.generalAPI.WayAPI.UpdateWay(ctx, params.WayID).Request(openapiGeneral.MwServerInternalSchemasUpdateWayPayload{
		EstimationTime:  &params.EstimationTime,
		GoalDescription: &params.GoalDescription,
		IsCompleted:     &params.IsCompleted,
		IsPrivate:       params.IsPrivate,
		Name:            &params.Name,
	}).Execute()
	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return way, nil
}

type GetAllWaysParams struct {
	Status                 string
	WayName                string
	ReqMinDayReportsAmount int
	Page                   int
	Limit                  int
}

func (gs *GeneralService) GetAllWays(ctx context.Context, params *GetAllWaysParams) (*openapiGeneral.MwServerInternalSchemasGetAllWaysResponse, error) {
	ways, response, err := gs.generalAPI.WayAPI.GetAllWays(ctx).
		WayName(params.WayName).
		MinDayReportsAmount(int32(params.ReqMinDayReportsAmount)).
		Status(params.Status).
		Page(int32(params.Page)).
		Limit(int32(params.Limit)).
		Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return ways, nil
}

func mapWayPlainRes(wayRaw openapiGeneral.MwServerInternalSchemasWayPlainResponse) schemas.WayPlainResponse {
	return schemas.WayPlainResponse{
		Uuid:              wayRaw.Uuid,
		Name:              wayRaw.Name,
		GoalDescription:   wayRaw.GoalDescription,
		UpdatedAt:         wayRaw.UpdatedAt,
		CreatedAt:         wayRaw.CreatedAt,
		EstimationTime:    wayRaw.EstimationTime,
		IsCompleted:       wayRaw.IsCompleted,
		Owner:             mapOwner(wayRaw.Owner),
		CopiedFromWayUuid: wayRaw.CopiedFromWayUuid.Get(),
		ProjectUuid:       wayRaw.ProjectUuid.Get(),
		IsPrivate:         wayRaw.IsPrivate,
		FavoriteForUsers:  wayRaw.FavoriteForUsers,
		DayReportsAmount:  wayRaw.DayReportsAmount,
		Mentors:           mapMentors(wayRaw.Mentors),
		WayTags:           mapWayTags(wayRaw.WayTags),
		MetricsDone:       wayRaw.MetricsDone,
		MetricsTotal:      wayRaw.MetricsTotal,
		ChildrenUuids:     wayRaw.ChildrenUuids,
	}
}
func (gs *GeneralService) DeleteWayById(ctx *gin.Context, wayID string) error {
	response, err := gs.generalAPI.WayAPI.DeleteWay(ctx, wayID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) GetWayById(ctx context.Context, wayUUID string) (*openapiGeneral.MwServerInternalSchemasWayPopulatedResponse, error) {
	way, response, err := gs.generalAPI.WayAPI.GetWayByUuid(ctx, wayUUID).Execute()
	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}
	return way, nil
}

func (gs *GeneralService) GetWayPlainForNotificationById(ctx context.Context, wayUUID string) (*openapiGeneral.MwServerInternalSchemasWayPlainForNotificationResponse, error) {
	way, response, err := gs.generalAPI.WayAPI.GetWayPlainForNotificationByUuid(ctx, wayUUID).Execute()
	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}
	return way, nil
}

func (gs *GeneralService) CreateWayCollection(ctx context.Context, payload *schemas.CreateWayCollectionPayload) (*openapiGeneral.MwServerInternalSchemasWayCollectionPopulatedResponse, error) {
	wayCollection, response, err := gs.generalAPI.WayCollectionAPI.CreateWayCollection(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateWayCollectionPayload{
		Name:      payload.Name,
		OwnerUuid: payload.OwnerUuid,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return wayCollection, nil
}

func (gs *GeneralService) UpdateWayCollection(ctx context.Context, wayCollectionID, wayCollectionName string) (*openapiGeneral.MwServerInternalSchemasWayCollectionPlainResponse, error) {
	wayCollection, response, err := gs.generalAPI.WayCollectionAPI.UpdateWayCollection(ctx, wayCollectionID).Request(openapiGeneral.MwServerInternalSchemasUpdateWayCollectionPayload{
		Name: &wayCollectionName,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return wayCollection, nil
}

func (gs *GeneralService) DeleteWayCollectionById(ctx context.Context, wayCollectionID string) error {
	response, err := gs.generalAPI.WayCollectionAPI.DeleteWayCollection(ctx, wayCollectionID).Execute()
	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}
	return nil
}

func (gs *GeneralService) CreateWayCollectionWay(ctx context.Context, payload *schemas.CreateWayCollectionWay) (*openapiGeneral.MwServerInternalSchemasWayCollectionWayResponse, error) {
	wayCollectionWay, response, err := gs.generalAPI.WayCollectionWayAPI.CreateWayCollectionWay(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateWayCollectionWay{
		WayUuid:           payload.WayUuid,
		WayCollectionUuid: payload.WayCollectionUuid,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return wayCollectionWay, nil
}

func (gs *GeneralService) DeleteWayCollectionWayById(ctx context.Context, wayID, wayCollectionID string) error {
	response, err := gs.generalAPI.WayCollectionWayAPI.DeleteWayCollectionWay(ctx, wayCollectionID, wayID).Execute()

	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

type GetWayStatisticsTriplePeriodParams struct {
	WayUUIDs       []uuid.UUID
	TotalStartDate time.Time
	EndDate        time.Time
}

func (gs *GeneralService) GetWayStatisticsById(ctx context.Context, wayUUID string) (*openapiGeneral.MwServerInternalSchemasWayStatisticsTriplePeriod, error) {
	wayStatistics, response, err := gs.generalAPI.WayAPI.GetWayStatisticsByUuid(ctx, wayUUID).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return wayStatistics, nil
}

func (gs *GeneralService) AddWayTagToWay(ctx context.Context, name, wayID string) (*openapiGeneral.MwServerInternalSchemasWayTagResponse, error) {
	wayTag, response, err := gs.generalAPI.WayTagAPI.CreateWayTag(ctx).Request(openapiGeneral.MwServerInternalSchemasCreateWayTagPayload{
		WayUuid: wayID,
		Name:    name,
	}).Execute()

	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	return wayTag, nil
}

func (gs *GeneralService) DeleteWayTagFromWayByTagID(ctx context.Context, wayTagID, wayID string) error {
	response, err := gs.generalAPI.WayTagAPI.DeleteWayTag(ctx, wayTagID, wayID).Execute()
	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}

	return nil
}

func (gs *GeneralService) GeneralHealthCheck(ctx context.Context) error {
	response, err := gs.generalAPI.HealthAPI.GeneralHealthCheck(ctx).Execute()
	if err != nil {
		return utils.ExtractErrorMessageFromResponse(response)
	}
	return nil
}

func (gs *GeneralService) GetUserByIds(ctx context.Context, userIDs []string) ([]schemas.ShortUser, error) {
	chatUsersData, response, err := gs.generalAPI.UserAPI.GetUsersByIds(ctx).Request(userIDs).Execute()
	if err != nil {
		return nil, utils.ExtractErrorMessageFromResponse(response)
	}

	shortUsers := lo.Map(chatUsersData, func(userData openapiGeneral.MwServerInternalSchemasShortUser, _ int) schemas.ShortUser {
		return schemas.ShortUser{
			UserID:   userData.UserId,
			Email:    userData.Email,
			Name:     userData.Name,
			ImageURL: userData.ImageUrl,
		}
	})

	return shortUsers, nil
}
