import {
  CreateProblemRequest,
  DeleteProblemRequest,
  GetProblemsByDayReportUuidRequest,
  SchemasProblemPopulatedResponse,
  UpdateProblemRequest,
} from "src/apiAutogenerated";
import {problemService} from "src/serviceUpdated/services";

/**
 * Provides methods to interact with the problems
 */
export class ProblemService {

  /**
   * Create problem
   */
  public static async createProblem(requestParameters: CreateProblemRequest): Promise<SchemasProblemPopulatedResponse> {
    const problem = await problemService.createProblem(requestParameters);

    return problem;
  }

  /**
   * Get problems by DayReport UUID
   */
  public static async GetProblems(
    requestParameters: GetProblemsByDayReportUuidRequest,
  ): Promise<SchemasProblemPopulatedResponse[]> {
    const problems = await problemService.getProblemsByDayReportUuid(requestParameters);

    return problems;
  }

  /**
   * Update problem
   */
  public static async updateProblem(requestParameters: UpdateProblemRequest): Promise<SchemasProblemPopulatedResponse> {
    const updatedProblem = await problemService.updateProblem(requestParameters);

    return updatedProblem;
  }

  /**
   * Delete problem by UUID
   */
  public static async deleteProblem(requestParameters: DeleteProblemRequest): Promise<void> {
    await problemService.deleteProblem(requestParameters);
  }

}
