// @ts-nocheck
/* eslint-disable */
/**
 * Masters way training-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwTrainingBffInternalSchemasGetTestSessionResultRequest
 */
export interface MwTrainingBffInternalSchemasGetTestSessionResultRequest {
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasGetTestSessionResultRequest
     */
    sessionUuid: string;
}

/**
 * Check if a given object implements the MwTrainingBffInternalSchemasGetTestSessionResultRequest interface.
 */
export function instanceOfMwTrainingBffInternalSchemasGetTestSessionResultRequest(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "sessionUuid" in value;

    return isInstance;
}

export function MwTrainingBffInternalSchemasGetTestSessionResultRequestFromJSON(json: any): MwTrainingBffInternalSchemasGetTestSessionResultRequest {
    return MwTrainingBffInternalSchemasGetTestSessionResultRequestFromJSONTyped(json, false);
}

export function MwTrainingBffInternalSchemasGetTestSessionResultRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwTrainingBffInternalSchemasGetTestSessionResultRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionUuid': json['session_uuid'],
    };
}


export function MwTrainingBffInternalSchemasGetTestSessionResultRequestToJSON(value?: MwTrainingBffInternalSchemasGetTestSessionResultRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'session_uuid': value.sessionUuid,
    };
}

