// @ts-nocheck
/* eslint-disable */
/**
 * Masters way training-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwTrainingBffInternalSchemasTestPreview
 */
export interface MwTrainingBffInternalSchemasTestPreview {
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTestPreview
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTestPreview
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTestPreview
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTestPreview
     */
    ownerUuid: string;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTestPreview
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTestPreview
     */
    uuid: string;
}

/**
 * Check if a given object implements the MwTrainingBffInternalSchemasTestPreview interface.
 */
export function instanceOfMwTrainingBffInternalSchemasTestPreview(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "ownerUuid" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "uuid" in value;

    return isInstance;
}

export function MwTrainingBffInternalSchemasTestPreviewFromJSON(json: any): MwTrainingBffInternalSchemasTestPreview {
    return MwTrainingBffInternalSchemasTestPreviewFromJSONTyped(json, false);
}

export function MwTrainingBffInternalSchemasTestPreviewFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwTrainingBffInternalSchemasTestPreview {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'description': json['description'],
        'name': json['name'],
        'ownerUuid': json['owner_uuid'],
        'updatedAt': json['updated_at'],
        'uuid': json['uuid'],
    };
}


export function MwTrainingBffInternalSchemasTestPreviewToJSON(value?: MwTrainingBffInternalSchemasTestPreview | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'description': value.description,
        'name': value.name,
        'owner_uuid': value.ownerUuid,
        'updated_at': value.updatedAt,
        'uuid': value.uuid,
    };
}

