// @ts-nocheck
/* eslint-disable */
/**
 * Masters way training-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwTrainingBffInternalSchemasUpdateTrainingPayload
 */
export interface MwTrainingBffInternalSchemasUpdateTrainingPayload {
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasUpdateTrainingPayload
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MwTrainingBffInternalSchemasUpdateTrainingPayload
     */
    isPrivate?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasUpdateTrainingPayload
     */
    name?: string;
}

/**
 * Check if a given object implements the MwTrainingBffInternalSchemasUpdateTrainingPayload interface.
 */
export function instanceOfMwTrainingBffInternalSchemasUpdateTrainingPayload(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function MwTrainingBffInternalSchemasUpdateTrainingPayloadFromJSON(json: any): MwTrainingBffInternalSchemasUpdateTrainingPayload {
    return MwTrainingBffInternalSchemasUpdateTrainingPayloadFromJSONTyped(json, false);
}

export function MwTrainingBffInternalSchemasUpdateTrainingPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwTrainingBffInternalSchemasUpdateTrainingPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'isPrivate': !exists(json, 'isPrivate') ? undefined : json['isPrivate'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}


export function MwTrainingBffInternalSchemasUpdateTrainingPayloadToJSON(value?: MwTrainingBffInternalSchemasUpdateTrainingPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'isPrivate': value.isPrivate,
        'name': value.name,
    };
}

