// @ts-nocheck
/* eslint-disable */
/**
 * Masters way training-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MwTrainingBffInternalSchemasTopicTreeNode } from './MwTrainingBffInternalSchemasTopicTreeNode';
import {
    MwTrainingBffInternalSchemasTopicTreeNodeFromJSON,
    MwTrainingBffInternalSchemasTopicTreeNodeFromJSONTyped,
    MwTrainingBffInternalSchemasTopicTreeNodeToJSON,
} from './MwTrainingBffInternalSchemasTopicTreeNode';
import type { MwTrainingBffInternalSchemasTrainingTag } from './MwTrainingBffInternalSchemasTrainingTag';
import {
    MwTrainingBffInternalSchemasTrainingTagFromJSON,
    MwTrainingBffInternalSchemasTrainingTagFromJSONTyped,
    MwTrainingBffInternalSchemasTrainingTagToJSON,
} from './MwTrainingBffInternalSchemasTrainingTag';
import type { MwTrainingBffInternalSchemasUser } from './MwTrainingBffInternalSchemasUser';
import {
    MwTrainingBffInternalSchemasUserFromJSON,
    MwTrainingBffInternalSchemasUserFromJSONTyped,
    MwTrainingBffInternalSchemasUserToJSON,
} from './MwTrainingBffInternalSchemasUser';

/**
 * 
 * @export
 * @interface MwTrainingBffInternalSchemasTraining
 */
export interface MwTrainingBffInternalSchemasTraining {
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    favoriteForUserUuids: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    isPrivate: boolean;
    /**
     * 
     * @type {Array<MwTrainingBffInternalSchemasUser>}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    mentors: Array<MwTrainingBffInternalSchemasUser>;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    name: string;
    /**
     * 
     * @type {MwTrainingBffInternalSchemasUser}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    owner: MwTrainingBffInternalSchemasUser;
    /**
     * 
     * @type {Array<MwTrainingBffInternalSchemasUser>}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    students: Array<MwTrainingBffInternalSchemasUser>;
    /**
     * 
     * @type {Array<MwTrainingBffInternalSchemasTopicTreeNode>}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    topicsTree: Array<MwTrainingBffInternalSchemasTopicTreeNode>;
    /**
     * 
     * @type {Array<MwTrainingBffInternalSchemasTrainingTag>}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    trainingTags: Array<MwTrainingBffInternalSchemasTrainingTag>;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof MwTrainingBffInternalSchemasTraining
     */
    uuid: string;
}

/**
 * Check if a given object implements the MwTrainingBffInternalSchemasTraining interface.
 */
export function instanceOfMwTrainingBffInternalSchemasTraining(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "favoriteForUserUuids" in value;
    isInstance = isInstance && "isPrivate" in value;
    isInstance = isInstance && "mentors" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "students" in value;
    isInstance = isInstance && "topicsTree" in value;
    isInstance = isInstance && "trainingTags" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "uuid" in value;

    return isInstance;
}

export function MwTrainingBffInternalSchemasTrainingFromJSON(json: any): MwTrainingBffInternalSchemasTraining {
    return MwTrainingBffInternalSchemasTrainingFromJSONTyped(json, false);
}

export function MwTrainingBffInternalSchemasTrainingFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwTrainingBffInternalSchemasTraining {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'description': json['description'],
        'favoriteForUserUuids': json['favoriteForUserUuids'],
        'isPrivate': json['isPrivate'],
        'mentors': ((json['mentors'] as Array<any>).map(MwTrainingBffInternalSchemasUserFromJSON)),
        'name': json['name'],
        'owner': MwTrainingBffInternalSchemasUserFromJSON(json['owner']),
        'students': ((json['students'] as Array<any>).map(MwTrainingBffInternalSchemasUserFromJSON)),
        'topicsTree': ((json['topicsTree'] as Array<any>).map(MwTrainingBffInternalSchemasTopicTreeNodeFromJSON)),
        'trainingTags': ((json['trainingTags'] as Array<any>).map(MwTrainingBffInternalSchemasTrainingTagFromJSON)),
        'updatedAt': json['updatedAt'],
        'uuid': json['uuid'],
    };
}


export function MwTrainingBffInternalSchemasTrainingToJSON(value?: MwTrainingBffInternalSchemasTraining | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'description': value.description,
        'favoriteForUserUuids': value.favoriteForUserUuids,
        'isPrivate': value.isPrivate,
        'mentors': ((value.mentors as Array<any>).map(MwTrainingBffInternalSchemasUserToJSON)),
        'name': value.name,
        'owner': MwTrainingBffInternalSchemasUserToJSON(value.owner),
        'students': ((value.students as Array<any>).map(MwTrainingBffInternalSchemasUserToJSON)),
        'topicsTree': ((value.topicsTree as Array<any>).map(MwTrainingBffInternalSchemasTopicTreeNodeToJSON)),
        'trainingTags': ((value.trainingTags as Array<any>).map(MwTrainingBffInternalSchemasTrainingTagToJSON)),
        'updatedAt': value.updatedAt,
        'uuid': value.uuid,
    };
}

