import {
  CreatePlanRequest,
  DeletePlanRequest,
  GetPlansByDayReportUuidRequest,
  SchemasPlanPopulatedResponse,
  UpdatePlanRequest,
} from "src/apiAutogenerated";
import {planService} from "src/service/services";

/**
 * Provides methods to interact with the plans
 */
export class ProblemService {

  /**
   * Create plan
   */
  public static async createPlan(requestParameters: CreatePlanRequest): Promise<SchemasPlanPopulatedResponse> {
    const plan = await planService.createPlan(requestParameters);

    return plan;
  }

  /**
   * Get plans by DayReport UUID
   */
  public static async GetPlans(requestParameters: GetPlansByDayReportUuidRequest): Promise<SchemasPlanPopulatedResponse[]> {
    const plans = await planService.getPlansByDayReportUuid(requestParameters);

    return plans;
  }

  /**
   * Update plan
   */
  public static async updatePlan(requestParameters: UpdatePlanRequest): Promise<SchemasPlanPopulatedResponse> {
    const updatedPlan = planService.updatePlan(requestParameters);

    return updatedPlan;
  }

  /**
   * Delete plan by UUID
   */
  public static async deletePlan(requestParameters: DeletePlanRequest): Promise<void> {
    await planService.deletePlan(requestParameters);
  }

}
