import {
  GetQuestionResultsBySessionUuidRequest,
  MwTrainingBffInternalSchemasQuestionResult,
} from "src/apiAutogenerated/training";
import {questionResultService} from "src/service/services";

/**
 * Provides methods to interact with the QuestionResults
 */
export class QuestionResultService {

  /**
   * Get question results by session Uuid
   */
  public static async getQuestionResultsBySessionUuid(
    requestParameters: GetQuestionResultsBySessionUuidRequest,
  ): Promise<MwTrainingBffInternalSchemasQuestionResult[]> {
    const questionResults = await questionResultService.getQuestionResultsBySessionUuid(requestParameters);

    return questionResults;
  }

}

