import {
  CreateWayRequest,
  DeleteWayRequest,
  GetAllWaysRequest,
  GetWayByUuidRequest,
  GetWayStatisticsByUuidRequest,
  MwGeneralBffInternalSchemasGetAllWaysResponse,
  MwGeneralBffInternalSchemasWayPlainResponse,
  MwGeneralBffInternalSchemasWayPopulatedResponse,
  MwGeneralBffInternalSchemasWayStatisticsTriplePeriod,
  UpdateWayRequest,
} from "src/apiAutogenerated/general";
import {Way} from "src/model/businessModel/Way";
import {wayService} from "src/service/services";

/**
 * WayDTO props without uuid
 */
export type WayDTOWithoutUuid = Omit<Way, "uuid">;

export type GetWaysFilter = {

  /**
   * Show only ways in progress
   */
  isInProgress?: boolean;

  /**
   * Show only completed ways
   */
  isCompleted?: boolean;

  /**
   * Show only abandoned ways
   */
  isAbandoned?: boolean;
}

/**
 * Pagination and filter params
 */
export interface GetWaysParams {

  /**
   * Page
   */
  page?: number;

  /**
   * Limit
   */
  limit?: number;

  /**
   * Status
   */
  status?: string;

  /**
   * Only ways with day reports amount bigger than here will be shown
   */
  minDayReportsAmount?: number;

  /**
   * Part of way name
   */
  wayName: string;

}

/**
 * Provides methods to interact with the Ways
 */
export class WayService {

  /**
   * Get all ways
   */
  public static async getAllWays(requestParameters: GetAllWaysRequest = {}):
    Promise<MwGeneralBffInternalSchemasGetAllWaysResponse> {
    const allWays = await wayService.getAllWays(requestParameters);

    return allWays;
  }

  /**
   * Create way
   */
  public static async createWay(requestParameters: CreateWayRequest): Promise<MwGeneralBffInternalSchemasWayPlainResponse> {
    const way = await wayService.createWay(requestParameters);

    return way;
  }

  /**
   * Get way by UUID
   */
  public static async getWayByUuid(requestParameters: GetWayByUuidRequest):
    Promise<MwGeneralBffInternalSchemasWayPopulatedResponse> {
    const way = await wayService.getWayByUuid(requestParameters);

    return way;
  }

  /**
   * Update way
   */
  public static async updateWay(requestParameters: UpdateWayRequest): Promise<MwGeneralBffInternalSchemasWayPlainResponse> {
    const updatedWay = await wayService.updateWay(requestParameters);

    return updatedWay;
  }

  /**
   * Delete way
   */
  public static async deleteWay(requestParameters: DeleteWayRequest): Promise<void> {
    await wayService.deleteWay(requestParameters);
  }

  /**
   * Get way statistics
   */
  public static async getWayStatisticTripleById(
    requestParameters: GetWayStatisticsByUuidRequest,
  ): Promise<MwGeneralBffInternalSchemasWayStatisticsTriplePeriod> {
    const statistics = await wayService.getWayStatisticsByUuid(requestParameters);

    return statistics;
  }

}

