/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwServerInternalSchemasCreatePlanForTelegramPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwServerInternalSchemasCreatePlanForTelegramPayload{}

// MwServerInternalSchemasCreatePlanForTelegramPayload struct for MwServerInternalSchemasCreatePlanForTelegramPayload
type MwServerInternalSchemasCreatePlanForTelegramPayload struct {
	Description string `json:"description"`
	IsDone bool `json:"isDone"`
	OwnerUuid string `json:"ownerUuid"`
	Time int32 `json:"time"`
	WayUuid string `json:"wayUuid"`
}

type _MwServerInternalSchemasCreatePlanForTelegramPayload MwServerInternalSchemasCreatePlanForTelegramPayload

// NewMwServerInternalSchemasCreatePlanForTelegramPayload instantiates a new MwServerInternalSchemasCreatePlanForTelegramPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwServerInternalSchemasCreatePlanForTelegramPayload(description string, isDone bool, ownerUuid string, time int32, wayUuid string) *MwServerInternalSchemasCreatePlanForTelegramPayload {
	this := MwServerInternalSchemasCreatePlanForTelegramPayload{}
	this.Description = description
	this.IsDone = isDone
	this.OwnerUuid = ownerUuid
	this.Time = time
	this.WayUuid = wayUuid
	return &this
}

// NewMwServerInternalSchemasCreatePlanForTelegramPayloadWithDefaults instantiates a new MwServerInternalSchemasCreatePlanForTelegramPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwServerInternalSchemasCreatePlanForTelegramPayloadWithDefaults() *MwServerInternalSchemasCreatePlanForTelegramPayload {
	this := MwServerInternalSchemasCreatePlanForTelegramPayload{}
	return &this
}

// GetDescription returns the Description field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) SetDescription(v string) {
	o.Description = v
}

// GetIsDone returns the IsDone field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetIsDone() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDone
}

// GetIsDoneOk returns a tuple with the IsDone field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetIsDoneOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDone, true
}

// SetIsDone sets field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) SetIsDone(v bool) {
	o.IsDone = v
}

// GetOwnerUuid returns the OwnerUuid field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetOwnerUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerUuid
}

// GetOwnerUuidOk returns a tuple with the OwnerUuid field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetOwnerUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerUuid, true
}

// SetOwnerUuid sets field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) SetOwnerUuid(v string) {
	o.OwnerUuid = v
}

// GetTime returns the Time field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) SetTime(v int32) {
	o.Time = v
}

// GetWayUuid returns the WayUuid field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetWayUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WayUuid
}

// GetWayUuidOk returns a tuple with the WayUuid field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) GetWayUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WayUuid, true
}

// SetWayUuid sets field value
func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) SetWayUuid(v string) {
	o.WayUuid = v
}

func (o MwServerInternalSchemasCreatePlanForTelegramPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwServerInternalSchemasCreatePlanForTelegramPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["isDone"] = o.IsDone
	toSerialize["ownerUuid"] = o.OwnerUuid
	toSerialize["time"] = o.Time
	toSerialize["wayUuid"] = o.WayUuid
	return toSerialize, nil
}

func (o *MwServerInternalSchemasCreatePlanForTelegramPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"isDone",
		"ownerUuid",
		"time",
		"wayUuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwServerInternalSchemasCreatePlanForTelegramPayload := _MwServerInternalSchemasCreatePlanForTelegramPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwServerInternalSchemasCreatePlanForTelegramPayload)

	if err != nil {
		return err
	}

	*o = MwServerInternalSchemasCreatePlanForTelegramPayload(varMwServerInternalSchemasCreatePlanForTelegramPayload)

	return err
}

type NullableMwServerInternalSchemasCreatePlanForTelegramPayload struct {
	value *MwServerInternalSchemasCreatePlanForTelegramPayload
	isSet bool
}

func (v NullableMwServerInternalSchemasCreatePlanForTelegramPayload) Get() *MwServerInternalSchemasCreatePlanForTelegramPayload {
	return v.value
}

func (v *NullableMwServerInternalSchemasCreatePlanForTelegramPayload) Set(val *MwServerInternalSchemasCreatePlanForTelegramPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwServerInternalSchemasCreatePlanForTelegramPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwServerInternalSchemasCreatePlanForTelegramPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwServerInternalSchemasCreatePlanForTelegramPayload(val *MwServerInternalSchemasCreatePlanForTelegramPayload) *NullableMwServerInternalSchemasCreatePlanForTelegramPayload {
	return &NullableMwServerInternalSchemasCreatePlanForTelegramPayload{value: val, isSet: true}
}

func (v NullableMwServerInternalSchemasCreatePlanForTelegramPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwServerInternalSchemasCreatePlanForTelegramPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


