services:
  postgres-general:
    build:
      context: .
      dockerfile: ./postgres/postgres-general.Dockerfile
    container_name: postgres-general
    ports:
      - "5432:5432"
    volumes:
      - postgres-general:/var/lib/postgresql/data
    env_file:
      - ./mw-server/.env
    networks:
      - app-network

  mw-server:
    image: viktarveratsennikau/masters-way-mw-server:latest
    build:
      context: .
      dockerfile: ./mw-server/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres-general
    networks:
      - app-network

  mw-chat-websocket:
    image: viktarveratsennikau/masters-way-mw-chat-websocket:latest
    build:
      context: .
      dockerfile: ./mw-chat-websocket/Dockerfile
    ports:
      - "7994:7994"
    depends_on:
      - mw-server
    networks:
      - app-network

  mw-test-websocket:
    image: viktarveratsennikau/masters-way-mw-test-websocket:latest
    build:
      context: .
      dockerfile: ./mw-test-websocket/Dockerfile
    ports:
      - "7991:7991"
    depends_on:
      - mw-server
    networks:
      - app-network

  mw-notification-websocket:
    image: viktarveratsennikau/masters-way-mw-notification-websocket:latest
    build:
      context: .
      dockerfile: ./mw-notification-websocket/Dockerfile
    ports:
      - "7996:7996"
    depends_on:
      - mw-server
    networks:
      - app-network

  mw-telegram-bot:
    image: viktarveratsennikau/masters-way-mw-telegram-bot:latest
    build:
      context: .
      dockerfile: ./mw-telegram-bot/Dockerfile
    container_name: masters-way-mw-telegram-bot-1
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/mastersway.duckdns.org/privkey.pem:/etc/nginx/server.key:ro
      - /etc/letsencrypt/live/mastersway.duckdns.org/fullchain.pem:/etc/nginx/server.crt:ro
    depends_on:
      - mw-server
      - mw-chat-websocket
      - mw-notification-websocket
      - mw-telegram-bot
      - mw-test-websocket
    networks:
      - app-network

volumes:
  postgres-general:
  # Старые volume (удалить после миграции)
  postgres-mail:
  postgres-notification:
  postgres-storage:
  postgres-survey:
  postgres-training:
  postgres-chat:

networks:
  app-network:
    driver: bridge