services:
  postgres-general:
    build:
      context: .
      dockerfile: ./postgres/postgres-general.Dockerfile
    container_name: postgres-general
    ports:
      - "5432:5432"
    volumes:
      - postgres-general:/var/lib/postgresql/data
    env_file:
      - ./mw-server/.env
    networks:
      - app-network

  mw-server:
    build:
      context: .
      dockerfile: ./mw-server/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres-general
    networks:
      - app-network

  mw-chat-websocket:
    build:
      context: .
      dockerfile: ./mw-chat-websocket/Dockerfile
    ports:
      - "7994:7994"
    depends_on:
      - mw-server
    networks:
      - app-network

  mw-test-websocket:
    build:
      context: .
      dockerfile: ./mw-test-websocket/Dockerfile
    ports:
      - "7991:7991"
    networks:
      - app-network

  mw-webapp:
    build:
      context: .
      dockerfile: ./mw-webapp/Dockerfile
    ports:
      - "5172:5174"
    networks:
      - app-network

  mw-notification-websocket:
    build:
      context: .
      dockerfile: ./mw-notification-websocket/Dockerfile
    ports:
      - "7996:7996"
    depends_on:
      - mw-server
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    ports:
      - "5173:80"
    volumes:
      - ./gateway/local.docker.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mw-server
      - mw-webapp
      - mw-chat-websocket
      - mw-notification-websocket
      - mw-test-websocket
    networks:
      - app-network

volumes:
  postgres-general:

networks:
  app-network:
    driver: bridge