version: "3.9"
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./mw-server/.env
    networks:
      - app-network

  mw-server:
    build:
      context: ./mw-server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

  mw-webapp:
    build:
      context: "./mw-webapp"
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./gateway/localQA.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mw-server
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
