packages:
  - 'mw-webapp'
  - 'mw-server'
  - 'mw-general-bff'
  - 'mw-mobile'
  - 'mw-chat'
  - 'mw-chat-bff'
  - 'mw-chat-websocket'
  - 'mw-storage'
  - 'mw-mail'
  - 'mw-survey'
  - 'mw-notification'
  - 'mw-notification-bff'
  - 'mw-notification-websocket'
  - 'mw-training'
  - 'mw-training-bff'
  - 'mw-test-websocket'
