# packages:
#   - 'mw-webapp'
#   - 'mw-server'
#   - 'mw-mobile'
#   - 'mw-chat'
#   - 'mw-chat-bff'

packages:
  - 'mw-webapp/**'
  - 'mw-server/**'
  - 'mw-mobile/**'
  - 'mw-chat/**'
  - 'mw-chat-bff/**'
