import {wayDTOToWayPreviewConverter} from "src/dataAccessLogic/DTOToPreviewConverter/wayDTOToWayPreviewConverter";
import {GoalPreviewDAL} from "src/dataAccessLogic/GoalPreviewDAL";
import {wayPreviewToWayDTOConverter} from "src/dataAccessLogic/PreviewToDTOConverter/WayPreviewToWayDTOConverter";
import {UserPreviewDAL} from "src/dataAccessLogic/UserPreviewDAL";
import {UserPreview} from "src/model/businessModelPreview/UserPreview";
import {WayPreview} from "src/model/businessModelPreview/WayPreview";
import {WayDTOWithoutUuid, WayService} from "src/service/WayService";
import {DateUtils} from "src/utils/DateUtils";

/**
 * Provides methods to interact with the WayPreview model
 */
export class WayPreviewDAL {

  /**
   * Get all WayPreview
   */
  public static async getWaysPreview(): Promise<WayPreview[]> {
    const waysDTO = await WayService.getWaysDTO();
    const waysUuids = waysDTO.map((item) => item.uuid);

    const waysPreview = await Promise.all(waysUuids.map(WayPreviewDAL.getWayPreview));
    const waysPreviewReverse = waysPreview.reverse();

    return waysPreviewReverse;
  }

  /**
   * Get WayPreview
   */
  public static async getWayPreview(uuid: string): Promise<WayPreview> {
    const wayDTO = await WayService.getWayDTO(uuid);

    const owner = await UserPreviewDAL.getUserPreview(wayDTO.ownerUuid);

    const currentMentors = await Promise.all(wayDTO.currentMentorUuids.map(UserPreviewDAL.getUserPreview));

    const goal = await GoalPreviewDAL.getGoalPreview(wayDTO.goalUuid);

    const wayPreviewProps = {
      owner,
      currentMentors,
      goal,
    };

    const wayPreview = wayDTOToWayPreviewConverter(wayDTO, wayPreviewProps);

    return wayPreview;
  }

  /**
   * Create WayPreview with empty fields and autogenerated uuid
   */
  public static async createWayPreview(userUuid: string): Promise<WayPreview> {
    const user = await UserPreviewDAL.getUserPreview(userUuid);
    const newGoal = await GoalPreviewDAL.createGoalPreview();

    const DEFAULT_WAY: WayDTOWithoutUuid = {
      name: `${DateUtils.getShortISODateValue(new Date)} Way of ${user.name}`,
      dayReportUuids: [],
      ownerUuid: `${userUuid}`,
      monthReportUuids: [],
      goalUuid: `${newGoal.uuid}`,
      currentMentorUuids: [],
      isCompleted: false,
    };
    const wayDTO = await WayService.createWayDTO(DEFAULT_WAY);

    const updatedUser = new UserPreview({
      uuid: user.uuid,
      name: user.name,
      email: user.email,
      description: user.description,
      ownWays: [...user.ownWays, wayDTO.uuid],
      favoriteWays: user.favoriteWays,
      mentoringWays: user.mentoringWays,
    });

    await UserPreviewDAL.updateUserPreview(updatedUser);

    const way = WayPreviewDAL.getWayPreview(wayDTO.uuid);

    return way;
  }

  /**
   * Get User ways preview based of provided type
   */
  public static async getUserWaysPreview(uuid: string, type: "Own" | "Mentoring" | "Favorite"): Promise<WayPreview[]> {

    let waysDTO;

    switch (type) {
      case "Own":
        waysDTO = await WayService.getOwnWaysDTO(uuid);
        break;
      case "Mentoring":
        waysDTO = await WayService.getMentoringWaysDTO(uuid);
        break;
      case "Favorite":
        waysDTO = await WayService.getFavoriteWaysDTO(uuid);
        break;
    }

    const waysUuids = waysDTO.map((item) => item.uuid);

    const waysPreview = await Promise.all(waysUuids.map(WayPreviewDAL.getWayPreview));

    return waysPreview;
  }

  /**
   * Update Way
   */
  public static async updateWayPreview(wayPreview: WayPreview) {
    const ownerUuid = wayPreview.owner.uuid;
    const goalUuid = wayPreview.goal.uuid;
    const currentMentorsUuids = wayPreview.currentMentors.map((item) => item.uuid);

    const wayDTOProps = {
      ownerUuid,
      goalUuid,
      currentMentorsUuids,
    };

    const wayDTO = wayPreviewToWayDTOConverter(wayPreview, wayDTOProps);
    await WayService.updateWayDTO(wayDTO, wayDTO.uuid);
  }

}