/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwServerInternalSchemasDefaultWayCollections type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwServerInternalSchemasDefaultWayCollections{}

// MwServerInternalSchemasDefaultWayCollections struct for MwServerInternalSchemasDefaultWayCollections
type MwServerInternalSchemasDefaultWayCollections struct {
	Favorite MwServerInternalSchemasWayCollectionPopulatedResponse `json:"favorite"`
	Mentoring MwServerInternalSchemasWayCollectionPopulatedResponse `json:"mentoring"`
	Own MwServerInternalSchemasWayCollectionPopulatedResponse `json:"own"`
}

type _MwServerInternalSchemasDefaultWayCollections MwServerInternalSchemasDefaultWayCollections

// NewMwServerInternalSchemasDefaultWayCollections instantiates a new MwServerInternalSchemasDefaultWayCollections object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwServerInternalSchemasDefaultWayCollections(favorite MwServerInternalSchemasWayCollectionPopulatedResponse, mentoring MwServerInternalSchemasWayCollectionPopulatedResponse, own MwServerInternalSchemasWayCollectionPopulatedResponse) *MwServerInternalSchemasDefaultWayCollections {
	this := MwServerInternalSchemasDefaultWayCollections{}
	this.Favorite = favorite
	this.Mentoring = mentoring
	this.Own = own
	return &this
}

// NewMwServerInternalSchemasDefaultWayCollectionsWithDefaults instantiates a new MwServerInternalSchemasDefaultWayCollections object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwServerInternalSchemasDefaultWayCollectionsWithDefaults() *MwServerInternalSchemasDefaultWayCollections {
	this := MwServerInternalSchemasDefaultWayCollections{}
	return &this
}

// GetFavorite returns the Favorite field value
func (o *MwServerInternalSchemasDefaultWayCollections) GetFavorite() MwServerInternalSchemasWayCollectionPopulatedResponse {
	if o == nil {
		var ret MwServerInternalSchemasWayCollectionPopulatedResponse
		return ret
	}

	return o.Favorite
}

// GetFavoriteOk returns a tuple with the Favorite field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasDefaultWayCollections) GetFavoriteOk() (*MwServerInternalSchemasWayCollectionPopulatedResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Favorite, true
}

// SetFavorite sets field value
func (o *MwServerInternalSchemasDefaultWayCollections) SetFavorite(v MwServerInternalSchemasWayCollectionPopulatedResponse) {
	o.Favorite = v
}

// GetMentoring returns the Mentoring field value
func (o *MwServerInternalSchemasDefaultWayCollections) GetMentoring() MwServerInternalSchemasWayCollectionPopulatedResponse {
	if o == nil {
		var ret MwServerInternalSchemasWayCollectionPopulatedResponse
		return ret
	}

	return o.Mentoring
}

// GetMentoringOk returns a tuple with the Mentoring field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasDefaultWayCollections) GetMentoringOk() (*MwServerInternalSchemasWayCollectionPopulatedResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mentoring, true
}

// SetMentoring sets field value
func (o *MwServerInternalSchemasDefaultWayCollections) SetMentoring(v MwServerInternalSchemasWayCollectionPopulatedResponse) {
	o.Mentoring = v
}

// GetOwn returns the Own field value
func (o *MwServerInternalSchemasDefaultWayCollections) GetOwn() MwServerInternalSchemasWayCollectionPopulatedResponse {
	if o == nil {
		var ret MwServerInternalSchemasWayCollectionPopulatedResponse
		return ret
	}

	return o.Own
}

// GetOwnOk returns a tuple with the Own field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasDefaultWayCollections) GetOwnOk() (*MwServerInternalSchemasWayCollectionPopulatedResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Own, true
}

// SetOwn sets field value
func (o *MwServerInternalSchemasDefaultWayCollections) SetOwn(v MwServerInternalSchemasWayCollectionPopulatedResponse) {
	o.Own = v
}

func (o MwServerInternalSchemasDefaultWayCollections) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwServerInternalSchemasDefaultWayCollections) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["favorite"] = o.Favorite
	toSerialize["mentoring"] = o.Mentoring
	toSerialize["own"] = o.Own
	return toSerialize, nil
}

func (o *MwServerInternalSchemasDefaultWayCollections) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"favorite",
		"mentoring",
		"own",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwServerInternalSchemasDefaultWayCollections := _MwServerInternalSchemasDefaultWayCollections{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwServerInternalSchemasDefaultWayCollections)

	if err != nil {
		return err
	}

	*o = MwServerInternalSchemasDefaultWayCollections(varMwServerInternalSchemasDefaultWayCollections)

	return err
}

type NullableMwServerInternalSchemasDefaultWayCollections struct {
	value *MwServerInternalSchemasDefaultWayCollections
	isSet bool
}

func (v NullableMwServerInternalSchemasDefaultWayCollections) Get() *MwServerInternalSchemasDefaultWayCollections {
	return v.value
}

func (v *NullableMwServerInternalSchemasDefaultWayCollections) Set(val *MwServerInternalSchemasDefaultWayCollections) {
	v.value = val
	v.isSet = true
}

func (v NullableMwServerInternalSchemasDefaultWayCollections) IsSet() bool {
	return v.isSet
}

func (v *NullableMwServerInternalSchemasDefaultWayCollections) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwServerInternalSchemasDefaultWayCollections(val *MwServerInternalSchemasDefaultWayCollections) *NullableMwServerInternalSchemasDefaultWayCollections {
	return &NullableMwServerInternalSchemasDefaultWayCollections{value: val, isSet: true}
}

func (v NullableMwServerInternalSchemasDefaultWayCollections) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwServerInternalSchemasDefaultWayCollections) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


