ALTER TABLE users
    ALTER COLUMN "name" TYPE VARCHAR,
    ALTER COLUMN "email" TYPE VARCHAR,
    ALTER COLUMN "description" TYPE VARCHAR,
    ALTER COLUMN "image_url" TYPE VARCHAR,
    ADD COLUMN "firebase_id" VARCHAR NOT NULL;

ALTER TABLE user_tags
    ALTER COLUMN "name" TYPE VARCHAR;

ALTER TABLE way_collections
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN type TYPE VARCHAR;

ALTER TABLE ways
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN goal_description TYPE VARCHAR;

ALTER TABLE metrics
    ALTER COLUMN description TYPE VARCHAR,
    ALTER COLUMN metric_estimation TYPE VARCHAR;

ALTER TABLE job_tags
    ALTER COLUMN name TYPE VARCHAR,
    ALTER COLUMN description TYPE VARCHAR,
    ALTER COLUMN color TYPE VARCHAR;

ALTER TABLE plans
    ALTER COLUMN description TYPE VARCHAR,
    ALTER COLUMN time TYPE VARCHAR;

ALTER TABLE job_dones
    ALTER COLUMN description TYPE VARCHAR,
    ALTER COLUMN time TYPE VARCHAR;

ALTER TABLE problems
    ALTER COLUMN description TYPE VARCHAR;

ALTER TABLE comments
    ALTER COLUMN description TYPE VARCHAR;
