// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Notification_CreateNotification_FullMethodName  = "/notification.Notification/CreateNotification"
	Notification_GetNotificationList_FullMethodName = "/notification.Notification/GetNotificationList"
	Notification_UpdateNotification_FullMethodName  = "/notification.Notification/UpdateNotification"
)

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationClient interface {
	CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
	GetNotificationList(ctx context.Context, in *GetNotificationListRequest, opts ...grpc.CallOption) (*GetNotificationListResponse, error)
	UpdateNotification(ctx context.Context, in *UpdateNotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
}

type notificationClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationClient(cc grpc.ClientConnInterface) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, Notification_CreateNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) GetNotificationList(ctx context.Context, in *GetNotificationListRequest, opts ...grpc.CallOption) (*GetNotificationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotificationListResponse)
	err := c.cc.Invoke(ctx, Notification_GetNotificationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) UpdateNotification(ctx context.Context, in *UpdateNotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, Notification_UpdateNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
// All implementations must embed UnimplementedNotificationServer
// for forward compatibility.
type NotificationServer interface {
	CreateNotification(context.Context, *CreateNotificationRequest) (*NotificationResponse, error)
	GetNotificationList(context.Context, *GetNotificationListRequest) (*GetNotificationListResponse, error)
	UpdateNotification(context.Context, *UpdateNotificationRequest) (*NotificationResponse, error)
	mustEmbedUnimplementedNotificationServer()
}

// UnimplementedNotificationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServer struct{}

func (UnimplementedNotificationServer) CreateNotification(context.Context, *CreateNotificationRequest) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotification not implemented")
}
func (UnimplementedNotificationServer) GetNotificationList(context.Context, *GetNotificationListRequest) (*GetNotificationListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotificationList not implemented")
}
func (UnimplementedNotificationServer) UpdateNotification(context.Context, *UpdateNotificationRequest) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotification not implemented")
}
func (UnimplementedNotificationServer) mustEmbedUnimplementedNotificationServer() {}
func (UnimplementedNotificationServer) testEmbeddedByValue()                      {}

// UnsafeNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServer will
// result in compilation errors.
type UnsafeNotificationServer interface {
	mustEmbedUnimplementedNotificationServer()
}

func RegisterNotificationServer(s grpc.ServiceRegistrar, srv NotificationServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Notification_ServiceDesc, srv)
}

func _Notification_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notification_CreateNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).CreateNotification(ctx, req.(*CreateNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_GetNotificationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).GetNotificationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notification_GetNotificationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).GetNotificationList(ctx, req.(*GetNotificationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_UpdateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).UpdateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notification_UpdateNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).UpdateNotification(ctx, req.(*UpdateNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notification_ServiceDesc is the grpc.ServiceDesc for Notification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotification",
			Handler:    _Notification_CreateNotification_Handler,
		},
		{
			MethodName: "GetNotificationList",
			Handler:    _Notification_GetNotificationList_Handler,
		},
		{
			MethodName: "UpdateNotification",
			Handler:    _Notification_UpdateNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}

const (
	EnabledNotification_CreateEnabledNotifications_FullMethodName = "/notification.EnabledNotification/CreateEnabledNotifications"
	EnabledNotification_GetEnabledNotificationList_FullMethodName = "/notification.EnabledNotification/GetEnabledNotificationList"
	EnabledNotification_UpdateEnabledNotification_FullMethodName  = "/notification.EnabledNotification/UpdateEnabledNotification"
)

// EnabledNotificationClient is the client API for EnabledNotification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnabledNotificationClient interface {
	CreateEnabledNotifications(ctx context.Context, in *CreateEnabledNotificationsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetEnabledNotificationList(ctx context.Context, in *GetEnabledNotificationListRequest, opts ...grpc.CallOption) (*GetEnabledNotificationListResponse, error)
	UpdateEnabledNotification(ctx context.Context, in *UpdateEnabledNotificationRequest, opts ...grpc.CallOption) (*EnabledNotificationResponse, error)
}

type enabledNotificationClient struct {
	cc grpc.ClientConnInterface
}

func NewEnabledNotificationClient(cc grpc.ClientConnInterface) EnabledNotificationClient {
	return &enabledNotificationClient{cc}
}

func (c *enabledNotificationClient) CreateEnabledNotifications(ctx context.Context, in *CreateEnabledNotificationsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EnabledNotification_CreateEnabledNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enabledNotificationClient) GetEnabledNotificationList(ctx context.Context, in *GetEnabledNotificationListRequest, opts ...grpc.CallOption) (*GetEnabledNotificationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnabledNotificationListResponse)
	err := c.cc.Invoke(ctx, EnabledNotification_GetEnabledNotificationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enabledNotificationClient) UpdateEnabledNotification(ctx context.Context, in *UpdateEnabledNotificationRequest, opts ...grpc.CallOption) (*EnabledNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnabledNotificationResponse)
	err := c.cc.Invoke(ctx, EnabledNotification_UpdateEnabledNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnabledNotificationServer is the server API for EnabledNotification service.
// All implementations must embed UnimplementedEnabledNotificationServer
// for forward compatibility.
type EnabledNotificationServer interface {
	CreateEnabledNotifications(context.Context, *CreateEnabledNotificationsRequest) (*emptypb.Empty, error)
	GetEnabledNotificationList(context.Context, *GetEnabledNotificationListRequest) (*GetEnabledNotificationListResponse, error)
	UpdateEnabledNotification(context.Context, *UpdateEnabledNotificationRequest) (*EnabledNotificationResponse, error)
	mustEmbedUnimplementedEnabledNotificationServer()
}

// UnimplementedEnabledNotificationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnabledNotificationServer struct{}

func (UnimplementedEnabledNotificationServer) CreateEnabledNotifications(context.Context, *CreateEnabledNotificationsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnabledNotifications not implemented")
}
func (UnimplementedEnabledNotificationServer) GetEnabledNotificationList(context.Context, *GetEnabledNotificationListRequest) (*GetEnabledNotificationListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnabledNotificationList not implemented")
}
func (UnimplementedEnabledNotificationServer) UpdateEnabledNotification(context.Context, *UpdateEnabledNotificationRequest) (*EnabledNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnabledNotification not implemented")
}
func (UnimplementedEnabledNotificationServer) mustEmbedUnimplementedEnabledNotificationServer() {}
func (UnimplementedEnabledNotificationServer) testEmbeddedByValue()                             {}

// UnsafeEnabledNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnabledNotificationServer will
// result in compilation errors.
type UnsafeEnabledNotificationServer interface {
	mustEmbedUnimplementedEnabledNotificationServer()
}

func RegisterEnabledNotificationServer(s grpc.ServiceRegistrar, srv EnabledNotificationServer) {
	// If the following call pancis, it indicates UnimplementedEnabledNotificationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnabledNotification_ServiceDesc, srv)
}

func _EnabledNotification_CreateEnabledNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnabledNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnabledNotificationServer).CreateEnabledNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnabledNotification_CreateEnabledNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnabledNotificationServer).CreateEnabledNotifications(ctx, req.(*CreateEnabledNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnabledNotification_GetEnabledNotificationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnabledNotificationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnabledNotificationServer).GetEnabledNotificationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnabledNotification_GetEnabledNotificationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnabledNotificationServer).GetEnabledNotificationList(ctx, req.(*GetEnabledNotificationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnabledNotification_UpdateEnabledNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnabledNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnabledNotificationServer).UpdateEnabledNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnabledNotification_UpdateEnabledNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnabledNotificationServer).UpdateEnabledNotification(ctx, req.(*UpdateEnabledNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnabledNotification_ServiceDesc is the grpc.ServiceDesc for EnabledNotification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnabledNotification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.EnabledNotification",
	HandlerType: (*EnabledNotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEnabledNotifications",
			Handler:    _EnabledNotification_CreateEnabledNotifications_Handler,
		},
		{
			MethodName: "GetEnabledNotificationList",
			Handler:    _EnabledNotification_GetEnabledNotificationList_Handler,
		},
		{
			MethodName: "UpdateEnabledNotification",
			Handler:    _EnabledNotification_UpdateEnabledNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}

const (
	Dev_ResetDB_FullMethodName = "/notification.Dev/ResetDB"
)

// DevClient is the client API for Dev service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevClient interface {
	ResetDB(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type devClient struct {
	cc grpc.ClientConnInterface
}

func NewDevClient(cc grpc.ClientConnInterface) DevClient {
	return &devClient{cc}
}

func (c *devClient) ResetDB(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Dev_ResetDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevServer is the server API for Dev service.
// All implementations must embed UnimplementedDevServer
// for forward compatibility.
type DevServer interface {
	ResetDB(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedDevServer()
}

// UnimplementedDevServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevServer struct{}

func (UnimplementedDevServer) ResetDB(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetDB not implemented")
}
func (UnimplementedDevServer) mustEmbedUnimplementedDevServer() {}
func (UnimplementedDevServer) testEmbeddedByValue()             {}

// UnsafeDevServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevServer will
// result in compilation errors.
type UnsafeDevServer interface {
	mustEmbedUnimplementedDevServer()
}

func RegisterDevServer(s grpc.ServiceRegistrar, srv DevServer) {
	// If the following call pancis, it indicates UnimplementedDevServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dev_ServiceDesc, srv)
}

func _Dev_ResetDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServer).ResetDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dev_ResetDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServer).ResetDB(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Dev_ServiceDesc is the grpc.ServiceDesc for Dev service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dev_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.Dev",
	HandlerType: (*DevServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResetDB",
			Handler:    _Dev_ResetDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
