import {SchemasUserPopulatedResponse} from "src/apiAutogenerated";
import {getWayStatus} from "src/logic/waysTable/wayStatus";
import {User, WayCollection} from "src/model/businessModel/User";
import {WayPreview} from "src/model/businessModelPreview/WayPreview";
import {Language} from "src/utils/LanguageWorker";

/**
 * Convert {@link UserDTO} to {@link User}
 */
export const UserDTOToUserConverter = (userDTO: SchemasUserPopulatedResponse): User => {
  return new User({
    ...userDTO,
    wayCollections: userDTO.wayCollections.map((wayCollectionDTO) => {
      const wayCollection: WayCollection = {
        ...wayCollectionDTO,
        createdAt: new Date(wayCollectionDTO.createdAt),
        updatedAt: new Date(wayCollectionDTO.updatedAt),
        ways: wayCollectionDTO.ways.map((way) => {
          const status = getWayStatus({
            status: way.isCompleted ? "Completed" : null,
            lastUpdate: new Date(way.updatedAt),
            language: Language.ENGLISH,
          });

          const wayPreview = new WayPreview({
            ...way,
            status,
            createdAt: new Date(way.createdAt),
            lastUpdate: new Date(way.updatedAt),
            mentors: [],
          });

          return wayPreview;
        }),
      };

      return wayCollection;
    }),
    createdAt: new Date(userDTO.createdAt),
    favoriteForUserUuids: [],
    favoriteUserUuids: [],
    imageUrl: userDTO.imageUrl ?? "",
    wayRequests: [],
  });
};
