import {MwGeneralBffInternalSchemasUserPlainResponse} from "src/apiAutogenerated/general";
import {UserPlain} from "src/model/businessModel/User";

/**
 * Convert {@link UserPlainDTO} to {@link UserPlain}
 */
export const userPlainDTOToUserPlainConverter = (userPlainDTO: MwGeneralBffInternalSchemasUserPlainResponse): UserPlain => {
  return new UserPlain({
    ...userPlainDTO,
    createdAt: new Date(userPlainDTO.createdAt),
  });
};
