import {PricePlanType} from "src/component/pricingBlock/pricePlan/PricePlan";

export const pricePlansList: PricePlanType[] = [
  {
    id: 0,
    theme: "light",
    name: "Start",
    price: 0,
    period: "free",
    capabilities: {
      ownTrainings: null,
      aiSupport: null,
      trackProgress: null,
      chat: null,
      notifications: null,
      mobileSupport: null,
      masterCoins: 50,
    },
    buttonValue: "start",
  },
  {
    id: 1,
    theme: "light",
    name: "Start AI",
    price: 10,
    period: "month",
    capabilities: {
      ownTrainings: null,
      aiSupport: null,
      trackProgress: null,
      chat: null,
      notifications: null,
      mobileSupport: null,
      masterCoins: 1500,
    },
    buttonValue: "start-ai",
  },
  {
    id: 2,
    theme: "dark",
    name: "Grow",
    price: 50,
    period: "month",
    capabilities: {
      allInStart: null,
      consultation: null,
      mentorSupport: null,
      secondMeeting: null,
      masterCoins: 2000,
    },
    buttonValue: "grow",
  },
  {
    id: 3,
    theme: "light",
    name: "Scale",
    price: 0,
    period: "individually",
    capabilities: {
      allInGrow: null,
      prioritySupport: null,
      featureRequest: null,
      onboarding: null,
      masterCoins: 4000,
    },
    buttonValue: "scale",
  },
];
