// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersGetLinkedUserResponse
 */
export interface ControllersGetLinkedUserResponse {
    /**
     * 
     * @type {string}
     * @memberof ControllersGetLinkedUserResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersGetLinkedUserResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersGetLinkedUserResponse
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersGetLinkedUserResponse
     */
    userUuid?: string;
}

/**
 * Check if a given object implements the ControllersGetLinkedUserResponse interface.
 */
export function instanceOfControllersGetLinkedUserResponse(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function ControllersGetLinkedUserResponseFromJSON(json: any): ControllersGetLinkedUserResponse {
    return ControllersGetLinkedUserResponseFromJSONTyped(json, false);
}

export function ControllersGetLinkedUserResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ControllersGetLinkedUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'token': !exists(json, 'token') ? undefined : json['token'],
        'userUuid': !exists(json, 'userUuid') ? undefined : json['userUuid'],
    };
}


export function ControllersGetLinkedUserResponseToJSON(value?: ControllersGetLinkedUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'name': value.name,
        'token': value.token,
        'userUuid': value.userUuid,
    };
}

