package openapi

import (
	openapiGeneral "mw-training-bff/apiAutogenerated/general"
	openapiStorage "mw-training-bff/apiAutogenerated/mw-storage"
	openapiTrainingBFF "mw-training-bff/apiAutogenerated/mw-training-bff"
	openapiTraining "mw-training-bff/apiAutogenerated/training"
	"mw-training-bff/internal/config"
	"net/http"
)

func MakeTestGeneralAPIClient(cfg *config.Config) *openapiGeneral.APIClient {
	generalAPIConfig := &openapiGeneral.Configuration{
		Host:   cfg.TestGeneralAPIHost,
		Scheme: "http",
		Servers: openapiGeneral.ServerConfigurations{
			{
				URL:         cfg.TestGeneralBaseURL,
				Description: "mw-general",
			},
		},
		HTTPClient: &http.Client{
			Transport: &AuthTransport{rt: http.DefaultTransport},
		},
	}
	return openapiGeneral.NewAPIClient(generalAPIConfig)
}

func MakeTestTrainingAPIClient(cfg *config.Config) *openapiTraining.APIClient {
	trainingAPIConfig := &openapiTraining.Configuration{
		Host:   cfg.TestTrainingAPIHost,
		Scheme: "http",
		Servers: openapiTraining.ServerConfigurations{
			{
				URL:         cfg.TestTrainingBaseURL,
				Description: "mw-training",
			},
		},
		HTTPClient: &http.Client{
			Transport: &AuthTransport{rt: http.DefaultTransport},
		},
	}
	return openapiTraining.NewAPIClient(trainingAPIConfig)
}

func MakeTestTrainingBFFAPIClient(cfg *config.Config) *openapiTrainingBFF.APIClient {
	trainingBFFAPIConfig := &openapiTrainingBFF.Configuration{
		Host:   cfg.TestTrainingBFFAPIHost,
		Scheme: "http",
		Servers: openapiTrainingBFF.ServerConfigurations{
			{
				URL:         cfg.TestTrainingBFFBaseURL,
				Description: "mw-training-bff",
			},
		},
		HTTPClient: &http.Client{
			Transport: &AuthTransport{rt: http.DefaultTransport},
		},
	}
	return openapiTrainingBFF.NewAPIClient(trainingBFFAPIConfig)
}

func MakeTestStorageAPIClient(cfg *config.Config) *openapiStorage.APIClient {
	storageAPIConfig := &openapiStorage.Configuration{
		Host:   cfg.TestStorageAPIHost,
		Scheme: "http",
		Servers: openapiStorage.ServerConfigurations{
			{
				URL:         cfg.TestStorageBaseURL,
				Description: "mw-storage",
			},
		},
		HTTPClient: &http.Client{
			Transport: &AuthTransport{rt: http.DefaultTransport},
		},
	}
	return openapiStorage.NewAPIClient(storageAPIConfig)
}
