// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemasAIGenerateTrainingDescriptionByTestResultsResponse
 */
export interface SchemasAIGenerateTrainingDescriptionByTestResultsResponse {
    /**
     * 
     * @type {string}
     * @memberof SchemasAIGenerateTrainingDescriptionByTestResultsResponse
     */
    trainingDescription: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasAIGenerateTrainingDescriptionByTestResultsResponse
     */
    trainingName: string;
}

/**
 * Check if a given object implements the SchemasAIGenerateTrainingDescriptionByTestResultsResponse interface.
 */
export function instanceOfSchemasAIGenerateTrainingDescriptionByTestResultsResponse(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "trainingDescription" in value;
    isInstance = isInstance && "trainingName" in value;

    return isInstance;
}

export function SchemasAIGenerateTrainingDescriptionByTestResultsResponseFromJSON(json: any): SchemasAIGenerateTrainingDescriptionByTestResultsResponse {
    return SchemasAIGenerateTrainingDescriptionByTestResultsResponseFromJSONTyped(json, false);
}

export function SchemasAIGenerateTrainingDescriptionByTestResultsResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasAIGenerateTrainingDescriptionByTestResultsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trainingDescription': json['trainingDescription'],
        'trainingName': json['trainingName'],
    };
}


export function SchemasAIGenerateTrainingDescriptionByTestResultsResponseToJSON(value?: SchemasAIGenerateTrainingDescriptionByTestResultsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trainingDescription': value.trainingDescription,
        'trainingName': value.trainingName,
    };
}

