// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SchemasRoomPopulatedResponse } from './SchemasRoomPopulatedResponse';
import {
    SchemasRoomPopulatedResponseFromJSON,
    SchemasRoomPopulatedResponseFromJSONTyped,
    SchemasRoomPopulatedResponseToJSON,
} from './SchemasRoomPopulatedResponse';

/**
 * 
 * @export
 * @interface SchemasFindOrCreateRoomResponse
 */
export interface SchemasFindOrCreateRoomResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SchemasFindOrCreateRoomResponse
     */
    isAlreadyCreated: boolean;
    /**
     * 
     * @type {SchemasRoomPopulatedResponse}
     * @memberof SchemasFindOrCreateRoomResponse
     */
    room: SchemasRoomPopulatedResponse;
}

/**
 * Check if a given object implements the SchemasFindOrCreateRoomResponse interface.
 */
export function instanceOfSchemasFindOrCreateRoomResponse(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "isAlreadyCreated" in value;
    isInstance = isInstance && "room" in value;

    return isInstance;
}

export function SchemasFindOrCreateRoomResponseFromJSON(json: any): SchemasFindOrCreateRoomResponse {
    return SchemasFindOrCreateRoomResponseFromJSONTyped(json, false);
}

export function SchemasFindOrCreateRoomResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasFindOrCreateRoomResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isAlreadyCreated': json['isAlreadyCreated'],
        'room': SchemasRoomPopulatedResponseFromJSON(json['room']),
    };
}


export function SchemasFindOrCreateRoomResponseToJSON(value?: SchemasFindOrCreateRoomResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isAlreadyCreated': value.isAlreadyCreated,
        'room': SchemasRoomPopulatedResponseToJSON(value.room),
    };
}

