/*
Masters way general-bff API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation{}

// MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation struct for MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation
type MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation struct {
	AverageJobTime *int32
	AverageTimePerCalendarDay *int32
	AverageTimePerWorkingDay *int32
	FinishedJobs *int32
	TotalReports *int32
	TotalTime *int32
}

// NewMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation instantiates a new MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation() *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation {
	this := MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation{}
	return &this
}

// NewMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformationWithDefaults instantiates a new MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformationWithDefaults() *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation {
	this := MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation{}
	return &this
}

// GetAverageJobTime returns the AverageJobTime field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetAverageJobTime() int32 {
	if o == nil || IsNil(o.AverageJobTime) {
		var ret int32
		return ret
	}
	return *o.AverageJobTime
}

// GetAverageJobTimeOk returns a tuple with the AverageJobTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetAverageJobTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.AverageJobTime) {
		return nil, false
	}
	return o.AverageJobTime, true
}

// HasAverageJobTime returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) HasAverageJobTime() bool {
	if o != nil && !IsNil(o.AverageJobTime) {
		return true
	}

	return false
}

// SetAverageJobTime gets a reference to the given int32 and assigns it to the AverageJobTime field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) SetAverageJobTime(v int32) {
	o.AverageJobTime = &v
}

// GetAverageTimePerCalendarDay returns the AverageTimePerCalendarDay field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetAverageTimePerCalendarDay() int32 {
	if o == nil || IsNil(o.AverageTimePerCalendarDay) {
		var ret int32
		return ret
	}
	return *o.AverageTimePerCalendarDay
}

// GetAverageTimePerCalendarDayOk returns a tuple with the AverageTimePerCalendarDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetAverageTimePerCalendarDayOk() (*int32, bool) {
	if o == nil || IsNil(o.AverageTimePerCalendarDay) {
		return nil, false
	}
	return o.AverageTimePerCalendarDay, true
}

// HasAverageTimePerCalendarDay returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) HasAverageTimePerCalendarDay() bool {
	if o != nil && !IsNil(o.AverageTimePerCalendarDay) {
		return true
	}

	return false
}

// SetAverageTimePerCalendarDay gets a reference to the given int32 and assigns it to the AverageTimePerCalendarDay field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) SetAverageTimePerCalendarDay(v int32) {
	o.AverageTimePerCalendarDay = &v
}

// GetAverageTimePerWorkingDay returns the AverageTimePerWorkingDay field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetAverageTimePerWorkingDay() int32 {
	if o == nil || IsNil(o.AverageTimePerWorkingDay) {
		var ret int32
		return ret
	}
	return *o.AverageTimePerWorkingDay
}

// GetAverageTimePerWorkingDayOk returns a tuple with the AverageTimePerWorkingDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetAverageTimePerWorkingDayOk() (*int32, bool) {
	if o == nil || IsNil(o.AverageTimePerWorkingDay) {
		return nil, false
	}
	return o.AverageTimePerWorkingDay, true
}

// HasAverageTimePerWorkingDay returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) HasAverageTimePerWorkingDay() bool {
	if o != nil && !IsNil(o.AverageTimePerWorkingDay) {
		return true
	}

	return false
}

// SetAverageTimePerWorkingDay gets a reference to the given int32 and assigns it to the AverageTimePerWorkingDay field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) SetAverageTimePerWorkingDay(v int32) {
	o.AverageTimePerWorkingDay = &v
}

// GetFinishedJobs returns the FinishedJobs field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetFinishedJobs() int32 {
	if o == nil || IsNil(o.FinishedJobs) {
		var ret int32
		return ret
	}
	return *o.FinishedJobs
}

// GetFinishedJobsOk returns a tuple with the FinishedJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetFinishedJobsOk() (*int32, bool) {
	if o == nil || IsNil(o.FinishedJobs) {
		return nil, false
	}
	return o.FinishedJobs, true
}

// HasFinishedJobs returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) HasFinishedJobs() bool {
	if o != nil && !IsNil(o.FinishedJobs) {
		return true
	}

	return false
}

// SetFinishedJobs gets a reference to the given int32 and assigns it to the FinishedJobs field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) SetFinishedJobs(v int32) {
	o.FinishedJobs = &v
}

// GetTotalReports returns the TotalReports field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetTotalReports() int32 {
	if o == nil || IsNil(o.TotalReports) {
		var ret int32
		return ret
	}
	return *o.TotalReports
}

// GetTotalReportsOk returns a tuple with the TotalReports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetTotalReportsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalReports) {
		return nil, false
	}
	return o.TotalReports, true
}

// HasTotalReports returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) HasTotalReports() bool {
	if o != nil && !IsNil(o.TotalReports) {
		return true
	}

	return false
}

// SetTotalReports gets a reference to the given int32 and assigns it to the TotalReports field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) SetTotalReports(v int32) {
	o.TotalReports = &v
}

// GetTotalTime returns the TotalTime field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetTotalTime() int32 {
	if o == nil || IsNil(o.TotalTime) {
		var ret int32
		return ret
	}
	return *o.TotalTime
}

// GetTotalTimeOk returns a tuple with the TotalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) GetTotalTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTime) {
		return nil, false
	}
	return o.TotalTime, true
}

// HasTotalTime returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) HasTotalTime() bool {
	if o != nil && !IsNil(o.TotalTime) {
		return true
	}

	return false
}

// SetTotalTime gets a reference to the given int32 and assigns it to the TotalTime field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) SetTotalTime(v int32) {
	o.TotalTime = &v
}

func (o MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AverageJobTime) {
		toSerialize["averageJobTime"] = o.AverageJobTime
	}
	if !IsNil(o.AverageTimePerCalendarDay) {
		toSerialize["averageTimePerCalendarDay"] = o.AverageTimePerCalendarDay
	}
	if !IsNil(o.AverageTimePerWorkingDay) {
		toSerialize["averageTimePerWorkingDay"] = o.AverageTimePerWorkingDay
	}
	if !IsNil(o.FinishedJobs) {
		toSerialize["finishedJobs"] = o.FinishedJobs
	}
	if !IsNil(o.TotalReports) {
		toSerialize["totalReports"] = o.TotalReports
	}
	if !IsNil(o.TotalTime) {
		toSerialize["totalTime"] = o.TotalTime
	}
	return toSerialize, nil
}

type NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation struct {
	value *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation
	isSet bool
}

func (v NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) Get() *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation {
	return v.value
}

func (v *NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) Set(val *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation(val *MwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) *NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation {
	return &NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation{value: val, isSet: true}
}

func (v NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwGeneralBffApiAutogeneratedGeneralMwServerInternalSchemasOverallInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


