/*
Masters way general-bff API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwGeneralBffInternalSchemasUserTagResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwGeneralBffInternalSchemasUserTagResponse{}

// MwGeneralBffInternalSchemasUserTagResponse struct for MwGeneralBffInternalSchemasUserTagResponse
type MwGeneralBffInternalSchemasUserTagResponse struct {
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}

type _MwGeneralBffInternalSchemasUserTagResponse MwGeneralBffInternalSchemasUserTagResponse

// NewMwGeneralBffInternalSchemasUserTagResponse instantiates a new MwGeneralBffInternalSchemasUserTagResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwGeneralBffInternalSchemasUserTagResponse(name string, uuid string) *MwGeneralBffInternalSchemasUserTagResponse {
	this := MwGeneralBffInternalSchemasUserTagResponse{}
	this.Name = name
	this.Uuid = uuid
	return &this
}

// NewMwGeneralBffInternalSchemasUserTagResponseWithDefaults instantiates a new MwGeneralBffInternalSchemasUserTagResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwGeneralBffInternalSchemasUserTagResponseWithDefaults() *MwGeneralBffInternalSchemasUserTagResponse {
	this := MwGeneralBffInternalSchemasUserTagResponse{}
	return &this
}

// GetName returns the Name field value
func (o *MwGeneralBffInternalSchemasUserTagResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserTagResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MwGeneralBffInternalSchemasUserTagResponse) SetName(v string) {
	o.Name = v
}

// GetUuid returns the Uuid field value
func (o *MwGeneralBffInternalSchemasUserTagResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserTagResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *MwGeneralBffInternalSchemasUserTagResponse) SetUuid(v string) {
	o.Uuid = v
}

func (o MwGeneralBffInternalSchemasUserTagResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwGeneralBffInternalSchemasUserTagResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *MwGeneralBffInternalSchemasUserTagResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwGeneralBffInternalSchemasUserTagResponse := _MwGeneralBffInternalSchemasUserTagResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwGeneralBffInternalSchemasUserTagResponse)

	if err != nil {
		return err
	}

	*o = MwGeneralBffInternalSchemasUserTagResponse(varMwGeneralBffInternalSchemasUserTagResponse)

	return err
}

type NullableMwGeneralBffInternalSchemasUserTagResponse struct {
	value *MwGeneralBffInternalSchemasUserTagResponse
	isSet bool
}

func (v NullableMwGeneralBffInternalSchemasUserTagResponse) Get() *MwGeneralBffInternalSchemasUserTagResponse {
	return v.value
}

func (v *NullableMwGeneralBffInternalSchemasUserTagResponse) Set(val *MwGeneralBffInternalSchemasUserTagResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMwGeneralBffInternalSchemasUserTagResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMwGeneralBffInternalSchemasUserTagResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwGeneralBffInternalSchemasUserTagResponse(val *MwGeneralBffInternalSchemasUserTagResponse) *NullableMwGeneralBffInternalSchemasUserTagResponse {
	return &NullableMwGeneralBffInternalSchemasUserTagResponse{value: val, isSet: true}
}

func (v NullableMwGeneralBffInternalSchemasUserTagResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwGeneralBffInternalSchemasUserTagResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


