/*
Masters way general-bff API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections{}

// MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections struct for MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections
type MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections struct {
	Favorite *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse
	Mentoring *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse
	Own *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse
}

// NewMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections instantiates a new MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections() *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections {
	this := MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections{}
	return &this
}

// NewMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollectionsWithDefaults instantiates a new MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollectionsWithDefaults() *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections {
	this := MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections{}
	return &this
}

// GetFavorite returns the Favorite field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) GetFavorite() MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse {
	if o == nil || IsNil(o.Favorite) {
		var ret MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse
		return ret
	}
	return *o.Favorite
}

// GetFavoriteOk returns a tuple with the Favorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) GetFavoriteOk() (*MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse, bool) {
	if o == nil || IsNil(o.Favorite) {
		return nil, false
	}
	return o.Favorite, true
}

// HasFavorite returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) HasFavorite() bool {
	if o != nil && !IsNil(o.Favorite) {
		return true
	}

	return false
}

// SetFavorite gets a reference to the given MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse and assigns it to the Favorite field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) SetFavorite(v MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse) {
	o.Favorite = &v
}

// GetMentoring returns the Mentoring field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) GetMentoring() MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse {
	if o == nil || IsNil(o.Mentoring) {
		var ret MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse
		return ret
	}
	return *o.Mentoring
}

// GetMentoringOk returns a tuple with the Mentoring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) GetMentoringOk() (*MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse, bool) {
	if o == nil || IsNil(o.Mentoring) {
		return nil, false
	}
	return o.Mentoring, true
}

// HasMentoring returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) HasMentoring() bool {
	if o != nil && !IsNil(o.Mentoring) {
		return true
	}

	return false
}

// SetMentoring gets a reference to the given MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse and assigns it to the Mentoring field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) SetMentoring(v MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse) {
	o.Mentoring = &v
}

// GetOwn returns the Own field value if set, zero value otherwise.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) GetOwn() MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse {
	if o == nil || IsNil(o.Own) {
		var ret MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse
		return ret
	}
	return *o.Own
}

// GetOwnOk returns a tuple with the Own field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) GetOwnOk() (*MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse, bool) {
	if o == nil || IsNil(o.Own) {
		return nil, false
	}
	return o.Own, true
}

// HasOwn returns a boolean if a field has been set.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) HasOwn() bool {
	if o != nil && !IsNil(o.Own) {
		return true
	}

	return false
}

// SetOwn gets a reference to the given MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse and assigns it to the Own field.
func (o *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) SetOwn(v MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasWayCollectionPopulatedResponse) {
	o.Own = &v
}

func (o MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Favorite) {
		toSerialize["favorite"] = o.Favorite
	}
	if !IsNil(o.Mentoring) {
		toSerialize["mentoring"] = o.Mentoring
	}
	if !IsNil(o.Own) {
		toSerialize["own"] = o.Own
	}
	return toSerialize, nil
}

type NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections struct {
	value *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections
	isSet bool
}

func (v NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) Get() *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections {
	return v.value
}

func (v *NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) Set(val *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) {
	v.value = val
	v.isSet = true
}

func (v NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) IsSet() bool {
	return v.isSet
}

func (v *NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections(val *MwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) *NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections {
	return &NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections{value: val, isSet: true}
}

func (v NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwGeneralBffApiAutogeneratedGeneralMwserverInternalSchemasDefaultWayCollections) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


