// @ts-nocheck
/* eslint-disable */
/**
 * Masters way API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemasUserPlainResponse
 */
export interface SchemasUserPlainResponse {
    /**
     * 
     * @type {string}
     * @memberof SchemasUserPlainResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasUserPlainResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasUserPlainResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasUserPlainResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SchemasUserPlainResponse
     */
    isMentor?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SchemasUserPlainResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasUserPlainResponse
     */
    uuid?: string;
}

/**
 * Check if a given object implements the SchemasUserPlainResponse interface.
 */
export function instanceOfSchemasUserPlainResponse(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function SchemasUserPlainResponseFromJSON(json: any): SchemasUserPlainResponse {
    return SchemasUserPlainResponseFromJSONTyped(json, false);
}

export function SchemasUserPlainResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasUserPlainResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'isMentor': !exists(json, 'isMentor') ? undefined : json['isMentor'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}


export function SchemasUserPlainResponseToJSON(value?: SchemasUserPlainResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'description': value.description,
        'email': value.email,
        'imageUrl': value.imageUrl,
        'isMentor': value.isMentor,
        'name': value.name,
        'uuid': value.uuid,
    };
}

