// @ts-nocheck
/* eslint-disable */
/**
 * Masters way API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemasJobTagResponse
 */
export interface SchemasJobTagResponse {
    /**
     * 
     * @type {string}
     * @memberof SchemasJobTagResponse
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasJobTagResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasJobTagResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasJobTagResponse
     */
    uuid?: string;
}

/**
 * Check if a given object implements the SchemasJobTagResponse interface.
 */
export function instanceOfSchemasJobTagResponse(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function SchemasJobTagResponseFromJSON(json: any): SchemasJobTagResponse {
    return SchemasJobTagResponseFromJSONTyped(json, false);
}

export function SchemasJobTagResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasJobTagResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': !exists(json, 'color') ? undefined : json['color'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}


export function SchemasJobTagResponseToJSON(value?: SchemasJobTagResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': value.color,
        'description': value.description,
        'name': value.name,
        'uuid': value.uuid,
    };
}

