// @ts-nocheck
/* eslint-disable */
/**
 * Masters way API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemasCreateMetricPayload
 */
export interface SchemasCreateMetricPayload {
    /**
     * 
     * @type {string}
     * @memberof SchemasCreateMetricPayload
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof SchemasCreateMetricPayload
     */
    doneDate?: number;
    /**
     * 
     * @type {number}
     * @memberof SchemasCreateMetricPayload
     */
    estimationTime?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SchemasCreateMetricPayload
     */
    isDone?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SchemasCreateMetricPayload
     */
    wayUuid?: string;
}

/**
 * Check if a given object implements the SchemasCreateMetricPayload interface.
 */
export function instanceOfSchemasCreateMetricPayload(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function SchemasCreateMetricPayloadFromJSON(json: any): SchemasCreateMetricPayload {
    return SchemasCreateMetricPayloadFromJSONTyped(json, false);
}

export function SchemasCreateMetricPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasCreateMetricPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'doneDate': !exists(json, 'doneDate') ? undefined : json['doneDate'],
        'estimationTime': !exists(json, 'estimationTime') ? undefined : json['estimationTime'],
        'isDone': !exists(json, 'isDone') ? undefined : json['isDone'],
        'wayUuid': !exists(json, 'wayUuid') ? undefined : json['wayUuid'],
    };
}


export function SchemasCreateMetricPayloadToJSON(value?: SchemasCreateMetricPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'doneDate': value.doneDate,
        'estimationTime': value.estimationTime,
        'isDone': value.isDone,
        'wayUuid': value.wayUuid,
    };
}

