// @ts-nocheck
/* eslint-disable */
/**
 * Masters way API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SchemasUserPlainResponse } from './SchemasUserPlainResponse';
import {
    SchemasUserPlainResponseFromJSON,
    SchemasUserPlainResponseFromJSONTyped,
    SchemasUserPlainResponseToJSON,
} from './SchemasUserPlainResponse';

/**
 * 
 * @export
 * @interface SchemasCommentPlainResponse
 */
export interface SchemasCommentPlainResponse {
    /**
     * 
     * @type {string}
     * @memberof SchemasCommentPlainResponse
     */
    description?: string;
    /**
     * 
     * @type {SchemasUserPlainResponse}
     * @memberof SchemasCommentPlainResponse
     */
    owner?: SchemasUserPlainResponse;
}

/**
 * Check if a given object implements the SchemasCommentPlainResponse interface.
 */
export function instanceOfSchemasCommentPlainResponse(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function SchemasCommentPlainResponseFromJSON(json: any): SchemasCommentPlainResponse {
    return SchemasCommentPlainResponseFromJSONTyped(json, false);
}

export function SchemasCommentPlainResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasCommentPlainResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'owner': !exists(json, 'owner') ? undefined : SchemasUserPlainResponseFromJSON(json['owner']),
    };
}


export function SchemasCommentPlainResponseToJSON(value?: SchemasCommentPlainResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'owner': SchemasUserPlainResponseToJSON(value.owner),
    };
}

