/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwServerInternalSchemasCreatePlanJobTagPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwServerInternalSchemasCreatePlanJobTagPayload{}

// MwServerInternalSchemasCreatePlanJobTagPayload struct for MwServerInternalSchemasCreatePlanJobTagPayload
type MwServerInternalSchemasCreatePlanJobTagPayload struct {
	JobTagUuid string `json:"jobTagUuid"`
	PlanUuid string `json:"planUuid"`
}

type _MwServerInternalSchemasCreatePlanJobTagPayload MwServerInternalSchemasCreatePlanJobTagPayload

// NewMwServerInternalSchemasCreatePlanJobTagPayload instantiates a new MwServerInternalSchemasCreatePlanJobTagPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwServerInternalSchemasCreatePlanJobTagPayload(jobTagUuid string, planUuid string) *MwServerInternalSchemasCreatePlanJobTagPayload {
	this := MwServerInternalSchemasCreatePlanJobTagPayload{}
	this.JobTagUuid = jobTagUuid
	this.PlanUuid = planUuid
	return &this
}

// NewMwServerInternalSchemasCreatePlanJobTagPayloadWithDefaults instantiates a new MwServerInternalSchemasCreatePlanJobTagPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwServerInternalSchemasCreatePlanJobTagPayloadWithDefaults() *MwServerInternalSchemasCreatePlanJobTagPayload {
	this := MwServerInternalSchemasCreatePlanJobTagPayload{}
	return &this
}

// GetJobTagUuid returns the JobTagUuid field value
func (o *MwServerInternalSchemasCreatePlanJobTagPayload) GetJobTagUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobTagUuid
}

// GetJobTagUuidOk returns a tuple with the JobTagUuid field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasCreatePlanJobTagPayload) GetJobTagUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobTagUuid, true
}

// SetJobTagUuid sets field value
func (o *MwServerInternalSchemasCreatePlanJobTagPayload) SetJobTagUuid(v string) {
	o.JobTagUuid = v
}

// GetPlanUuid returns the PlanUuid field value
func (o *MwServerInternalSchemasCreatePlanJobTagPayload) GetPlanUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanUuid
}

// GetPlanUuidOk returns a tuple with the PlanUuid field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasCreatePlanJobTagPayload) GetPlanUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanUuid, true
}

// SetPlanUuid sets field value
func (o *MwServerInternalSchemasCreatePlanJobTagPayload) SetPlanUuid(v string) {
	o.PlanUuid = v
}

func (o MwServerInternalSchemasCreatePlanJobTagPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwServerInternalSchemasCreatePlanJobTagPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobTagUuid"] = o.JobTagUuid
	toSerialize["planUuid"] = o.PlanUuid
	return toSerialize, nil
}

func (o *MwServerInternalSchemasCreatePlanJobTagPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobTagUuid",
		"planUuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwServerInternalSchemasCreatePlanJobTagPayload := _MwServerInternalSchemasCreatePlanJobTagPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwServerInternalSchemasCreatePlanJobTagPayload)

	if err != nil {
		return err
	}

	*o = MwServerInternalSchemasCreatePlanJobTagPayload(varMwServerInternalSchemasCreatePlanJobTagPayload)

	return err
}

type NullableMwServerInternalSchemasCreatePlanJobTagPayload struct {
	value *MwServerInternalSchemasCreatePlanJobTagPayload
	isSet bool
}

func (v NullableMwServerInternalSchemasCreatePlanJobTagPayload) Get() *MwServerInternalSchemasCreatePlanJobTagPayload {
	return v.value
}

func (v *NullableMwServerInternalSchemasCreatePlanJobTagPayload) Set(val *MwServerInternalSchemasCreatePlanJobTagPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwServerInternalSchemasCreatePlanJobTagPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwServerInternalSchemasCreatePlanJobTagPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwServerInternalSchemasCreatePlanJobTagPayload(val *MwServerInternalSchemasCreatePlanJobTagPayload) *NullableMwServerInternalSchemasCreatePlanJobTagPayload {
	return &NullableMwServerInternalSchemasCreatePlanJobTagPayload{value: val, isSet: true}
}

func (v NullableMwServerInternalSchemasCreatePlanJobTagPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwServerInternalSchemasCreatePlanJobTagPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


