package controllers

import (
	"context"

	db "mw-training/internal/db/sqlc"
	services "mw-training/internal/services"
	pb "mw-training/pkg/grpcAutogenerated/training"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"google.golang.org/protobuf/types/known/emptypb"
)

type TrainingController struct {
	trainingService *services.TrainingService
	pb.TrainingServiceServer
}

func NewTrainingController(trainingService *services.TrainingService) *TrainingController {
	return &TrainingController{trainingService: trainingService}
}

func (tc *TrainingController) CreateNewTraining(ctx context.Context, in *pb.CreateTrainingRequest) (*pb.Training, error) {
	name := in.GetName()

	arg := db.CreateTrainingParams{
		Name: pgtype.Text{String: name, Valid: true},
	}

	training, err := tc.trainingService.CreateTraining(ctx, arg)
	if err != nil {
		return nil, err
	}

	return &training, nil
}

func (tc *TrainingController) GetTrainingsList(ctx context.Context, in *pb.GetTrainingsListRequest) (*pb.TrainingPreviewList, error) {
	userUuid := in.GetUserUuid()
	// page := in.GetPage()
	// limit := in.GetLimit()
	// trainingName := in.GetTrainingName()

	trainings, err := tc.trainingService.GetTrainingList(ctx, pgtype.UUID{Bytes: uuid.MustParse(userUuid), Valid: true})
	if err != nil {
		return nil, err
	}

	return &pb.TrainingPreviewList{
		TrainingList: trainings,
	}, nil
}

func (tc *TrainingController) GetTrainingListForUser(ctx context.Context, in *pb.GetTrainingsListForUserRequest) (*pb.TrainingPreviewList, error) {
	userUuid := in.GetUserUuid()

	trainings, err := tc.trainingService.GetTrainingList(ctx, pgtype.UUID{Bytes: uuid.MustParse(userUuid), Valid: true})
	if err != nil {
		return nil, err
	}

	return &pb.TrainingPreviewList{
		TrainingList: trainings,
	}, nil
}

func (tc *TrainingController) GetTrainingById(ctx context.Context, in *pb.GetTrainingRequest) (*pb.Training, error) {
	trainingUuid := in.GetTrainingUuid()

	training, err := tc.trainingService.GetTrainingById(ctx, pgtype.UUID{Bytes: uuid.MustParse(trainingUuid), Valid: true})
	if err != nil {
		return nil, err
	}

	return &training, nil
}

func (tc *TrainingController) UpdateTraining(ctx context.Context, in *pb.UpdateTrainingRequest) (*pb.Training, error) {
	trainingUuid := in.GetUuid()
	trainingName := in.GetName()
	description := in.GetDescription()
	isPrivate := in.GetIsPrivate()

	arg := db.UpdateTrainingParams{
		TrainingUuid: pgtype.UUID{Bytes: uuid.MustParse(trainingUuid), Valid: true},
		Name:         pgtype.Text{String: trainingName, Valid: true},
		Description:  pgtype.Text{String: description, Valid: true},
		IsPrivate:    pgtype.Bool{Bool: isPrivate, Valid: true},
	}
	training, err := tc.trainingService.UpdateTraining(ctx, arg)
	if err != nil {
		return nil, err
	}
	return &training, nil
}

func (tc *TrainingController) DeleteTraining(ctx context.Context, in *pb.DeleteTrainingRequest) (*emptypb.Empty, error) {
	trainingUuid := in.GetUuid()

	err := tc.trainingService.DeleteTraining(ctx, pgtype.UUID{Bytes: uuid.MustParse(trainingUuid), Valid: true})
	if err != nil {
		return nil, err
	}

	return &emptypb.Empty{}, nil
}
