// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SchemasMetricResponse } from './SchemasMetricResponse';
import {
    SchemasMetricResponseFromJSON,
    SchemasMetricResponseFromJSONTyped,
    SchemasMetricResponseToJSON,
} from './SchemasMetricResponse';

/**
 * 
 * @export
 * @interface SchemasMetricTreeNode
 */
export interface SchemasMetricTreeNode {
    /**
     * 
     * @type {Array<SchemasMetricTreeNode>}
     * @memberof SchemasMetricTreeNode
     */
    children: Array<SchemasMetricTreeNode>;
    /**
     * 
     * @type {SchemasMetricResponse}
     * @memberof SchemasMetricTreeNode
     */
    metric: SchemasMetricResponse;
}

/**
 * Check if a given object implements the SchemasMetricTreeNode interface.
 */
export function instanceOfSchemasMetricTreeNode(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "children" in value;
    isInstance = isInstance && "metric" in value;

    return isInstance;
}

export function SchemasMetricTreeNodeFromJSON(json: any): SchemasMetricTreeNode {
    return SchemasMetricTreeNodeFromJSONTyped(json, false);
}

export function SchemasMetricTreeNodeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasMetricTreeNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'children': ((json['children'] as Array<any>).map(SchemasMetricTreeNodeFromJSON)),
        'metric': SchemasMetricResponseFromJSON(json['metric']),
    };
}


export function SchemasMetricTreeNodeToJSON(value?: SchemasMetricTreeNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'children': ((value.children as Array<any>).map(SchemasMetricTreeNodeToJSON)),
        'metric': SchemasMetricResponseToJSON(value.metric),
    };
}

