{
 "title": "business metrics",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "All users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) from users;\n" }
   ]
  },
  {
   "title": "All  Users who created at least 3 reports for all time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n    SELECT \n        COUNT(day_reports.uuid) AS day_reports_amount, \n        users.name\n    FROM users\n    LEFT JOIN ways ON ways.owner_uuid = users.uuid\n    LEFT JOIN day_reports ON day_reports.way_uuid = ways.uuid\n    GROUP BY users.uuid, users.name\n) AS subquery\nWHERE day_reports_amount >= 3;\n\n"
    }
   ]
  },
  {
   "title": "All  Users who created at least 10 reports",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n    SELECT \n        COUNT(day_reports.uuid) AS day_reports_amount, \n        users.name\n    FROM users\n    LEFT JOIN ways ON ways.owner_uuid = users.uuid\n    LEFT JOIN day_reports ON day_reports.way_uuid = ways.uuid\n    GROUP BY users.uuid, users.name\n) AS subquery\nWHERE day_reports_amount >= 10;\n"
    }
   ]
  },
  {
   "title": "New Users in past 30 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) \nFROM users\nWHERE created_at >= NOW() - INTERVAL '30 days'"
    }
   ]
  },
  {
   "title": "New Users who create 3 reports",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from (\n select count(day_reports.uuid) as day_reports_amount, users.name from users\n left join ways on ways.owner_uuid = users.\"uuid\"\n left join day_reports on day_reports.way_uuid = ways.uuid\n where\n (users.created_at > NOW() - INTERVAL '30 days')\n group by users.uuid\n) where day_reports_amount > 3;"
    }
   ]
  },
  {
   "title": "New Users who create 10 reports",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from (\n select count(day_reports.uuid) as day_reports_amount, users.name from users\n left join ways on ways.owner_uuid = users.\"uuid\"\n left join day_reports on day_reports.way_uuid = ways.uuid\n where\n (users.created_at > NOW() - INTERVAL '30 days')\n group by users.uuid\n order by day_reports_amount DESC\n) where day_reports_amount > 10;"
    }
   ]
  },
  {
   "title": "All Ways",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM ways;\n" }
   ]
  },
  {
   "title": "New Ways in past 30 days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) FROM ways\nWHERE created_at >= NOW() - INTERVAL '30 days'\n"
    }
   ]
  },
  {
   "title": "Ways created in last 30 days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT users.uuid) FROM users join ways on ways.owner_uuid = users.uuid WHERE ways.created_at > NOW() - INTERVAL '30 days';"
    }
   ]
  },
  {
   "title": "Total Trainings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) FROM trainings;"
    }
   ]
  },
  {
   "title": "New Trainings in past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) \nFROM trainings\nWHERE created_at >= NOW() - INTERVAL '30 days'\n"
    }
   ]
  },
  {
   "title": "Number of ways copied from Ways",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT (ways.copied_from_way_uuid )\nFROM \n    ways\nwhere \n ways.copied_from_way_uuid IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Number of ways copied from Ways",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT (ways.copied_from_trainings_uuid )\nFROM \n    ways\nwhere \n ways.copied_from_way_uuid IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Amount of users for each pricing plan for all time",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  'Free' AS metric, \n  COUNT(users.uuid) AS value, \n  NOW() AS time \nFROM profile_settings\nJOIN users\n  ON users.uuid = profile_settings.owner_uuid\nWHERE profile_settings.pricing_plan = 'free'\n\nUNION ALL\n\nSELECT\n  'Starter' AS metric, \n  COUNT(users.uuid) AS value, \n  NOW() AS time \nFROM profile_settings\nJOIN users\n  ON users.uuid = profile_settings.owner_uuid\nWHERE profile_settings.pricing_plan = 'starter'\n\nUNION ALL\n\nSELECT\n  'Pro' AS metric, \n  COUNT(users.uuid) AS value, \n  NOW() AS time \nFROM profile_settings\nJOIN users\n  ON users.uuid = profile_settings.owner_uuid\nWHERE profile_settings.pricing_plan = 'pro';"
    }
   ]
  },
  {
   "title": "Amount of mentors per users",
   "type": "histogram",
   "gridPos": { "h": 13, "w": 10, "x": 9, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(mentor_users_ways.way_uuid) as users_count,\n    NOW() as time\nFROM \n    users \nLEFT JOIN \n    mentor_users_ways  ON users.uuid = mentor_users_ways.user_uuid\nGROUP BY \n    users .uuid, users .name\n"
    }
   ]
  },
  {
   "title": "Total number of users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('month', created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('month', created_at)) AS total_users\nFROM users\nGROUP BY DATE_TRUNC('month', created_at)"
    }
   ]
  },
  {
   "title": "NUMBER OF USERS WHICH HAVE X REPORTS",
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 46 }
  },
  {
   "title": "Total number of users which have more than 1 report ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', users.created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('day', users.created_at)) AS total_users\nFROM users\nJOIN (\n  SELECT ways.owner_uuid\n  FROM ways\n  JOIN day_reports ON ways.uuid = day_reports.way_uuid\n  GROUP BY ways.owner_uuid\n  HAVING COUNT(day_reports.uuid) > 1\n) AS report_counts ON users.uuid = report_counts.owner_uuid\nGROUP BY DATE_TRUNC('day', users.created_at)"
    }
   ]
  },
  {
   "title": "Total number of users which have more than 3 reports ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', users.created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('day', users.created_at))\n    AS total_users\nFROM users\nJOIN (\n  SELECT DISTINCT ways.owner_uuid\n  FROM ways\n  JOIN day_reports ON ways.uuid = day_reports.way_uuid\n  GROUP BY ways.owner_uuid\n  HAVING COUNT(day_reports.uuid) > 3\n) AS report_counts ON users.uuid = report_counts.owner_uuid\nGROUP BY DATE_TRUNC('day', users.created_at)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Total number of users which have more than 20 reports ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', users.created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('day', users.created_at))\n    AS total_users\nFROM users\nJOIN (\n  SELECT DISTINCT ways.owner_uuid\n  FROM ways\n  JOIN day_reports ON ways.uuid = day_reports.way_uuid\n  GROUP BY ways.owner_uuid\n  HAVING COUNT(day_reports.uuid) > 20\n) AS report_counts ON users.uuid = report_counts.owner_uuid\nGROUP BY DATE_TRUNC('day', users.created_at)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Total number of users which have more than 30 reports ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', users.created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('day', users.created_at))\n    AS total_users\nFROM users\nJOIN (\n  SELECT DISTINCT ways.owner_uuid\n  FROM ways\n  JOIN day_reports ON ways.uuid = day_reports.way_uuid\n  GROUP BY ways.owner_uuid\n  HAVING COUNT(day_reports.uuid) > 30\n) AS report_counts ON users.uuid = report_counts.owner_uuid\nGROUP BY DATE_TRUNC('day', users.created_at)"
    }
   ]
  },
  { "title": "NUMBER OF REPORT PER WAY", "type": "text", "gridPos": { "h": 2, "w": 23, "x": 0, "y": 60 } },
  {
   "title": "Number of Reports per Way for all time(reports/way)",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "WITH report_counts_per_way AS (\n  SELECT\n    way_uuid,\n    COUNT(uuid) AS report_count\n  FROM day_reports\n  GROUP BY way_uuid\n)\nSELECT\n  report_count,\n  COUNT(way_uuid) AS way_count,\n  NOW() AS time\nFROM report_counts_per_way\nGROUP BY report_count\nORDER BY report_count ASC;"
    }
   ]
  },
  {
   "title": "Number of Reports per Way for last year(reports/way)",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 62 },
   "targets": [
    {
     "rawSql": "WITH report_counts_per_way AS (\n  SELECT\n    way_uuid,\n    COUNT(uuid) AS report_count\n  FROM day_reports\n  WHERE created_at >= NOW() - INTERVAL '1 year'\n  GROUP BY way_uuid\n)\nSELECT\n  report_count,\n  COUNT(way_uuid) AS way_count,\n  NOW() AS time\nFROM report_counts_per_way\nGROUP BY report_count\nORDER BY report_count ASC;"
    }
   ]
  },
  {
   "title": "Number of Reports per Way for last 90 days(reports/way)",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 62 },
   "targets": [
    {
     "rawSql": "WITH report_counts_per_way AS (\n  SELECT\n    way_uuid,\n    COUNT(uuid) AS report_count\n  FROM day_reports\n  WHERE created_at >= NOW() - INTERVAL '90 days'\n  GROUP BY way_uuid\n)\nSELECT\n  report_count,\n  COUNT(way_uuid) AS way_count,\n  NOW() AS time\nFROM report_counts_per_way\nGROUP BY report_count\nORDER BY report_count ASC;"
    }
   ]
  },
  {
   "title": "Number of Reports per Way for last 30 days(reports/way)",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 62 },
   "targets": [
    {
     "rawSql": "WITH report_counts_per_way AS (\n  SELECT\n    way_uuid,\n    COUNT(uuid) AS report_count\n  FROM day_reports\n  WHERE created_at >= NOW() - INTERVAL '30 days'\n  GROUP BY way_uuid\n)\nSELECT\n  report_count,\n  COUNT(way_uuid) AS way_count,\n  NOW() AS time\nFROM report_counts_per_way\nGROUP BY report_count\nORDER BY report_count ASC;"
    }
   ]
  },
  {
   "title": "Number of Reports per Way for last 7 days(reports/way)",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 62 },
   "targets": [
    {
     "rawSql": "WITH report_counts_per_way AS (\n  SELECT\n    way_uuid,\n    COUNT(uuid) AS report_count\n  FROM day_reports\n  WHERE created_at >= NOW() - INTERVAL '30 days'\n  GROUP BY way_uuid\n)\nSELECT\n  report_count,\n  COUNT(way_uuid) AS way_count,\n  NOW() AS time\nFROM report_counts_per_way\nGROUP BY report_count\nORDER BY report_count ASC;"
    }
   ]
  }
 ]
}