{
 "title": "Business matrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT COUNT(*) from users;\n" }
   ]
  },
  {
   "title": "All  Users who created at least 3 reports",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n    SELECT \n        COUNT(day_reports.uuid) AS day_reports_amount, \n        users.name\n    FROM users\n    LEFT JOIN ways ON ways.owner_uuid = users.uuid\n    LEFT JOIN day_reports ON day_reports.way_uuid = ways.uuid\n    WHERE day_reports.created_at >= CURRENT_DATE - INTERVAL '30 days'\n    GROUP BY users.uuid, users.name\n    ORDER BY day_reports_amount DESC\n) AS subquery\nWHERE day_reports_amount >= 3;\n"
    }
   ]
  },
  {
   "title": "All  Users who created at least 10 reports",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n    SELECT \n        COUNT(day_reports.uuid) AS day_reports_amount, \n        users.name\n    FROM users\n    LEFT JOIN ways ON ways.owner_uuid = users.uuid\n    LEFT JOIN day_reports ON day_reports.way_uuid = ways.uuid\n    WHERE day_reports.created_at >= CURRENT_DATE - INTERVAL '30 days'\n    GROUP BY users.uuid, users.name\n    ORDER BY day_reports_amount DESC\n) AS subquery\nWHERE day_reports_amount >= 10;\n"
    }
   ]
  },
  {
   "title": "New Users in past 30 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) \nFROM users\nWHERE created_at >= NOW() - INTERVAL '30 days'"
    }
   ]
  },
  {
   "title": "New Users who create 3 reports",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "select * from (\n select count(day_reports.uuid) as day_reports_amount, users.name from users\n left join ways on ways.owner_uuid = users.\"uuid\"\n left join day_reports on day_reports.way_uuid = ways.uuid\n where\n (users.created_at > NOW() - INTERVAL '30 days')\n group by users.uuid\n order by day_reports_amount DESC\n) where day_reports_amount > 3;"
    }
   ]
  },
  {
   "title": "New Users who create 10 reports",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
   "targets": [
    {
     "rawSql": "select * from (\n select count(day_reports.uuid) as day_reports_amount, users.name from users\n left join ways on ways.owner_uuid = users.\"uuid\"\n left join day_reports on day_reports.way_uuid = ways.uuid\n where\n (users.created_at > NOW() - INTERVAL '30 days')\n group by users.uuid\n order by day_reports_amount DESC\n) where day_reports_amount > 10;"
    }
   ]
  },
  {
   "title": "All Ways",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM ways;\n" }
   ]
  },
  {
   "title": "New Ways in past 30 days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) FROM ways\nWHERE created_at >= NOW() - INTERVAL '30 days'\n"
    }
   ]
  },
  {
   "title": "Users who create ways n last 30 days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT users.uuid) FROM users join ways on ways.owner_uuid = users.uuid WHERE users.created_at > NOW() - INTERVAL '30 days';"
    }
   ]
  },
  {
   "title": "Total Trainings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) FROM trainings;"
    }
   ]
  },
  {
   "title": "New Trainings in past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 7, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) \nFROM trainings\nWHERE created_at >= NOW() - INTERVAL '30 days'\n"
    }
   ]
  },
  {
   "title": "Total number of users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('month', created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('month', created_at)) AS total_users\nFROM users\nGROUP BY DATE_TRUNC('month', created_at)"
    }
   ]
  },
  {
   "title": "Total number of users which have more than 1 report",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('month', u.created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('month', u.created_at)) AS total_users\nFROM users u\nJOIN (\n  SELECT DISTINCT w.owner_uuid\n  FROM ways w\n  JOIN day_reports dr ON w.uuid = dr.way_uuid\n  GROUP BY w.owner_uuid\n  HAVING COUNT(dr.uuid) > 1\n) report_counts ON u.uuid = report_counts.owner_uuid\nGROUP BY DATE_TRUNC('month', u.created_at)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total number of users which have more than 3 reports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('month', u.created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('month', u.created_at)) AS total_users\nFROM users u\nJOIN (\n  SELECT DISTINCT w.owner_uuid\n  FROM ways w\n  JOIN day_reports dr ON w.uuid = dr.way_uuid\n  GROUP BY w.owner_uuid\n  HAVING COUNT(dr.uuid) > 3\n) report_counts ON u.uuid = report_counts.owner_uuid\nGROUP BY DATE_TRUNC('month', u.created_at)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total number of users which have more than 20 reports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('month', u.created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('month', u.created_at)) AS total_users\nFROM users u\nJOIN (\n  SELECT DISTINCT w.owner_uuid\n  FROM ways w\n  JOIN day_reports dr ON w.uuid = dr.way_uuid\n  GROUP BY w.owner_uuid\n  HAVING COUNT(dr.uuid) > 20\n) report_counts ON u.uuid = report_counts.owner_uuid\nGROUP BY DATE_TRUNC('month', u.created_at)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total number of users which have more than 30 reports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('month', u.created_at) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('month', u.created_at)) AS total_users\nFROM users u\nJOIN (\n  SELECT DISTINCT w.owner_uuid\n  FROM ways w\n  JOIN day_reports dr ON w.uuid = dr.way_uuid\n  GROUP BY w.owner_uuid\n  HAVING COUNT(dr.uuid) > 30\n) report_counts ON u.uuid = report_counts.owner_uuid\nGROUP BY DATE_TRUNC('month', u.created_at)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average amount of day reports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none", "label": "way_count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  w.uuid as metric,\n  NOW() as time,\n  COUNT(dr.uuid) as report_count\nFROM ways w\nJOIN day_reports dr ON w.uuid = dr.way_uuid\nGROUP BY w.uuid"
    }
   ]
  }
 ]
}