{
 "title": "Main dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT COUNT(*) from users;\n" }
   ]
  },
  {
   "title": "New Users in past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) \nFROM users\nWHERE created_at >= NOW() - INTERVAL '30 days'"
    }
   ]
  },
  {
   "title": "All Ways",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM ways;\n" }
   ]
  },
  {
   "title": "New Ways in past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) FROM ways\nWHERE created_at >= NOW() - INTERVAL '30 days'\n"
    }
   ]
  },
  {
   "title": "Total Trainings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) FROM trainings;"
    }
   ]
  },
  {
   "title": "New Trainings in past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) \nFROM trainings\nWHERE created_at >= NOW() - INTERVAL '30 days'\n"
    }
   ]
  }
 ]
}