{
 "title": "Metrics",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "impressions_manual", "query": "50000" },
   { "name": "revenue_per_paid_user", "query": "50" },
   { "name": "marketing_budget", "query": "40" },
   { "name": "paid_conversion", "query": "0.07" }
  ]
 },
 "panels": [
  {
   "title": "Funnel",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH base AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name IN ('MIN','MEAN','MAX')\r\n),\r\nmanual_base AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\ncalc_base AS (\r\n  SELECT\r\n    scenario_name,\r\n\r\n    impressions::numeric AS impressions,\r\n    impressions::numeric * ctr_rate AS site_visitors,\r\n    impressions::numeric * ctr_rate * cr_reg_rate AS registrations,\r\n    impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate AS paid_users\r\n  FROM base\r\n),\r\ncalc_manual AS (\r\n  SELECT\r\n    'MANUAL'::text AS scenario_name,\r\n\r\n    [[impressions_manual]]::numeric AS impressions,\r\n    [[impressions_manual]]::numeric * ctr_rate AS site_visitors,\r\n    [[impressions_manual]]::numeric * ctr_rate * cr_reg_rate AS registrations,\r\n    [[impressions_manual]]::numeric * ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric AS paid_users\r\n\r\n  FROM manual_base\r\n),\r\ncalc_all AS (\r\n  SELECT * FROM calc_base\r\n  UNION ALL\r\n  SELECT * FROM calc_manual\r\n)\r\nSELECT\r\n  metric,\r\n  MAX(CASE WHEN scenario_name = 'MIN'    THEN value END) AS \"MIN\",\r\n  MAX(CASE WHEN scenario_name = 'MEAN'   THEN value END) AS \"MEAN\",\r\n  MAX(CASE WHEN scenario_name = 'MAX'    THEN value END) AS \"MAX\",\r\n  MAX(CASE WHEN scenario_name = 'MANUAL' THEN value END) AS \"MANUAL\"\r\nFROM (\r\n  SELECT scenario_name, 'Impressions'   AS metric, impressions   AS value FROM calc_all\r\n  UNION ALL\r\n  SELECT scenario_name, 'Site visitors' AS metric, site_visitors AS value FROM calc_all\r\n  UNION ALL\r\n  SELECT scenario_name, 'Registrations' AS metric, registrations AS value FROM calc_all\r\n  UNION ALL\r\n  SELECT scenario_name, 'Paid users'    AS metric, paid_users AS value FROM calc_all\r\n) t\r\nGROUP BY metric\r\nORDER BY\r\n  CASE metric\r\n    WHEN 'Impressions' THEN 1\r\n    WHEN 'Site visitors' THEN 2\r\n    WHEN 'Registrations' THEN 3\r\n    WHEN 'Paid users' THEN 4\r\n  END;\r\n"
    }
   ]
  },
  {
   "title": "Paid users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH p AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\ncalc AS (\r\n  SELECT\r\n    'MEAN'::text AS name,\r\n    (impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate) AS value\r\n  FROM p\r\n\r\n  UNION ALL\r\n\r\n  SELECT\r\n    'MANUAL'::text AS name,\r\n    ([[impressions_manual]]::numeric * ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric) AS value\r\n  FROM p\r\n)\r\nSELECT name, value FROM calc;\r\n"
    }
   ]
  },
  {
   "title": "Total revenue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH p AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\ncalc AS (\r\n  SELECT\r\n    'MEAN'::text AS name,\r\n    (impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate)\r\n      * (${revenue_per_paid_user:raw})::numeric AS value\r\n  FROM p\r\n\r\n  UNION ALL\r\n\r\n  SELECT\r\n    'MANUAL'::text AS name,\r\n    ((${impressions_manual:raw})::numeric * ctr_rate * cr_reg_rate * [[paid_conversion]])\r\n      * (${revenue_per_paid_user:raw})::numeric AS value\r\n  FROM p\r\n)\r\nSELECT name, value FROM calc;\r\n"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH base AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name IN ('MIN','MEAN','MAX')\r\n),\r\nmanual_base AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\ncalc_base AS (\r\n  SELECT\r\n    scenario_name AS scenario,\r\n    impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate AS paid_users\r\n  FROM base\r\n),\r\ncalc_manual AS (\r\n  SELECT\r\n    'MANUAL'::text AS scenario,\r\n    [[impressions_manual]]::numeric\r\n      * ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric AS paid_users\r\n  FROM manual_base\r\n),\r\nfinal AS (\r\n  SELECT\r\n    scenario,\r\n    paid_users,\r\n    [[revenue_per_paid_user]]::numeric AS revenue_per_paid_user,\r\n    (paid_users * [[revenue_per_paid_user]]::numeric) AS total_revenue\r\n  FROM (\r\n    SELECT scenario, paid_users FROM calc_base\r\n    UNION ALL\r\n    SELECT scenario, paid_users FROM calc_manual\r\n  ) t\r\n)\r\nSELECT\r\n  metric,\r\n  MAX(CASE WHEN scenario = 'MIN' THEN value END)    AS \"MIN\",\r\n  MAX(CASE WHEN scenario = 'MEAN' THEN value END)   AS \"MEAN\",\r\n  MAX(CASE WHEN scenario = 'MAX' THEN value END)    AS \"MAX\",\r\n  MAX(CASE WHEN scenario = 'MANUAL' THEN value END) AS \"MANUAL\"\r\nFROM (\r\n  SELECT scenario, 'Paid users'            AS metric, paid_users            AS value FROM final\r\n  UNION ALL\r\n  SELECT scenario, 'Revenue per paid user' AS metric, revenue_per_paid_user AS value FROM final\r\n  UNION ALL\r\n  SELECT scenario, 'Total revenue'         AS metric, total_revenue         AS value FROM final\r\n) x\r\nGROUP BY metric\r\nORDER BY\r\n  CASE metric\r\n    WHEN 'Paid users' THEN 1\r\n    WHEN 'Revenue per paid user' THEN 2\r\n    WHEN 'Total revenue' THEN 3\r\n  END;\r\n"
    }
   ]
  },
  {
   "title": "Profit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH p AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\ncalc AS (\r\n  SELECT\r\n    'MEAN'::text AS name,\r\n    (\r\n      (impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate)\r\n        * (${revenue_per_paid_user:raw})::numeric\r\n      - (${marketing_budget:raw})::numeric\r\n    ) AS value\r\n  FROM p\r\n\r\n  UNION ALL\r\n\r\n  SELECT\r\n    'MANUAL'::text AS name,\r\n    (\r\n      ((${impressions_manual:raw})::numeric * ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric)\r\n        * (${revenue_per_paid_user:raw})::numeric\r\n      - (${marketing_budget:raw})::numeric\r\n    ) AS value\r\n  FROM p\r\n)\r\nSELECT name, value FROM calc;\r\n"
    }
   ]
  },
  {
   "title": "Break-even impressions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH p AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\nbe AS (\r\n  -- MEAN\r\n  SELECT\r\n    'MEAN'::text AS name,\r\n    CASE\r\n      WHEN (ctr_rate * cr_reg_rate * paid_conversion_rate * (${revenue_per_paid_user:raw})::numeric) = 0\r\n        THEN NULL\r\n      ELSE (${marketing_budget:raw})::numeric\r\n           / (ctr_rate * cr_reg_rate * paid_conversion_rate * (${revenue_per_paid_user:raw})::numeric)\r\n    END AS value\r\n  FROM p\r\n\r\n  UNION ALL\r\n\r\n  -- MANUAL (только paid_conversion меняем)\r\n  SELECT\r\n    'MANUAL'::text AS name,\r\n    CASE\r\n      WHEN (ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric * (${revenue_per_paid_user:raw})::numeric) = 0\r\n        THEN NULL\r\n      ELSE (${marketing_budget:raw})::numeric\r\n           / (ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric * (${revenue_per_paid_user:raw})::numeric)\r\n    END AS value\r\n  FROM p\r\n)\r\nSELECT name, value FROM be;\r\n"
    }
   ]
  },
  {
   "title": "Unit economics",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH base AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name IN ('MIN','MEAN','MAX')\r\n),\r\nmanual_base AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\ncalc_base AS (\r\n  SELECT\r\n    scenario_name AS scenario,\r\n    impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate AS paid_users\r\n  FROM base\r\n),\r\ncalc_manual AS (\r\n  SELECT\r\n    'MANUAL'::text AS scenario,\r\n    (${impressions_manual:raw})::numeric\r\n      * ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric AS paid_users\r\n  FROM manual_base\r\n),\r\ncalc_all AS (\r\n  SELECT * FROM calc_base\r\n  UNION ALL\r\n  SELECT * FROM calc_manual\r\n),\r\nfinal AS (\r\n  SELECT\r\n    scenario,\r\n    paid_users,\r\n    (${revenue_per_paid_user:raw})::numeric AS revenue_per_paid_user,\r\n    (${marketing_budget:raw})::numeric      AS marketing_budget,\r\n    paid_users * (${revenue_per_paid_user:raw})::numeric AS total_revenue,\r\n    paid_users * (${revenue_per_paid_user:raw})::numeric\r\n      - (${marketing_budget:raw})::numeric AS profit,\r\n    CASE\r\n      WHEN (${marketing_budget:raw})::numeric = 0 THEN NULL\r\n      ELSE (\r\n        (paid_users * (${revenue_per_paid_user:raw})::numeric\r\n        - (${marketing_budget:raw})::numeric)\r\n        / (${marketing_budget:raw})::numeric\r\n      )\r\n    END AS romi,\r\n    CASE\r\n      WHEN paid_users = 0 THEN NULL\r\n      ELSE (${marketing_budget:raw})::numeric / paid_users\r\n    END AS cpa\r\n  FROM calc_all\r\n)\r\nSELECT\r\n  metric,\r\n  MAX(CASE WHEN scenario = 'MIN' THEN value END)    AS \"MIN\",\r\n  MAX(CASE WHEN scenario = 'MEAN' THEN value END)   AS \"MEAN\",\r\n  MAX(CASE WHEN scenario = 'MAX' THEN value END)    AS \"MAX\",\r\n  MAX(CASE WHEN scenario = 'MANUAL' THEN value END) AS \"MANUAL\"\r\nFROM (\r\n  SELECT scenario, 'Profit'           AS metric, profit           AS value FROM final\r\n  UNION ALL\r\n  SELECT scenario, 'ROMI'             AS metric, romi             AS value FROM final\r\n  UNION ALL\r\n  SELECT scenario, 'Marketing budget' AS metric, marketing_budget AS value FROM final\r\n  UNION ALL\r\n  SELECT scenario, 'CPA'              AS metric, cpa              AS value FROM final\r\n) t\r\nGROUP BY metric\r\nORDER BY\r\n  CASE metric\r\n    WHEN 'Profit' THEN 1\r\n    WHEN 'ROMI' THEN 2\r\n    WHEN 'Marketing budget' THEN 3\r\n    WHEN 'CPA' THEN 4\r\n  END;\r\n"
    }
   ]
  },
  {
   "title": "ROMI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH p AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\ncalc AS (\r\n  -- MEAN\r\n  SELECT\r\n    'MEAN'::text AS name,\r\n    CASE\r\n      WHEN (${marketing_budget:raw})::numeric = 0 THEN NULL\r\n      ELSE (\r\n        (\r\n          (impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate)\r\n            * (${revenue_per_paid_user:raw})::numeric\r\n          - (${marketing_budget:raw})::numeric\r\n        ) / (${marketing_budget:raw})::numeric\r\n      )\r\n    END AS value\r\n  FROM p\r\n\r\n  UNION ALL\r\n\r\n  SELECT\r\n    'MANUAL'::text AS name,\r\n    CASE\r\n      WHEN (${marketing_budget:raw})::numeric = 0 THEN NULL\r\n      ELSE (\r\n        (\r\n          ((${impressions_manual:raw})::numeric * ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric)\r\n            * (${revenue_per_paid_user:raw})::numeric\r\n          - (${marketing_budget:raw})::numeric\r\n        ) / (${marketing_budget:raw})::numeric\r\n      )\r\n    END AS value\r\n  FROM p\r\n)\r\nSELECT name, value FROM calc;\r\n"
    }
   ]
  },
  {
   "title": "CPA",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "WITH p AS (\r\n  SELECT *\r\n  FROM mw_marketing.scenarios\r\n  WHERE scenario_name = 'MEAN'\r\n),\r\ncalc AS (\r\n  -- MEAN\r\n  SELECT\r\n    'MEAN'::text AS name,\r\n    CASE\r\n      WHEN (impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate) = 0 THEN NULL\r\n      ELSE (${marketing_budget:raw})::numeric\r\n           / (impressions::numeric * ctr_rate * cr_reg_rate * paid_conversion_rate)\r\n    END AS value\r\n  FROM p\r\n\r\n  UNION ALL\r\n\r\n  -- MANUAL (paid_conversion берём из переменной)\r\n  SELECT\r\n    'MANUAL'::text AS name,\r\n    CASE\r\n      WHEN ((${impressions_manual:raw})::numeric * ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric) = 0 THEN NULL\r\n      ELSE (${marketing_budget:raw})::numeric\r\n           / ((${impressions_manual:raw})::numeric * ctr_rate * cr_reg_rate * [[paid_conversion]]::numeric)\r\n    END AS value\r\n  FROM p\r\n)\r\nSELECT name, value FROM calc;\r\n"
    }
   ]
  }
 ]
}