// @ts-nocheck
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SchemasRequestToGroupRoom } from './SchemasRequestToGroupRoom';
import {
    SchemasRequestToGroupRoomFromJSON,
    SchemasRequestToGroupRoomFromJSONTyped,
    SchemasRequestToGroupRoomToJSON,
} from './SchemasRequestToGroupRoom';

/**
 * 
 * @export
 * @interface SchemasGetRequestsToGroupRoomResponse
 */
export interface SchemasGetRequestsToGroupRoomResponse {
    /**
     * 
     * @type {Array<SchemasRequestToGroupRoom>}
     * @memberof SchemasGetRequestsToGroupRoomResponse
     */
    requests: Array<SchemasRequestToGroupRoom>;
}

/**
 * Check if a given object implements the SchemasGetRequestsToGroupRoomResponse interface.
 */
export function instanceOfSchemasGetRequestsToGroupRoomResponse(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "requests" in value;

    return isInstance;
}

export function SchemasGetRequestsToGroupRoomResponseFromJSON(json: any): SchemasGetRequestsToGroupRoomResponse {
    return SchemasGetRequestsToGroupRoomResponseFromJSONTyped(json, false);
}

export function SchemasGetRequestsToGroupRoomResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasGetRequestsToGroupRoomResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requests': ((json['requests'] as Array<any>).map(SchemasRequestToGroupRoomFromJSON)),
    };
}


export function SchemasGetRequestsToGroupRoomResponseToJSON(value?: SchemasGetRequestsToGroupRoomResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requests': ((value.requests as Array<any>).map(SchemasRequestToGroupRoomToJSON)),
    };
}

