/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SchemasLabelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemasLabelResponse{}

// SchemasLabelResponse struct for SchemasLabelResponse
type SchemasLabelResponse struct {
	Color string `json:"color"`
	Description string `json:"description"`
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}

type _SchemasLabelResponse SchemasLabelResponse

// NewSchemasLabelResponse instantiates a new SchemasLabelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemasLabelResponse(color string, description string, name string, uuid string) *SchemasLabelResponse {
	this := SchemasLabelResponse{}
	this.Color = color
	this.Description = description
	this.Name = name
	this.Uuid = uuid
	return &this
}

// NewSchemasLabelResponseWithDefaults instantiates a new SchemasLabelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemasLabelResponseWithDefaults() *SchemasLabelResponse {
	this := SchemasLabelResponse{}
	return &this
}

// GetColor returns the Color field value
func (o *SchemasLabelResponse) GetColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Color
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
func (o *SchemasLabelResponse) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color, true
}

// SetColor sets field value
func (o *SchemasLabelResponse) SetColor(v string) {
	o.Color = v
}

// GetDescription returns the Description field value
func (o *SchemasLabelResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SchemasLabelResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SchemasLabelResponse) SetDescription(v string) {
	o.Description = v
}

// GetName returns the Name field value
func (o *SchemasLabelResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SchemasLabelResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SchemasLabelResponse) SetName(v string) {
	o.Name = v
}

// GetUuid returns the Uuid field value
func (o *SchemasLabelResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *SchemasLabelResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *SchemasLabelResponse) SetUuid(v string) {
	o.Uuid = v
}

func (o SchemasLabelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemasLabelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["color"] = o.Color
	toSerialize["description"] = o.Description
	toSerialize["name"] = o.Name
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *SchemasLabelResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"color",
		"description",
		"name",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchemasLabelResponse := _SchemasLabelResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSchemasLabelResponse)

	if err != nil {
		return err
	}

	*o = SchemasLabelResponse(varSchemasLabelResponse)

	return err
}

type NullableSchemasLabelResponse struct {
	value *SchemasLabelResponse
	isSet bool
}

func (v NullableSchemasLabelResponse) Get() *SchemasLabelResponse {
	return v.value
}

func (v *NullableSchemasLabelResponse) Set(val *SchemasLabelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemasLabelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemasLabelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemasLabelResponse(val *SchemasLabelResponse) *NullableSchemasLabelResponse {
	return &NullableSchemasLabelResponse{value: val, isSet: true}
}

func (v NullableSchemasLabelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemasLabelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


