/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwserverInternalSchemasCreateWayCollectionPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwserverInternalSchemasCreateWayCollectionPayload{}

// MwserverInternalSchemasCreateWayCollectionPayload struct for MwserverInternalSchemasCreateWayCollectionPayload
type MwserverInternalSchemasCreateWayCollectionPayload struct {
	Name string `json:"name"`
	OwnerUuid string `json:"ownerUuid"`
}

type _MwserverInternalSchemasCreateWayCollectionPayload MwserverInternalSchemasCreateWayCollectionPayload

// NewMwserverInternalSchemasCreateWayCollectionPayload instantiates a new MwserverInternalSchemasCreateWayCollectionPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwserverInternalSchemasCreateWayCollectionPayload(name string, ownerUuid string) *MwserverInternalSchemasCreateWayCollectionPayload {
	this := MwserverInternalSchemasCreateWayCollectionPayload{}
	this.Name = name
	this.OwnerUuid = ownerUuid
	return &this
}

// NewMwserverInternalSchemasCreateWayCollectionPayloadWithDefaults instantiates a new MwserverInternalSchemasCreateWayCollectionPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwserverInternalSchemasCreateWayCollectionPayloadWithDefaults() *MwserverInternalSchemasCreateWayCollectionPayload {
	this := MwserverInternalSchemasCreateWayCollectionPayload{}
	return &this
}

// GetName returns the Name field value
func (o *MwserverInternalSchemasCreateWayCollectionPayload) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MwserverInternalSchemasCreateWayCollectionPayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MwserverInternalSchemasCreateWayCollectionPayload) SetName(v string) {
	o.Name = v
}

// GetOwnerUuid returns the OwnerUuid field value
func (o *MwserverInternalSchemasCreateWayCollectionPayload) GetOwnerUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerUuid
}

// GetOwnerUuidOk returns a tuple with the OwnerUuid field value
// and a boolean to check if the value has been set.
func (o *MwserverInternalSchemasCreateWayCollectionPayload) GetOwnerUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerUuid, true
}

// SetOwnerUuid sets field value
func (o *MwserverInternalSchemasCreateWayCollectionPayload) SetOwnerUuid(v string) {
	o.OwnerUuid = v
}

func (o MwserverInternalSchemasCreateWayCollectionPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwserverInternalSchemasCreateWayCollectionPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["ownerUuid"] = o.OwnerUuid
	return toSerialize, nil
}

func (o *MwserverInternalSchemasCreateWayCollectionPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"ownerUuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwserverInternalSchemasCreateWayCollectionPayload := _MwserverInternalSchemasCreateWayCollectionPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwserverInternalSchemasCreateWayCollectionPayload)

	if err != nil {
		return err
	}

	*o = MwserverInternalSchemasCreateWayCollectionPayload(varMwserverInternalSchemasCreateWayCollectionPayload)

	return err
}

type NullableMwserverInternalSchemasCreateWayCollectionPayload struct {
	value *MwserverInternalSchemasCreateWayCollectionPayload
	isSet bool
}

func (v NullableMwserverInternalSchemasCreateWayCollectionPayload) Get() *MwserverInternalSchemasCreateWayCollectionPayload {
	return v.value
}

func (v *NullableMwserverInternalSchemasCreateWayCollectionPayload) Set(val *MwserverInternalSchemasCreateWayCollectionPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwserverInternalSchemasCreateWayCollectionPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwserverInternalSchemasCreateWayCollectionPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwserverInternalSchemasCreateWayCollectionPayload(val *MwserverInternalSchemasCreateWayCollectionPayload) *NullableMwserverInternalSchemasCreateWayCollectionPayload {
	return &NullableMwserverInternalSchemasCreateWayCollectionPayload{value: val, isSet: true}
}

func (v NullableMwserverInternalSchemasCreateWayCollectionPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwserverInternalSchemasCreateWayCollectionPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


