version: "3.9"
services:
  chat-postgres:
    image: postgres:16.2
    container_name: chat-postgres
    ports:
      - "5433:5432"
    volumes:
      - chat-db:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  chat-db: