/*
Masters way general-bff API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwGeneralBffInternalSchemasUserPopulatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwGeneralBffInternalSchemasUserPopulatedResponse{}

// MwGeneralBffInternalSchemasUserPopulatedResponse struct for MwGeneralBffInternalSchemasUserPopulatedResponse
type MwGeneralBffInternalSchemasUserPopulatedResponse struct {
	CreatedAt string `json:"createdAt"`
	CustomWayCollections []MwGeneralBffInternalSchemasWayCollectionPopulatedResponse `json:"customWayCollections"`
	DefaultWayCollections MwGeneralBffInternalSchemasDefaultWayCollections `json:"defaultWayCollections"`
	Description string `json:"description"`
	Email string `json:"email"`
	FavoriteForUsers []string `json:"favoriteForUsers"`
	FavoriteUsers []MwGeneralBffInternalSchemasUserPlainResponse `json:"favoriteUsers"`
	ImageUrl string `json:"imageUrl"`
	IsMentor bool `json:"isMentor"`
	Name string `json:"name"`
	Projects []MwGeneralBffInternalSchemasProjectPlainResponse `json:"projects"`
	Tags []MwGeneralBffInternalSchemasUserTagResponse `json:"tags"`
	UserContacts []MwGeneralBffInternalSchemasUserContact `json:"userContacts"`
	Uuid string `json:"uuid"`
	WayRequests []MwGeneralBffInternalSchemasWayPlainResponse `json:"wayRequests"`
}

type _MwGeneralBffInternalSchemasUserPopulatedResponse MwGeneralBffInternalSchemasUserPopulatedResponse

// NewMwGeneralBffInternalSchemasUserPopulatedResponse instantiates a new MwGeneralBffInternalSchemasUserPopulatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwGeneralBffInternalSchemasUserPopulatedResponse(createdAt string, customWayCollections []MwGeneralBffInternalSchemasWayCollectionPopulatedResponse, defaultWayCollections MwGeneralBffInternalSchemasDefaultWayCollections, description string, email string, favoriteForUsers []string, favoriteUsers []MwGeneralBffInternalSchemasUserPlainResponse, imageUrl string, isMentor bool, name string, projects []MwGeneralBffInternalSchemasProjectPlainResponse, tags []MwGeneralBffInternalSchemasUserTagResponse, userContacts []MwGeneralBffInternalSchemasUserContact, uuid string, wayRequests []MwGeneralBffInternalSchemasWayPlainResponse) *MwGeneralBffInternalSchemasUserPopulatedResponse {
	this := MwGeneralBffInternalSchemasUserPopulatedResponse{}
	this.CreatedAt = createdAt
	this.CustomWayCollections = customWayCollections
	this.DefaultWayCollections = defaultWayCollections
	this.Description = description
	this.Email = email
	this.FavoriteForUsers = favoriteForUsers
	this.FavoriteUsers = favoriteUsers
	this.ImageUrl = imageUrl
	this.IsMentor = isMentor
	this.Name = name
	this.Projects = projects
	this.Tags = tags
	this.UserContacts = userContacts
	this.Uuid = uuid
	this.WayRequests = wayRequests
	return &this
}

// NewMwGeneralBffInternalSchemasUserPopulatedResponseWithDefaults instantiates a new MwGeneralBffInternalSchemasUserPopulatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwGeneralBffInternalSchemasUserPopulatedResponseWithDefaults() *MwGeneralBffInternalSchemasUserPopulatedResponse {
	this := MwGeneralBffInternalSchemasUserPopulatedResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCustomWayCollections returns the CustomWayCollections field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetCustomWayCollections() []MwGeneralBffInternalSchemasWayCollectionPopulatedResponse {
	if o == nil {
		var ret []MwGeneralBffInternalSchemasWayCollectionPopulatedResponse
		return ret
	}

	return o.CustomWayCollections
}

// GetCustomWayCollectionsOk returns a tuple with the CustomWayCollections field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetCustomWayCollectionsOk() ([]MwGeneralBffInternalSchemasWayCollectionPopulatedResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomWayCollections, true
}

// SetCustomWayCollections sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetCustomWayCollections(v []MwGeneralBffInternalSchemasWayCollectionPopulatedResponse) {
	o.CustomWayCollections = v
}

// GetDefaultWayCollections returns the DefaultWayCollections field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetDefaultWayCollections() MwGeneralBffInternalSchemasDefaultWayCollections {
	if o == nil {
		var ret MwGeneralBffInternalSchemasDefaultWayCollections
		return ret
	}

	return o.DefaultWayCollections
}

// GetDefaultWayCollectionsOk returns a tuple with the DefaultWayCollections field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetDefaultWayCollectionsOk() (*MwGeneralBffInternalSchemasDefaultWayCollections, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultWayCollections, true
}

// SetDefaultWayCollections sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetDefaultWayCollections(v MwGeneralBffInternalSchemasDefaultWayCollections) {
	o.DefaultWayCollections = v
}

// GetDescription returns the Description field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetDescription(v string) {
	o.Description = v
}

// GetEmail returns the Email field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetEmail(v string) {
	o.Email = v
}

// GetFavoriteForUsers returns the FavoriteForUsers field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetFavoriteForUsers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FavoriteForUsers
}

// GetFavoriteForUsersOk returns a tuple with the FavoriteForUsers field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetFavoriteForUsersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FavoriteForUsers, true
}

// SetFavoriteForUsers sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetFavoriteForUsers(v []string) {
	o.FavoriteForUsers = v
}

// GetFavoriteUsers returns the FavoriteUsers field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetFavoriteUsers() []MwGeneralBffInternalSchemasUserPlainResponse {
	if o == nil {
		var ret []MwGeneralBffInternalSchemasUserPlainResponse
		return ret
	}

	return o.FavoriteUsers
}

// GetFavoriteUsersOk returns a tuple with the FavoriteUsers field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetFavoriteUsersOk() ([]MwGeneralBffInternalSchemasUserPlainResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.FavoriteUsers, true
}

// SetFavoriteUsers sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetFavoriteUsers(v []MwGeneralBffInternalSchemasUserPlainResponse) {
	o.FavoriteUsers = v
}

// GetImageUrl returns the ImageUrl field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageUrl, true
}

// SetImageUrl sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetImageUrl(v string) {
	o.ImageUrl = v
}

// GetIsMentor returns the IsMentor field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetIsMentor() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMentor
}

// GetIsMentorOk returns a tuple with the IsMentor field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetIsMentorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMentor, true
}

// SetIsMentor sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetIsMentor(v bool) {
	o.IsMentor = v
}

// GetName returns the Name field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetName(v string) {
	o.Name = v
}

// GetProjects returns the Projects field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetProjects() []MwGeneralBffInternalSchemasProjectPlainResponse {
	if o == nil {
		var ret []MwGeneralBffInternalSchemasProjectPlainResponse
		return ret
	}

	return o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetProjectsOk() ([]MwGeneralBffInternalSchemasProjectPlainResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Projects, true
}

// SetProjects sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetProjects(v []MwGeneralBffInternalSchemasProjectPlainResponse) {
	o.Projects = v
}

// GetTags returns the Tags field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetTags() []MwGeneralBffInternalSchemasUserTagResponse {
	if o == nil {
		var ret []MwGeneralBffInternalSchemasUserTagResponse
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetTagsOk() ([]MwGeneralBffInternalSchemasUserTagResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetTags(v []MwGeneralBffInternalSchemasUserTagResponse) {
	o.Tags = v
}

// GetUserContacts returns the UserContacts field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetUserContacts() []MwGeneralBffInternalSchemasUserContact {
	if o == nil {
		var ret []MwGeneralBffInternalSchemasUserContact
		return ret
	}

	return o.UserContacts
}

// GetUserContactsOk returns a tuple with the UserContacts field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetUserContactsOk() ([]MwGeneralBffInternalSchemasUserContact, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserContacts, true
}

// SetUserContacts sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetUserContacts(v []MwGeneralBffInternalSchemasUserContact) {
	o.UserContacts = v
}

// GetUuid returns the Uuid field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetUuid(v string) {
	o.Uuid = v
}

// GetWayRequests returns the WayRequests field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetWayRequests() []MwGeneralBffInternalSchemasWayPlainResponse {
	if o == nil {
		var ret []MwGeneralBffInternalSchemasWayPlainResponse
		return ret
	}

	return o.WayRequests
}

// GetWayRequestsOk returns a tuple with the WayRequests field value
// and a boolean to check if the value has been set.
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) GetWayRequestsOk() ([]MwGeneralBffInternalSchemasWayPlainResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.WayRequests, true
}

// SetWayRequests sets field value
func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) SetWayRequests(v []MwGeneralBffInternalSchemasWayPlainResponse) {
	o.WayRequests = v
}

func (o MwGeneralBffInternalSchemasUserPopulatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwGeneralBffInternalSchemasUserPopulatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["customWayCollections"] = o.CustomWayCollections
	toSerialize["defaultWayCollections"] = o.DefaultWayCollections
	toSerialize["description"] = o.Description
	toSerialize["email"] = o.Email
	toSerialize["favoriteForUsers"] = o.FavoriteForUsers
	toSerialize["favoriteUsers"] = o.FavoriteUsers
	toSerialize["imageUrl"] = o.ImageUrl
	toSerialize["isMentor"] = o.IsMentor
	toSerialize["name"] = o.Name
	toSerialize["projects"] = o.Projects
	toSerialize["tags"] = o.Tags
	toSerialize["userContacts"] = o.UserContacts
	toSerialize["uuid"] = o.Uuid
	toSerialize["wayRequests"] = o.WayRequests
	return toSerialize, nil
}

func (o *MwGeneralBffInternalSchemasUserPopulatedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"customWayCollections",
		"defaultWayCollections",
		"description",
		"email",
		"favoriteForUsers",
		"favoriteUsers",
		"imageUrl",
		"isMentor",
		"name",
		"projects",
		"tags",
		"userContacts",
		"uuid",
		"wayRequests",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwGeneralBffInternalSchemasUserPopulatedResponse := _MwGeneralBffInternalSchemasUserPopulatedResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwGeneralBffInternalSchemasUserPopulatedResponse)

	if err != nil {
		return err
	}

	*o = MwGeneralBffInternalSchemasUserPopulatedResponse(varMwGeneralBffInternalSchemasUserPopulatedResponse)

	return err
}

type NullableMwGeneralBffInternalSchemasUserPopulatedResponse struct {
	value *MwGeneralBffInternalSchemasUserPopulatedResponse
	isSet bool
}

func (v NullableMwGeneralBffInternalSchemasUserPopulatedResponse) Get() *MwGeneralBffInternalSchemasUserPopulatedResponse {
	return v.value
}

func (v *NullableMwGeneralBffInternalSchemasUserPopulatedResponse) Set(val *MwGeneralBffInternalSchemasUserPopulatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMwGeneralBffInternalSchemasUserPopulatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMwGeneralBffInternalSchemasUserPopulatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwGeneralBffInternalSchemasUserPopulatedResponse(val *MwGeneralBffInternalSchemasUserPopulatedResponse) *NullableMwGeneralBffInternalSchemasUserPopulatedResponse {
	return &NullableMwGeneralBffInternalSchemasUserPopulatedResponse{value: val, isSet: true}
}

func (v NullableMwGeneralBffInternalSchemasUserPopulatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwGeneralBffInternalSchemasUserPopulatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


