/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SchemasRoomPreviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemasRoomPreviewResponse{}

// SchemasRoomPreviewResponse struct for SchemasRoomPreviewResponse
type SchemasRoomPreviewResponse struct {
	IsBlocked bool `json:"isBlocked"`
	Name string `json:"name"`
	RoomId string `json:"roomId"`
}

type _SchemasRoomPreviewResponse SchemasRoomPreviewResponse

// NewSchemasRoomPreviewResponse instantiates a new SchemasRoomPreviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemasRoomPreviewResponse(isBlocked bool, name string, roomId string) *SchemasRoomPreviewResponse {
	this := SchemasRoomPreviewResponse{}
	this.IsBlocked = isBlocked
	this.Name = name
	this.RoomId = roomId
	return &this
}

// NewSchemasRoomPreviewResponseWithDefaults instantiates a new SchemasRoomPreviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemasRoomPreviewResponseWithDefaults() *SchemasRoomPreviewResponse {
	this := SchemasRoomPreviewResponse{}
	return &this
}

// GetIsBlocked returns the IsBlocked field value
func (o *SchemasRoomPreviewResponse) GetIsBlocked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsBlocked
}

// GetIsBlockedOk returns a tuple with the IsBlocked field value
// and a boolean to check if the value has been set.
func (o *SchemasRoomPreviewResponse) GetIsBlockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsBlocked, true
}

// SetIsBlocked sets field value
func (o *SchemasRoomPreviewResponse) SetIsBlocked(v bool) {
	o.IsBlocked = v
}

// GetName returns the Name field value
func (o *SchemasRoomPreviewResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SchemasRoomPreviewResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SchemasRoomPreviewResponse) SetName(v string) {
	o.Name = v
}

// GetRoomId returns the RoomId field value
func (o *SchemasRoomPreviewResponse) GetRoomId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoomId
}

// GetRoomIdOk returns a tuple with the RoomId field value
// and a boolean to check if the value has been set.
func (o *SchemasRoomPreviewResponse) GetRoomIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoomId, true
}

// SetRoomId sets field value
func (o *SchemasRoomPreviewResponse) SetRoomId(v string) {
	o.RoomId = v
}

func (o SchemasRoomPreviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemasRoomPreviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isBlocked"] = o.IsBlocked
	toSerialize["name"] = o.Name
	toSerialize["roomId"] = o.RoomId
	return toSerialize, nil
}

func (o *SchemasRoomPreviewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isBlocked",
		"name",
		"roomId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchemasRoomPreviewResponse := _SchemasRoomPreviewResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSchemasRoomPreviewResponse)

	if err != nil {
		return err
	}

	*o = SchemasRoomPreviewResponse(varSchemasRoomPreviewResponse)

	return err
}

type NullableSchemasRoomPreviewResponse struct {
	value *SchemasRoomPreviewResponse
	isSet bool
}

func (v NullableSchemasRoomPreviewResponse) Get() *SchemasRoomPreviewResponse {
	return v.value
}

func (v *NullableSchemasRoomPreviewResponse) Set(val *SchemasRoomPreviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemasRoomPreviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemasRoomPreviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemasRoomPreviewResponse(val *SchemasRoomPreviewResponse) *NullableSchemasRoomPreviewResponse {
	return &NullableSchemasRoomPreviewResponse{value: val, isSet: true}
}

func (v NullableSchemasRoomPreviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemasRoomPreviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


