/*
Masters way chat API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwChatInternalSchemasUpdateMessageStatusPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwChatInternalSchemasUpdateMessageStatusPayload{}

// MwChatInternalSchemasUpdateMessageStatusPayload struct for MwChatInternalSchemasUpdateMessageStatusPayload
type MwChatInternalSchemasUpdateMessageStatusPayload struct {
	IsRead bool `json:"isRead"`
}

type _MwChatInternalSchemasUpdateMessageStatusPayload MwChatInternalSchemasUpdateMessageStatusPayload

// NewMwChatInternalSchemasUpdateMessageStatusPayload instantiates a new MwChatInternalSchemasUpdateMessageStatusPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwChatInternalSchemasUpdateMessageStatusPayload(isRead bool) *MwChatInternalSchemasUpdateMessageStatusPayload {
	this := MwChatInternalSchemasUpdateMessageStatusPayload{}
	this.IsRead = isRead
	return &this
}

// NewMwChatInternalSchemasUpdateMessageStatusPayloadWithDefaults instantiates a new MwChatInternalSchemasUpdateMessageStatusPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwChatInternalSchemasUpdateMessageStatusPayloadWithDefaults() *MwChatInternalSchemasUpdateMessageStatusPayload {
	this := MwChatInternalSchemasUpdateMessageStatusPayload{}
	return &this
}

// GetIsRead returns the IsRead field value
func (o *MwChatInternalSchemasUpdateMessageStatusPayload) GetIsRead() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRead
}

// GetIsReadOk returns a tuple with the IsRead field value
// and a boolean to check if the value has been set.
func (o *MwChatInternalSchemasUpdateMessageStatusPayload) GetIsReadOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRead, true
}

// SetIsRead sets field value
func (o *MwChatInternalSchemasUpdateMessageStatusPayload) SetIsRead(v bool) {
	o.IsRead = v
}

func (o MwChatInternalSchemasUpdateMessageStatusPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwChatInternalSchemasUpdateMessageStatusPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isRead"] = o.IsRead
	return toSerialize, nil
}

func (o *MwChatInternalSchemasUpdateMessageStatusPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isRead",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwChatInternalSchemasUpdateMessageStatusPayload := _MwChatInternalSchemasUpdateMessageStatusPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwChatInternalSchemasUpdateMessageStatusPayload)

	if err != nil {
		return err
	}

	*o = MwChatInternalSchemasUpdateMessageStatusPayload(varMwChatInternalSchemasUpdateMessageStatusPayload)

	return err
}

type NullableMwChatInternalSchemasUpdateMessageStatusPayload struct {
	value *MwChatInternalSchemasUpdateMessageStatusPayload
	isSet bool
}

func (v NullableMwChatInternalSchemasUpdateMessageStatusPayload) Get() *MwChatInternalSchemasUpdateMessageStatusPayload {
	return v.value
}

func (v *NullableMwChatInternalSchemasUpdateMessageStatusPayload) Set(val *MwChatInternalSchemasUpdateMessageStatusPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwChatInternalSchemasUpdateMessageStatusPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwChatInternalSchemasUpdateMessageStatusPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwChatInternalSchemasUpdateMessageStatusPayload(val *MwChatInternalSchemasUpdateMessageStatusPayload) *NullableMwChatInternalSchemasUpdateMessageStatusPayload {
	return &NullableMwChatInternalSchemasUpdateMessageStatusPayload{value: val, isSet: true}
}

func (v NullableMwChatInternalSchemasUpdateMessageStatusPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwChatInternalSchemasUpdateMessageStatusPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


