// @ts-nocheck
/* eslint-disable */
/**
 * Masters way training-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MwTrainingBffInternalSchemasCreateTrainingTrainingTagPayload,
} from '../models/index';
import {
    MwTrainingBffInternalSchemasCreateTrainingTrainingTagPayloadFromJSON,
    MwTrainingBffInternalSchemasCreateTrainingTrainingTagPayloadToJSON,
} from '../models/index';

export interface CreateTrainingTrainingTagRequest {
    trainingId: string;
    request: MwTrainingBffInternalSchemasCreateTrainingTrainingTagPayload;
}

export interface DeleteTrainingTrainingTagRequest {
    trainingId: string;
    trainingTagId: string;
}

/**
 * 
 */
export class TrainingTrainingTagApi extends runtime.BaseAPI {

    /**
     * Create training training tag
     */
    async createTrainingTrainingTagRaw(requestParameters: CreateTrainingTrainingTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling createTrainingTrainingTag.');
        }

        if (requestParameters.request === null || requestParameters.request === undefined) {
            throw new runtime.RequiredError('request','Required parameter requestParameters.request was null or undefined when calling createTrainingTrainingTag.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/trainingTrainingTags/{trainingId}`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MwTrainingBffInternalSchemasCreateTrainingTrainingTagPayloadToJSON(requestParameters.request),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create training training tag
     */
    async createTrainingTrainingTag(requestParameters: CreateTrainingTrainingTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createTrainingTrainingTagRaw(requestParameters, initOverrides);
    }

    /**
     * Delete training training tag
     */
    async deleteTrainingTrainingTagRaw(requestParameters: DeleteTrainingTrainingTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling deleteTrainingTrainingTag.');
        }

        if (requestParameters.trainingTagId === null || requestParameters.trainingTagId === undefined) {
            throw new runtime.RequiredError('trainingTagId','Required parameter requestParameters.trainingTagId was null or undefined when calling deleteTrainingTrainingTag.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/trainingTrainingTags/{trainingId}/trainingTag/{trainingTagId}`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))).replace(`{${"trainingTagId"}}`, encodeURIComponent(String(requestParameters.trainingTagId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete training training tag
     */
    async deleteTrainingTrainingTag(requestParameters: DeleteTrainingTrainingTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTrainingTrainingTagRaw(requestParameters, initOverrides);
    }

}
