// @ts-nocheck
/* eslint-disable */
/**
 * Masters way training-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MwTrainingBffInternalSchemasCreateTrainingTestRequest,
} from '../models/index';
import {
    MwTrainingBffInternalSchemasCreateTrainingTestRequestFromJSON,
    MwTrainingBffInternalSchemasCreateTrainingTestRequestToJSON,
} from '../models/index';

export interface TrainingTestPostRequest {
    request: MwTrainingBffInternalSchemasCreateTrainingTestRequest;
}

/**
 * 
 */
export class TrainingTestsApi extends runtime.BaseAPI {

    /**
     * Create TrainingTest
     * Create TrainingTest
     */
    async trainingTestPostRaw(requestParameters: TrainingTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.request === null || requestParameters.request === undefined) {
            throw new runtime.RequiredError('request','Required parameter requestParameters.request was null or undefined when calling trainingTestPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/trainingTest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MwTrainingBffInternalSchemasCreateTrainingTestRequestToJSON(requestParameters.request),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create TrainingTest
     * Create TrainingTest
     */
    async trainingTestPost(requestParameters: TrainingTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.trainingTestPostRaw(requestParameters, initOverrides);
    }

}
