/*
Masters way training-bff API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwTrainingBffInternalSchemasTrainingsAmount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwTrainingBffInternalSchemasTrainingsAmount{}

// MwTrainingBffInternalSchemasTrainingsAmount struct for MwTrainingBffInternalSchemasTrainingsAmount
type MwTrainingBffInternalSchemasTrainingsAmount struct {
	Favorite int32 `json:"favorite"`
	Mentor int32 `json:"mentor"`
	Owner int32 `json:"owner"`
	Student int32 `json:"student"`
}

type _MwTrainingBffInternalSchemasTrainingsAmount MwTrainingBffInternalSchemasTrainingsAmount

// NewMwTrainingBffInternalSchemasTrainingsAmount instantiates a new MwTrainingBffInternalSchemasTrainingsAmount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwTrainingBffInternalSchemasTrainingsAmount(favorite int32, mentor int32, owner int32, student int32) *MwTrainingBffInternalSchemasTrainingsAmount {
	this := MwTrainingBffInternalSchemasTrainingsAmount{}
	this.Favorite = favorite
	this.Mentor = mentor
	this.Owner = owner
	this.Student = student
	return &this
}

// NewMwTrainingBffInternalSchemasTrainingsAmountWithDefaults instantiates a new MwTrainingBffInternalSchemasTrainingsAmount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwTrainingBffInternalSchemasTrainingsAmountWithDefaults() *MwTrainingBffInternalSchemasTrainingsAmount {
	this := MwTrainingBffInternalSchemasTrainingsAmount{}
	return &this
}

// GetFavorite returns the Favorite field value
func (o *MwTrainingBffInternalSchemasTrainingsAmount) GetFavorite() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Favorite
}

// GetFavoriteOk returns a tuple with the Favorite field value
// and a boolean to check if the value has been set.
func (o *MwTrainingBffInternalSchemasTrainingsAmount) GetFavoriteOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Favorite, true
}

// SetFavorite sets field value
func (o *MwTrainingBffInternalSchemasTrainingsAmount) SetFavorite(v int32) {
	o.Favorite = v
}

// GetMentor returns the Mentor field value
func (o *MwTrainingBffInternalSchemasTrainingsAmount) GetMentor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Mentor
}

// GetMentorOk returns a tuple with the Mentor field value
// and a boolean to check if the value has been set.
func (o *MwTrainingBffInternalSchemasTrainingsAmount) GetMentorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mentor, true
}

// SetMentor sets field value
func (o *MwTrainingBffInternalSchemasTrainingsAmount) SetMentor(v int32) {
	o.Mentor = v
}

// GetOwner returns the Owner field value
func (o *MwTrainingBffInternalSchemasTrainingsAmount) GetOwner() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *MwTrainingBffInternalSchemasTrainingsAmount) GetOwnerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *MwTrainingBffInternalSchemasTrainingsAmount) SetOwner(v int32) {
	o.Owner = v
}

// GetStudent returns the Student field value
func (o *MwTrainingBffInternalSchemasTrainingsAmount) GetStudent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Student
}

// GetStudentOk returns a tuple with the Student field value
// and a boolean to check if the value has been set.
func (o *MwTrainingBffInternalSchemasTrainingsAmount) GetStudentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Student, true
}

// SetStudent sets field value
func (o *MwTrainingBffInternalSchemasTrainingsAmount) SetStudent(v int32) {
	o.Student = v
}

func (o MwTrainingBffInternalSchemasTrainingsAmount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwTrainingBffInternalSchemasTrainingsAmount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["favorite"] = o.Favorite
	toSerialize["mentor"] = o.Mentor
	toSerialize["owner"] = o.Owner
	toSerialize["student"] = o.Student
	return toSerialize, nil
}

func (o *MwTrainingBffInternalSchemasTrainingsAmount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"favorite",
		"mentor",
		"owner",
		"student",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwTrainingBffInternalSchemasTrainingsAmount := _MwTrainingBffInternalSchemasTrainingsAmount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwTrainingBffInternalSchemasTrainingsAmount)

	if err != nil {
		return err
	}

	*o = MwTrainingBffInternalSchemasTrainingsAmount(varMwTrainingBffInternalSchemasTrainingsAmount)

	return err
}

type NullableMwTrainingBffInternalSchemasTrainingsAmount struct {
	value *MwTrainingBffInternalSchemasTrainingsAmount
	isSet bool
}

func (v NullableMwTrainingBffInternalSchemasTrainingsAmount) Get() *MwTrainingBffInternalSchemasTrainingsAmount {
	return v.value
}

func (v *NullableMwTrainingBffInternalSchemasTrainingsAmount) Set(val *MwTrainingBffInternalSchemasTrainingsAmount) {
	v.value = val
	v.isSet = true
}

func (v NullableMwTrainingBffInternalSchemasTrainingsAmount) IsSet() bool {
	return v.isSet
}

func (v *NullableMwTrainingBffInternalSchemasTrainingsAmount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwTrainingBffInternalSchemasTrainingsAmount(val *MwTrainingBffInternalSchemasTrainingsAmount) *NullableMwTrainingBffInternalSchemasTrainingsAmount {
	return &NullableMwTrainingBffInternalSchemasTrainingsAmount{value: val, isSet: true}
}

func (v NullableMwTrainingBffInternalSchemasTrainingsAmount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwTrainingBffInternalSchemasTrainingsAmount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


