/*
Masters way training-bff API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwTrainingBffInternalSchemasCreateTopicsPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwTrainingBffInternalSchemasCreateTopicsPayload{}

// MwTrainingBffInternalSchemasCreateTopicsPayload struct for MwTrainingBffInternalSchemasCreateTopicsPayload
type MwTrainingBffInternalSchemasCreateTopicsPayload struct {
	TopicsPayload []MwTrainingBffInternalSchemasCreateTopicPayload `json:"topicsPayload"`
}

type _MwTrainingBffInternalSchemasCreateTopicsPayload MwTrainingBffInternalSchemasCreateTopicsPayload

// NewMwTrainingBffInternalSchemasCreateTopicsPayload instantiates a new MwTrainingBffInternalSchemasCreateTopicsPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwTrainingBffInternalSchemasCreateTopicsPayload(topicsPayload []MwTrainingBffInternalSchemasCreateTopicPayload) *MwTrainingBffInternalSchemasCreateTopicsPayload {
	this := MwTrainingBffInternalSchemasCreateTopicsPayload{}
	this.TopicsPayload = topicsPayload
	return &this
}

// NewMwTrainingBffInternalSchemasCreateTopicsPayloadWithDefaults instantiates a new MwTrainingBffInternalSchemasCreateTopicsPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwTrainingBffInternalSchemasCreateTopicsPayloadWithDefaults() *MwTrainingBffInternalSchemasCreateTopicsPayload {
	this := MwTrainingBffInternalSchemasCreateTopicsPayload{}
	return &this
}

// GetTopicsPayload returns the TopicsPayload field value
func (o *MwTrainingBffInternalSchemasCreateTopicsPayload) GetTopicsPayload() []MwTrainingBffInternalSchemasCreateTopicPayload {
	if o == nil {
		var ret []MwTrainingBffInternalSchemasCreateTopicPayload
		return ret
	}

	return o.TopicsPayload
}

// GetTopicsPayloadOk returns a tuple with the TopicsPayload field value
// and a boolean to check if the value has been set.
func (o *MwTrainingBffInternalSchemasCreateTopicsPayload) GetTopicsPayloadOk() ([]MwTrainingBffInternalSchemasCreateTopicPayload, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopicsPayload, true
}

// SetTopicsPayload sets field value
func (o *MwTrainingBffInternalSchemasCreateTopicsPayload) SetTopicsPayload(v []MwTrainingBffInternalSchemasCreateTopicPayload) {
	o.TopicsPayload = v
}

func (o MwTrainingBffInternalSchemasCreateTopicsPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwTrainingBffInternalSchemasCreateTopicsPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["topicsPayload"] = o.TopicsPayload
	return toSerialize, nil
}

func (o *MwTrainingBffInternalSchemasCreateTopicsPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"topicsPayload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwTrainingBffInternalSchemasCreateTopicsPayload := _MwTrainingBffInternalSchemasCreateTopicsPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwTrainingBffInternalSchemasCreateTopicsPayload)

	if err != nil {
		return err
	}

	*o = MwTrainingBffInternalSchemasCreateTopicsPayload(varMwTrainingBffInternalSchemasCreateTopicsPayload)

	return err
}

type NullableMwTrainingBffInternalSchemasCreateTopicsPayload struct {
	value *MwTrainingBffInternalSchemasCreateTopicsPayload
	isSet bool
}

func (v NullableMwTrainingBffInternalSchemasCreateTopicsPayload) Get() *MwTrainingBffInternalSchemasCreateTopicsPayload {
	return v.value
}

func (v *NullableMwTrainingBffInternalSchemasCreateTopicsPayload) Set(val *MwTrainingBffInternalSchemasCreateTopicsPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwTrainingBffInternalSchemasCreateTopicsPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwTrainingBffInternalSchemasCreateTopicsPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwTrainingBffInternalSchemasCreateTopicsPayload(val *MwTrainingBffInternalSchemasCreateTopicsPayload) *NullableMwTrainingBffInternalSchemasCreateTopicsPayload {
	return &NullableMwTrainingBffInternalSchemasCreateTopicsPayload{value: val, isSet: true}
}

func (v NullableMwTrainingBffInternalSchemasCreateTopicsPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwTrainingBffInternalSchemasCreateTopicsPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


