import {MwGeneralBffInternalSchemasMetricResponse} from "src/apiAutogenerated/general";
import {Metric} from "src/model/businessModel/Metric";

/**
 * Convert {@link metric} to {@link SchemasMetricResponse}
 */
export const metricToMetricDTO = (metric: Metric): MwGeneralBffInternalSchemasMetricResponse => {
  const metricDTO: MwGeneralBffInternalSchemasMetricResponse = {
    ...metric,
    parentUuid: metric.parentUuid,
    estimationTime: 0,
    doneDate: metric.doneDate?.toISOString() ?? null,
  };

  return metricDTO;
};
