/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwServerInternalSchemasAIGenerateQuestionsForTestPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwServerInternalSchemasAIGenerateQuestionsForTestPayload{}

// MwServerInternalSchemasAIGenerateQuestionsForTestPayload struct for MwServerInternalSchemasAIGenerateQuestionsForTestPayload
type MwServerInternalSchemasAIGenerateQuestionsForTestPayload struct {
	GenerateAmount int32
	Language string
	Questions []string
	TestDescription string
	TestName string
}

type _MwServerInternalSchemasAIGenerateQuestionsForTestPayload MwServerInternalSchemasAIGenerateQuestionsForTestPayload

// NewMwServerInternalSchemasAIGenerateQuestionsForTestPayload instantiates a new MwServerInternalSchemasAIGenerateQuestionsForTestPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwServerInternalSchemasAIGenerateQuestionsForTestPayload(generateAmount int32, language string, questions []string, testDescription string, testName string) *MwServerInternalSchemasAIGenerateQuestionsForTestPayload {
	this := MwServerInternalSchemasAIGenerateQuestionsForTestPayload{}
	this.GenerateAmount = generateAmount
	this.Language = language
	this.Questions = questions
	this.TestDescription = testDescription
	this.TestName = testName
	return &this
}

// NewMwServerInternalSchemasAIGenerateQuestionsForTestPayloadWithDefaults instantiates a new MwServerInternalSchemasAIGenerateQuestionsForTestPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwServerInternalSchemasAIGenerateQuestionsForTestPayloadWithDefaults() *MwServerInternalSchemasAIGenerateQuestionsForTestPayload {
	this := MwServerInternalSchemasAIGenerateQuestionsForTestPayload{}
	return &this
}

// GetGenerateAmount returns the GenerateAmount field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetGenerateAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GenerateAmount
}

// GetGenerateAmountOk returns a tuple with the GenerateAmount field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetGenerateAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GenerateAmount, true
}

// SetGenerateAmount sets field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) SetGenerateAmount(v int32) {
	o.GenerateAmount = v
}

// GetLanguage returns the Language field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) SetLanguage(v string) {
	o.Language = v
}

// GetQuestions returns the Questions field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetQuestions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Questions
}

// GetQuestionsOk returns a tuple with the Questions field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetQuestionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Questions, true
}

// SetQuestions sets field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) SetQuestions(v []string) {
	o.Questions = v
}

// GetTestDescription returns the TestDescription field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetTestDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TestDescription
}

// GetTestDescriptionOk returns a tuple with the TestDescription field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetTestDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TestDescription, true
}

// SetTestDescription sets field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) SetTestDescription(v string) {
	o.TestDescription = v
}

// GetTestName returns the TestName field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetTestName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TestName
}

// GetTestNameOk returns a tuple with the TestName field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) GetTestNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TestName, true
}

// SetTestName sets field value
func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) SetTestName(v string) {
	o.TestName = v
}

func (o MwServerInternalSchemasAIGenerateQuestionsForTestPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwServerInternalSchemasAIGenerateQuestionsForTestPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["generateAmount"] = o.GenerateAmount
	toSerialize["language"] = o.Language
	toSerialize["questions"] = o.Questions
	toSerialize["testDescription"] = o.TestDescription
	toSerialize["testName"] = o.TestName
	return toSerialize, nil
}

func (o *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"generateAmount",
		"language",
		"questions",
		"testDescription",
		"testName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwServerInternalSchemasAIGenerateQuestionsForTestPayload := _MwServerInternalSchemasAIGenerateQuestionsForTestPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwServerInternalSchemasAIGenerateQuestionsForTestPayload)

	if err != nil {
		return err
	}

	*o = MwServerInternalSchemasAIGenerateQuestionsForTestPayload(varMwServerInternalSchemasAIGenerateQuestionsForTestPayload)

	return err
}

type NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload struct {
	value *MwServerInternalSchemasAIGenerateQuestionsForTestPayload
	isSet bool
}

func (v NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload) Get() *MwServerInternalSchemasAIGenerateQuestionsForTestPayload {
	return v.value
}

func (v *NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload) Set(val *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload(val *MwServerInternalSchemasAIGenerateQuestionsForTestPayload) *NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload {
	return &NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload{value: val, isSet: true}
}

func (v NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwServerInternalSchemasAIGenerateQuestionsForTestPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


