/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwServerInternalSchemasUserPlainResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwServerInternalSchemasUserPlainResponse{}

// MwServerInternalSchemasUserPlainResponse struct for MwServerInternalSchemasUserPlainResponse
type MwServerInternalSchemasUserPlainResponse struct {
	CreatedAt string
	Description string
	Email string
	ImageUrl string
	IsMentor bool
	Name string
	Uuid string
}

type _MwServerInternalSchemasUserPlainResponse MwServerInternalSchemasUserPlainResponse

// NewMwServerInternalSchemasUserPlainResponse instantiates a new MwServerInternalSchemasUserPlainResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwServerInternalSchemasUserPlainResponse(createdAt string, description string, email string, imageUrl string, isMentor bool, name string, uuid string) *MwServerInternalSchemasUserPlainResponse {
	this := MwServerInternalSchemasUserPlainResponse{}
	this.CreatedAt = createdAt
	this.Description = description
	this.Email = email
	this.ImageUrl = imageUrl
	this.IsMentor = isMentor
	this.Name = name
	this.Uuid = uuid
	return &this
}

// NewMwServerInternalSchemasUserPlainResponseWithDefaults instantiates a new MwServerInternalSchemasUserPlainResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwServerInternalSchemasUserPlainResponseWithDefaults() *MwServerInternalSchemasUserPlainResponse {
	this := MwServerInternalSchemasUserPlainResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *MwServerInternalSchemasUserPlainResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasUserPlainResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *MwServerInternalSchemasUserPlainResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetDescription returns the Description field value
func (o *MwServerInternalSchemasUserPlainResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasUserPlainResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *MwServerInternalSchemasUserPlainResponse) SetDescription(v string) {
	o.Description = v
}

// GetEmail returns the Email field value
func (o *MwServerInternalSchemasUserPlainResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasUserPlainResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *MwServerInternalSchemasUserPlainResponse) SetEmail(v string) {
	o.Email = v
}

// GetImageUrl returns the ImageUrl field value
func (o *MwServerInternalSchemasUserPlainResponse) GetImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasUserPlainResponse) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageUrl, true
}

// SetImageUrl sets field value
func (o *MwServerInternalSchemasUserPlainResponse) SetImageUrl(v string) {
	o.ImageUrl = v
}

// GetIsMentor returns the IsMentor field value
func (o *MwServerInternalSchemasUserPlainResponse) GetIsMentor() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMentor
}

// GetIsMentorOk returns a tuple with the IsMentor field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasUserPlainResponse) GetIsMentorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMentor, true
}

// SetIsMentor sets field value
func (o *MwServerInternalSchemasUserPlainResponse) SetIsMentor(v bool) {
	o.IsMentor = v
}

// GetName returns the Name field value
func (o *MwServerInternalSchemasUserPlainResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasUserPlainResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MwServerInternalSchemasUserPlainResponse) SetName(v string) {
	o.Name = v
}

// GetUuid returns the Uuid field value
func (o *MwServerInternalSchemasUserPlainResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *MwServerInternalSchemasUserPlainResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *MwServerInternalSchemasUserPlainResponse) SetUuid(v string) {
	o.Uuid = v
}

func (o MwServerInternalSchemasUserPlainResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwServerInternalSchemasUserPlainResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["description"] = o.Description
	toSerialize["email"] = o.Email
	toSerialize["imageUrl"] = o.ImageUrl
	toSerialize["isMentor"] = o.IsMentor
	toSerialize["name"] = o.Name
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *MwServerInternalSchemasUserPlainResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"description",
		"email",
		"imageUrl",
		"isMentor",
		"name",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwServerInternalSchemasUserPlainResponse := _MwServerInternalSchemasUserPlainResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwServerInternalSchemasUserPlainResponse)

	if err != nil {
		return err
	}

	*o = MwServerInternalSchemasUserPlainResponse(varMwServerInternalSchemasUserPlainResponse)

	return err
}

type NullableMwServerInternalSchemasUserPlainResponse struct {
	value *MwServerInternalSchemasUserPlainResponse
	isSet bool
}

func (v NullableMwServerInternalSchemasUserPlainResponse) Get() *MwServerInternalSchemasUserPlainResponse {
	return v.value
}

func (v *NullableMwServerInternalSchemasUserPlainResponse) Set(val *MwServerInternalSchemasUserPlainResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMwServerInternalSchemasUserPlainResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMwServerInternalSchemasUserPlainResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwServerInternalSchemasUserPlainResponse(val *MwServerInternalSchemasUserPlainResponse) *NullableMwServerInternalSchemasUserPlainResponse {
	return &NullableMwServerInternalSchemasUserPlainResponse{value: val, isSet: true}
}

func (v NullableMwServerInternalSchemasUserPlainResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwServerInternalSchemasUserPlainResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


