package facades

import (
	"context"
	openapiGeneral "mw-general-bff/apiAutogenerated/general"
	"mw-general-bff/internal/schemas"
	"mw-general-bff/internal/services"

	"github.com/gin-gonic/gin"
)

type WayFacade struct {
	generalService *services.GeneralService
}

func newWayFacade(generalService *services.GeneralService) *WayFacade {
	return &WayFacade{generalService}
}

func (wf *WayFacade) CreateWay(ctx context.Context, payload *schemas.CreateWayPayload) (*openapiGeneral.MwServerInternalSchemasWayPlainResponse, error) {
	return wf.generalService.CreateWay(ctx, payload)
}

func (wf *WayFacade) UpdateWay(ctx context.Context, params *services.UpdateWayParams) (*openapiGeneral.MwServerInternalSchemasWayPlainResponse, error) {
	return wf.generalService.UpdateWay(ctx, params)
}

func (wf *WayFacade) GetWayById(ctx context.Context, wayUUID string) (*openapiGeneral.MwServerInternalSchemasWayPopulatedResponse, error) {
	return wf.generalService.GetWayById(ctx, wayUUID)
}

func (wf *WayFacade) GetAllWays(ctx context.Context, params *services.GetAllWaysParams) (*openapiGeneral.MwServerInternalSchemasGetAllWaysResponse, error) {
	return wf.generalService.GetAllWays(ctx, params)
}

func (wf *WayFacade) DeleteWayById(ctx *gin.Context, wayID string) error {
	return wf.generalService.DeleteWayById(ctx, wayID)
}

func (wf *WayFacade) GetWayStatisticsById(ctx context.Context, wayUUID string) (*openapiGeneral.MwServerInternalSchemasWayStatisticsTriplePeriod, error) {
	return wf.generalService.GetWayStatisticsById(ctx, wayUUID)
}
