/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MwserverInternalSchemasUpdateUserPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwserverInternalSchemasUpdateUserPayload{}

// MwserverInternalSchemasUpdateUserPayload struct for MwserverInternalSchemasUpdateUserPayload
type MwserverInternalSchemasUpdateUserPayload struct {
	Description *string
	ImageUrl *string
	IsMentor *bool
	Name *string
}

// NewMwserverInternalSchemasUpdateUserPayload instantiates a new MwserverInternalSchemasUpdateUserPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwserverInternalSchemasUpdateUserPayload() *MwserverInternalSchemasUpdateUserPayload {
	this := MwserverInternalSchemasUpdateUserPayload{}
	return &this
}

// NewMwserverInternalSchemasUpdateUserPayloadWithDefaults instantiates a new MwserverInternalSchemasUpdateUserPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwserverInternalSchemasUpdateUserPayloadWithDefaults() *MwserverInternalSchemasUpdateUserPayload {
	this := MwserverInternalSchemasUpdateUserPayload{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MwserverInternalSchemasUpdateUserPayload) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwserverInternalSchemasUpdateUserPayload) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MwserverInternalSchemasUpdateUserPayload) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MwserverInternalSchemasUpdateUserPayload) SetDescription(v string) {
	o.Description = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *MwserverInternalSchemasUpdateUserPayload) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwserverInternalSchemasUpdateUserPayload) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *MwserverInternalSchemasUpdateUserPayload) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *MwserverInternalSchemasUpdateUserPayload) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetIsMentor returns the IsMentor field value if set, zero value otherwise.
func (o *MwserverInternalSchemasUpdateUserPayload) GetIsMentor() bool {
	if o == nil || IsNil(o.IsMentor) {
		var ret bool
		return ret
	}
	return *o.IsMentor
}

// GetIsMentorOk returns a tuple with the IsMentor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwserverInternalSchemasUpdateUserPayload) GetIsMentorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMentor) {
		return nil, false
	}
	return o.IsMentor, true
}

// HasIsMentor returns a boolean if a field has been set.
func (o *MwserverInternalSchemasUpdateUserPayload) HasIsMentor() bool {
	if o != nil && !IsNil(o.IsMentor) {
		return true
	}

	return false
}

// SetIsMentor gets a reference to the given bool and assigns it to the IsMentor field.
func (o *MwserverInternalSchemasUpdateUserPayload) SetIsMentor(v bool) {
	o.IsMentor = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MwserverInternalSchemasUpdateUserPayload) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MwserverInternalSchemasUpdateUserPayload) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MwserverInternalSchemasUpdateUserPayload) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MwserverInternalSchemasUpdateUserPayload) SetName(v string) {
	o.Name = &v
}

func (o MwserverInternalSchemasUpdateUserPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwserverInternalSchemasUpdateUserPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["imageUrl"] = o.ImageUrl
	}
	if !IsNil(o.IsMentor) {
		toSerialize["isMentor"] = o.IsMentor
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableMwserverInternalSchemasUpdateUserPayload struct {
	value *MwserverInternalSchemasUpdateUserPayload
	isSet bool
}

func (v NullableMwserverInternalSchemasUpdateUserPayload) Get() *MwserverInternalSchemasUpdateUserPayload {
	return v.value
}

func (v *NullableMwserverInternalSchemasUpdateUserPayload) Set(val *MwserverInternalSchemasUpdateUserPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwserverInternalSchemasUpdateUserPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwserverInternalSchemasUpdateUserPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwserverInternalSchemasUpdateUserPayload(val *MwserverInternalSchemasUpdateUserPayload) *NullableMwserverInternalSchemasUpdateUserPayload {
	return &NullableMwserverInternalSchemasUpdateUserPayload{value: val, isSet: true}
}

func (v NullableMwserverInternalSchemasUpdateUserPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwserverInternalSchemasUpdateUserPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


