/*
Masters way general API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwserverInternalSchemasCreatePlanJobTagPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwserverInternalSchemasCreatePlanJobTagPayload{}

// MwserverInternalSchemasCreatePlanJobTagPayload struct for MwserverInternalSchemasCreatePlanJobTagPayload
type MwserverInternalSchemasCreatePlanJobTagPayload struct {
	JobTagUuid string
	PlanUuid string
}

type _MwserverInternalSchemasCreatePlanJobTagPayload MwserverInternalSchemasCreatePlanJobTagPayload

// NewMwserverInternalSchemasCreatePlanJobTagPayload instantiates a new MwserverInternalSchemasCreatePlanJobTagPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwserverInternalSchemasCreatePlanJobTagPayload(jobTagUuid string, planUuid string) *MwserverInternalSchemasCreatePlanJobTagPayload {
	this := MwserverInternalSchemasCreatePlanJobTagPayload{}
	this.JobTagUuid = jobTagUuid
	this.PlanUuid = planUuid
	return &this
}

// NewMwserverInternalSchemasCreatePlanJobTagPayloadWithDefaults instantiates a new MwserverInternalSchemasCreatePlanJobTagPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwserverInternalSchemasCreatePlanJobTagPayloadWithDefaults() *MwserverInternalSchemasCreatePlanJobTagPayload {
	this := MwserverInternalSchemasCreatePlanJobTagPayload{}
	return &this
}

// GetJobTagUuid returns the JobTagUuid field value
func (o *MwserverInternalSchemasCreatePlanJobTagPayload) GetJobTagUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobTagUuid
}

// GetJobTagUuidOk returns a tuple with the JobTagUuid field value
// and a boolean to check if the value has been set.
func (o *MwserverInternalSchemasCreatePlanJobTagPayload) GetJobTagUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobTagUuid, true
}

// SetJobTagUuid sets field value
func (o *MwserverInternalSchemasCreatePlanJobTagPayload) SetJobTagUuid(v string) {
	o.JobTagUuid = v
}

// GetPlanUuid returns the PlanUuid field value
func (o *MwserverInternalSchemasCreatePlanJobTagPayload) GetPlanUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanUuid
}

// GetPlanUuidOk returns a tuple with the PlanUuid field value
// and a boolean to check if the value has been set.
func (o *MwserverInternalSchemasCreatePlanJobTagPayload) GetPlanUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanUuid, true
}

// SetPlanUuid sets field value
func (o *MwserverInternalSchemasCreatePlanJobTagPayload) SetPlanUuid(v string) {
	o.PlanUuid = v
}

func (o MwserverInternalSchemasCreatePlanJobTagPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwserverInternalSchemasCreatePlanJobTagPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobTagUuid"] = o.JobTagUuid
	toSerialize["planUuid"] = o.PlanUuid
	return toSerialize, nil
}

func (o *MwserverInternalSchemasCreatePlanJobTagPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobTagUuid",
		"planUuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwserverInternalSchemasCreatePlanJobTagPayload := _MwserverInternalSchemasCreatePlanJobTagPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwserverInternalSchemasCreatePlanJobTagPayload)

	if err != nil {
		return err
	}

	*o = MwserverInternalSchemasCreatePlanJobTagPayload(varMwserverInternalSchemasCreatePlanJobTagPayload)

	return err
}

type NullableMwserverInternalSchemasCreatePlanJobTagPayload struct {
	value *MwserverInternalSchemasCreatePlanJobTagPayload
	isSet bool
}

func (v NullableMwserverInternalSchemasCreatePlanJobTagPayload) Get() *MwserverInternalSchemasCreatePlanJobTagPayload {
	return v.value
}

func (v *NullableMwserverInternalSchemasCreatePlanJobTagPayload) Set(val *MwserverInternalSchemasCreatePlanJobTagPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwserverInternalSchemasCreatePlanJobTagPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwserverInternalSchemasCreatePlanJobTagPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwserverInternalSchemasCreatePlanJobTagPayload(val *MwserverInternalSchemasCreatePlanJobTagPayload) *NullableMwserverInternalSchemasCreatePlanJobTagPayload {
	return &NullableMwserverInternalSchemasCreatePlanJobTagPayload{value: val, isSet: true}
}

func (v NullableMwserverInternalSchemasCreatePlanJobTagPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwserverInternalSchemasCreatePlanJobTagPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


