// @ts-nocheck
/* eslint-disable */
/**
 * Masters way API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SchemasCreateFormerMentorWayPayload,
} from '../models/index';
import {
    SchemasCreateFormerMentorWayPayloadFromJSON,
    SchemasCreateFormerMentorWayPayloadToJSON,
} from '../models/index';

export interface CreateFormerMentorWayRequest {
    request: SchemasCreateFormerMentorWayPayload;
}

/**
 * 
 */
export class FormerMentorWayApi extends runtime.BaseAPI {

    /**
     * Create a new formerMentorWay
     */
    async createFormerMentorWayRaw(requestParameters: CreateFormerMentorWayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.request === null || requestParameters.request === undefined) {
            throw new runtime.RequiredError('request','Required parameter requestParameters.request was null or undefined when calling createFormerMentorWay.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/formerMentorWayWays`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SchemasCreateFormerMentorWayPayloadToJSON(requestParameters.request),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new formerMentorWay
     */
    async createFormerMentorWay(requestParameters: CreateFormerMentorWayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createFormerMentorWayRaw(requestParameters, initOverrides);
    }

}
