package openapi

import (
	openapiChat "mw-chat-bff/apiAutogenerated/chat"
	openapiGeneral "mw-chat-bff/apiAutogenerated/general"
	openapiMWChatBFF "mw-chat-bff/apiAutogenerated/mw-chat-bff"
	openapiMWChatWebSocket "mw-chat-bff/apiAutogenerated/mw-chat-websocket"
	"mw-chat-bff/internal/auth"
	"mw-chat-bff/internal/config"
	"net/http"
)

type authTransport struct {
	rt http.RoundTripper
}

func (t *authTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	ctx := req.Context()
	if token, ok := ctx.Value(auth.ContextKeyAuthorization).(string); ok {
		req.Header.Set(auth.HeaderKeyAuthorization, token)
	}
	return t.rt.RoundTrip(req)
}

func MakeGeneralAPIClient(cfg *config.Config) *openapiGeneral.APIClient {
	generalAPIConfig := &openapiGeneral.Configuration{
		Host:   cfg.GeneralAPIHost,
		Scheme: "http",
		Servers: openapiGeneral.ServerConfigurations{
			{
				URL:         cfg.GeneralBaseURL,
				Description: "mw-general",
			},
		},
		HTTPClient: &http.Client{
			Transport: &authTransport{rt: http.DefaultTransport},
		},
	}
	return openapiGeneral.NewAPIClient(generalAPIConfig)
}

func MakeChatAPIClient(cfg *config.Config) *openapiChat.APIClient {
	chatAPIConfig := &openapiChat.Configuration{
		Host:   cfg.ChatAPIHost,
		Scheme: "http",
		Servers: openapiChat.ServerConfigurations{
			{
				URL:         cfg.ChatBaseURL,
				Description: "mw-chat",
			},
		},
		HTTPClient: &http.Client{
			Transport: &authTransport{rt: http.DefaultTransport},
		},
	}
	return openapiChat.NewAPIClient(chatAPIConfig)
}

func MakeMWChatWebSocketAPIClient(cfg *config.Config) *openapiMWChatWebSocket.APIClient {
	mwChatSocketAPIConfig := &openapiMWChatWebSocket.Configuration{
		Host:   cfg.MWChatWebSocketAPIHost,
		Scheme: "http",
		Servers: openapiMWChatWebSocket.ServerConfigurations{
			{
				URL:         cfg.MWChatWebSocketBaseURL,
				Description: "mw-chat-websocket",
			},
		},
		HTTPClient: &http.Client{
			Transport: &authTransport{rt: http.DefaultTransport},
		},
	}
	return openapiMWChatWebSocket.NewAPIClient(mwChatSocketAPIConfig)
}

func MakeChatBFFAPIClient(cfg *config.Config) *openapiMWChatBFF.APIClient {
	ChatBFFAPIConfig := &openapiMWChatBFF.Configuration{
		Host:   cfg.ChatBFFAPIHost,
		Scheme: "http",
		Servers: openapiMWChatBFF.ServerConfigurations{
			{
				URL:         cfg.ChatBFFBaseURL,
				Description: "mw-chat-bff",
			},
		},
		HTTPClient: &http.Client{
			Transport: &authTransport{rt: http.DefaultTransport},
		},
	}
	return openapiMWChatBFF.NewAPIClient(ChatBFFAPIConfig)
}
