#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

WEBAPP="mw-webapp/"
SERVER="mw-server/"

if git diff --name-only --cached | grep $FRONTEND;
  then
    echo "WEBAPP FOLDER CHANGED --> starting husky..."
    cd mw-webapp
    pnpm lint-staged
    pnpm concurrently \
        "pnpm web:type-check" \
        "pnpm web:test" \
        "pnpm web:build-storybook" \
        "pnpm web:build" \
        "pnpm web:cypress:component:run"
fi

if git diff --name-only --cached | grep $SERVER;
  then
    echo "SERVER FOLDER CHANGED --> starting husky..."
    cd mw-server
    go test -v ./...
fi

pnpm concurrently \
        "pnpm web:cypress:e2e:run"


