#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

WEBAPP="mw-webapp/"
SERVER="mw-server/"

if git diff --name-only --cached | grep $FRONTEND;
  then
    echo "WEBAPP FOLDER CHANGED --> starting husky..."
    cd mw-webapp
    pnpm lint-staged
    pnpm concurrently \
        "pnpm type-check:web" \
        "pnpm test:web" \
        "pnpm build-storybook:web" \
        "pnpm build:web" \
        "pnpm cypress:component:run:web"
fi

if git diff --name-only --cached | grep $SERVER;
  then
    echo "SERVER FOLDER CHANGED --> starting husky..."
    cd mw-server
    go test -v ./...
fi

pnpm concurrently \
        "pnpm cypress:e2e:run:web"


