// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MwGeneralBffInternalSchemasMetricResponse } from './MwGeneralBffInternalSchemasMetricResponse';
import {
    MwGeneralBffInternalSchemasMetricResponseFromJSON,
    MwGeneralBffInternalSchemasMetricResponseFromJSONTyped,
    MwGeneralBffInternalSchemasMetricResponseToJSON,
} from './MwGeneralBffInternalSchemasMetricResponse';

/**
 * 
 * @export
 * @interface MwGeneralBffInternalSchemasMetricTreeNode
 */
export interface MwGeneralBffInternalSchemasMetricTreeNode {
    /**
     * 
     * @type {Array<MwGeneralBffInternalSchemasMetricTreeNode>}
     * @memberof MwGeneralBffInternalSchemasMetricTreeNode
     */
    children: Array<MwGeneralBffInternalSchemasMetricTreeNode>;
    /**
     * 
     * @type {MwGeneralBffInternalSchemasMetricResponse}
     * @memberof MwGeneralBffInternalSchemasMetricTreeNode
     */
    metric: MwGeneralBffInternalSchemasMetricResponse;
}

/**
 * Check if a given object implements the MwGeneralBffInternalSchemasMetricTreeNode interface.
 */
export function instanceOfMwGeneralBffInternalSchemasMetricTreeNode(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "children" in value;
    isInstance = isInstance && "metric" in value;

    return isInstance;
}

export function MwGeneralBffInternalSchemasMetricTreeNodeFromJSON(json: any): MwGeneralBffInternalSchemasMetricTreeNode {
    return MwGeneralBffInternalSchemasMetricTreeNodeFromJSONTyped(json, false);
}

export function MwGeneralBffInternalSchemasMetricTreeNodeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwGeneralBffInternalSchemasMetricTreeNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'children': ((json['children'] as Array<any>).map(MwGeneralBffInternalSchemasMetricTreeNodeFromJSON)),
        'metric': MwGeneralBffInternalSchemasMetricResponseFromJSON(json['metric']),
    };
}


export function MwGeneralBffInternalSchemasMetricTreeNodeToJSON(value?: MwGeneralBffInternalSchemasMetricTreeNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'children': ((value.children as Array<any>).map(MwGeneralBffInternalSchemasMetricTreeNodeToJSON)),
        'metric': MwGeneralBffInternalSchemasMetricResponseToJSON(value.metric),
    };
}

