// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload
 */
export interface MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload {
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload
     */
    companionLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload
     */
    jobTagUuids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload
     */
    ownerUuid: string;
    /**
     * 
     * @type {number}
     * @memberof MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload
     */
    time: number;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload
     */
    wayUuid: string;
}

/**
 * Check if a given object implements the MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload interface.
 */
export function instanceOfMwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "ownerUuid" in value;
    isInstance = isInstance && "time" in value;
    isInstance = isInstance && "wayUuid" in value;

    return isInstance;
}

export function MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayloadFromJSON(json: any): MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload {
    return MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayloadFromJSONTyped(json, false);
}

export function MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companionLanguage': !exists(json, 'companionLanguage') ? undefined : json['companionLanguage'],
        'description': json['description'],
        'jobTagUuids': !exists(json, 'jobTagUuids') ? undefined : json['jobTagUuids'],
        'ownerUuid': json['ownerUuid'],
        'time': json['time'],
        'wayUuid': json['wayUuid'],
    };
}


export function MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayloadToJSON(value?: MwGeneralBffInternalSchemasCreateJobDoneForTelegramPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'companionLanguage': value.companionLanguage,
        'description': value.description,
        'jobTagUuids': value.jobTagUuids,
        'ownerUuid': value.ownerUuid,
        'time': value.time,
        'wayUuid': value.wayUuid,
    };
}

