// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwGeneralBffInternalSchemasUpdateJobTagPayload
 */
export interface MwGeneralBffInternalSchemasUpdateJobTagPayload {
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasUpdateJobTagPayload
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasUpdateJobTagPayload
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasUpdateJobTagPayload
     */
    name?: string;
}

/**
 * Check if a given object implements the MwGeneralBffInternalSchemasUpdateJobTagPayload interface.
 */
export function instanceOfMwGeneralBffInternalSchemasUpdateJobTagPayload(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function MwGeneralBffInternalSchemasUpdateJobTagPayloadFromJSON(json: any): MwGeneralBffInternalSchemasUpdateJobTagPayload {
    return MwGeneralBffInternalSchemasUpdateJobTagPayloadFromJSONTyped(json, false);
}

export function MwGeneralBffInternalSchemasUpdateJobTagPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwGeneralBffInternalSchemasUpdateJobTagPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': !exists(json, 'color') ? undefined : json['color'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}


export function MwGeneralBffInternalSchemasUpdateJobTagPayloadToJSON(value?: MwGeneralBffInternalSchemasUpdateJobTagPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': value.color,
        'description': value.description,
        'name': value.name,
    };
}

