// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwGeneralBffInternalSchemasProfileSetting
 */
export interface MwGeneralBffInternalSchemasProfileSetting {
    /**
     * 
     * @type {number}
     * @memberof MwGeneralBffInternalSchemasProfileSetting
     */
    coins: number;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasProfileSetting
     */
    expirationDate: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasProfileSetting
     */
    pricingPlan: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasProfileSetting
     */
    uuid: string;
}

/**
 * Check if a given object implements the MwGeneralBffInternalSchemasProfileSetting interface.
 */
export function instanceOfMwGeneralBffInternalSchemasProfileSetting(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "coins" in value;
    isInstance = isInstance && "expirationDate" in value;
    isInstance = isInstance && "pricingPlan" in value;
    isInstance = isInstance && "uuid" in value;

    return isInstance;
}

export function MwGeneralBffInternalSchemasProfileSettingFromJSON(json: any): MwGeneralBffInternalSchemasProfileSetting {
    return MwGeneralBffInternalSchemasProfileSettingFromJSONTyped(json, false);
}

export function MwGeneralBffInternalSchemasProfileSettingFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwGeneralBffInternalSchemasProfileSetting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coins': json['coins'],
        'expirationDate': json['expirationDate'],
        'pricingPlan': json['pricingPlan'],
        'uuid': json['uuid'],
    };
}


export function MwGeneralBffInternalSchemasProfileSettingToJSON(value?: MwGeneralBffInternalSchemasProfileSetting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coins': value.coins,
        'expirationDate': value.expirationDate,
        'pricingPlan': value.pricingPlan,
        'uuid': value.uuid,
    };
}

