// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwGeneralBffInternalSchemasCreateFavoriteUserPayload
 */
export interface MwGeneralBffInternalSchemasCreateFavoriteUserPayload {
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCreateFavoriteUserPayload
     */
    acceptorUserUuid: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCreateFavoriteUserPayload
     */
    donorUserUuid: string;
}

/**
 * Check if a given object implements the MwGeneralBffInternalSchemasCreateFavoriteUserPayload interface.
 */
export function instanceOfMwGeneralBffInternalSchemasCreateFavoriteUserPayload(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "acceptorUserUuid" in value;
    isInstance = isInstance && "donorUserUuid" in value;

    return isInstance;
}

export function MwGeneralBffInternalSchemasCreateFavoriteUserPayloadFromJSON(json: any): MwGeneralBffInternalSchemasCreateFavoriteUserPayload {
    return MwGeneralBffInternalSchemasCreateFavoriteUserPayloadFromJSONTyped(json, false);
}

export function MwGeneralBffInternalSchemasCreateFavoriteUserPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwGeneralBffInternalSchemasCreateFavoriteUserPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'acceptorUserUuid': json['acceptorUserUuid'],
        'donorUserUuid': json['donorUserUuid'],
    };
}


export function MwGeneralBffInternalSchemasCreateFavoriteUserPayloadToJSON(value?: MwGeneralBffInternalSchemasCreateFavoriteUserPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'acceptorUserUuid': value.acceptorUserUuid,
        'donorUserUuid': value.donorUserUuid,
    };
}

