// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MwGeneralBffInternalSchemasCompanionCharacter } from './MwGeneralBffInternalSchemasCompanionCharacter';
import {
    MwGeneralBffInternalSchemasCompanionCharacterFromJSON,
    MwGeneralBffInternalSchemasCompanionCharacterFromJSONTyped,
    MwGeneralBffInternalSchemasCompanionCharacterToJSON,
} from './MwGeneralBffInternalSchemasCompanionCharacter';

/**
 * 
 * @export
 * @interface MwGeneralBffInternalSchemasCompanionFeedbackResponse
 */
export interface MwGeneralBffInternalSchemasCompanionFeedbackResponse {
    /**
     * 
     * @type {MwGeneralBffInternalSchemasCompanionCharacter}
     * @memberof MwGeneralBffInternalSchemasCompanionFeedbackResponse
     */
    character: MwGeneralBffInternalSchemasCompanionCharacter;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCompanionFeedbackResponse
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCompanionFeedbackResponse
     */
    lastUpdatedAt: string;
    /**
     * 
     * @type {number}
     * @memberof MwGeneralBffInternalSchemasCompanionFeedbackResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCompanionFeedbackResponse
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasCompanionFeedbackResponse
     */
    wayUuid: string;
}



/**
 * Check if a given object implements the MwGeneralBffInternalSchemasCompanionFeedbackResponse interface.
 */
export function instanceOfMwGeneralBffInternalSchemasCompanionFeedbackResponse(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "character" in value;
    isInstance = isInstance && "comment" in value;
    isInstance = isInstance && "lastUpdatedAt" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "wayUuid" in value;

    return isInstance;
}

export function MwGeneralBffInternalSchemasCompanionFeedbackResponseFromJSON(json: any): MwGeneralBffInternalSchemasCompanionFeedbackResponse {
    return MwGeneralBffInternalSchemasCompanionFeedbackResponseFromJSONTyped(json, false);
}

export function MwGeneralBffInternalSchemasCompanionFeedbackResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwGeneralBffInternalSchemasCompanionFeedbackResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'character': MwGeneralBffInternalSchemasCompanionCharacterFromJSON(json['character']),
        'comment': json['comment'],
        'lastUpdatedAt': json['lastUpdatedAt'],
        'status': json['status'],
        'uuid': json['uuid'],
        'wayUuid': json['wayUuid'],
    };
}


export function MwGeneralBffInternalSchemasCompanionFeedbackResponseToJSON(value?: MwGeneralBffInternalSchemasCompanionFeedbackResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'character': MwGeneralBffInternalSchemasCompanionCharacterToJSON(value.character),
        'comment': value.comment,
        'lastUpdatedAt': value.lastUpdatedAt,
        'status': value.status,
        'uuid': value.uuid,
        'wayUuid': value.wayUuid,
    };
}

