// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general-bff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwGeneralBffInternalSchemasNotificationResponse
 */
export interface MwGeneralBffInternalSchemasNotificationResponse {
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasNotificationResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasNotificationResponse
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof MwGeneralBffInternalSchemasNotificationResponse
     */
    isRead: boolean;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasNotificationResponse
     */
    nature: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasNotificationResponse
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasNotificationResponse
     */
    userUuid: string;
    /**
     * 
     * @type {string}
     * @memberof MwGeneralBffInternalSchemasNotificationResponse
     */
    uuid: string;
}

/**
 * Check if a given object implements the MwGeneralBffInternalSchemasNotificationResponse interface.
 */
export function instanceOfMwGeneralBffInternalSchemasNotificationResponse(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "isRead" in value;
    isInstance = isInstance && "nature" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "userUuid" in value;
    isInstance = isInstance && "uuid" in value;

    return isInstance;
}

export function MwGeneralBffInternalSchemasNotificationResponseFromJSON(json: any): MwGeneralBffInternalSchemasNotificationResponse {
    return MwGeneralBffInternalSchemasNotificationResponseFromJSONTyped(json, false);
}

export function MwGeneralBffInternalSchemasNotificationResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwGeneralBffInternalSchemasNotificationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'description': json['description'],
        'isRead': json['isRead'],
        'nature': json['nature'],
        'url': json['url'],
        'userUuid': json['userUuid'],
        'uuid': json['uuid'],
    };
}


export function MwGeneralBffInternalSchemasNotificationResponseToJSON(value?: MwGeneralBffInternalSchemasNotificationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'description': value.description,
        'isRead': value.isRead,
        'nature': value.nature,
        'url': value.url,
        'userUuid': value.userUuid,
        'uuid': value.uuid,
    };
}

