// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwServerInternalSchemasAICommentIssueResponse
 */
export interface MwServerInternalSchemasAICommentIssueResponse {
    /**
     * 
     * @type {string}
     * @memberof MwServerInternalSchemasAICommentIssueResponse
     */
    goal: string;
}

/**
 * Check if a given object implements the MwServerInternalSchemasAICommentIssueResponse interface.
 */
export function instanceOfMwServerInternalSchemasAICommentIssueResponse(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "goal" in value;

    return isInstance;
}

export function MwServerInternalSchemasAICommentIssueResponseFromJSON(json: any): MwServerInternalSchemasAICommentIssueResponse {
    return MwServerInternalSchemasAICommentIssueResponseFromJSONTyped(json, false);
}

export function MwServerInternalSchemasAICommentIssueResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwServerInternalSchemasAICommentIssueResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'goal': json['goal'],
    };
}


export function MwServerInternalSchemasAICommentIssueResponseToJSON(value?: MwServerInternalSchemasAICommentIssueResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'goal': value.goal,
    };
}

