// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwServerInternalSchemasUpdateWayCollectionPayload
 */
export interface MwServerInternalSchemasUpdateWayCollectionPayload {
    /**
     * 
     * @type {string}
     * @memberof MwServerInternalSchemasUpdateWayCollectionPayload
     */
    name?: string;
}

/**
 * Check if a given object implements the MwServerInternalSchemasUpdateWayCollectionPayload interface.
 */
export function instanceOfMwServerInternalSchemasUpdateWayCollectionPayload(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function MwServerInternalSchemasUpdateWayCollectionPayloadFromJSON(json: any): MwServerInternalSchemasUpdateWayCollectionPayload {
    return MwServerInternalSchemasUpdateWayCollectionPayloadFromJSONTyped(json, false);
}

export function MwServerInternalSchemasUpdateWayCollectionPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwServerInternalSchemasUpdateWayCollectionPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}


export function MwServerInternalSchemasUpdateWayCollectionPayloadToJSON(value?: MwServerInternalSchemasUpdateWayCollectionPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

