// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwserverInternalSchemasWayCollectionWayResponse
 */
export interface MwserverInternalSchemasWayCollectionWayResponse {
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasWayCollectionWayResponse
     */
    wayCollectionId: string;
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasWayCollectionWayResponse
     */
    wayId: string;
}

/**
 * Check if a given object implements the MwserverInternalSchemasWayCollectionWayResponse interface.
 */
export function instanceOfMwserverInternalSchemasWayCollectionWayResponse(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "wayCollectionId" in value;
    isInstance = isInstance && "wayId" in value;

    return isInstance;
}

export function MwserverInternalSchemasWayCollectionWayResponseFromJSON(json: any): MwserverInternalSchemasWayCollectionWayResponse {
    return MwserverInternalSchemasWayCollectionWayResponseFromJSONTyped(json, false);
}

export function MwserverInternalSchemasWayCollectionWayResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwserverInternalSchemasWayCollectionWayResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wayCollectionId': json['wayCollectionId'],
        'wayId': json['wayId'],
    };
}


export function MwserverInternalSchemasWayCollectionWayResponseToJSON(value?: MwserverInternalSchemasWayCollectionWayResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wayCollectionId': value.wayCollectionId,
        'wayId': value.wayId,
    };
}

