// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwserverInternalSchemasUpdateUserPayload
 */
export interface MwserverInternalSchemasUpdateUserPayload {
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasUpdateUserPayload
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasUpdateUserPayload
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MwserverInternalSchemasUpdateUserPayload
     */
    isMentor?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasUpdateUserPayload
     */
    name?: string;
}

/**
 * Check if a given object implements the MwserverInternalSchemasUpdateUserPayload interface.
 */
export function instanceOfMwserverInternalSchemasUpdateUserPayload(
    value: object
): boolean {
    let isInstance = true;

    return isInstance;
}

export function MwserverInternalSchemasUpdateUserPayloadFromJSON(json: any): MwserverInternalSchemasUpdateUserPayload {
    return MwserverInternalSchemasUpdateUserPayloadFromJSONTyped(json, false);
}

export function MwserverInternalSchemasUpdateUserPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwserverInternalSchemasUpdateUserPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'isMentor': !exists(json, 'isMentor') ? undefined : json['isMentor'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}


export function MwserverInternalSchemasUpdateUserPayloadToJSON(value?: MwserverInternalSchemasUpdateUserPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'imageUrl': value.imageUrl,
        'isMentor': value.isMentor,
        'name': value.name,
    };
}

