// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MwserverInternalSchemasLabel
 */
export interface MwserverInternalSchemasLabel {
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasLabel
     */
    color: string;
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasLabel
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasLabel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MwserverInternalSchemasLabel
     */
    uuid: string;
}

/**
 * Check if a given object implements the MwserverInternalSchemasLabel interface.
 */
export function instanceOfMwserverInternalSchemasLabel(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "color" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "uuid" in value;

    return isInstance;
}

export function MwserverInternalSchemasLabelFromJSON(json: any): MwserverInternalSchemasLabel {
    return MwserverInternalSchemasLabelFromJSONTyped(json, false);
}

export function MwserverInternalSchemasLabelFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MwserverInternalSchemasLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': json['color'],
        'description': json['description'],
        'name': json['name'],
        'uuid': json['uuid'],
    };
}


export function MwserverInternalSchemasLabelToJSON(value?: MwserverInternalSchemasLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': value.color,
        'description': value.description,
        'name': value.name,
        'uuid': value.uuid,
    };
}

