// @ts-nocheck
/* eslint-disable */
/**
 * Masters way general API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemasCreateJobDoneLabelPayload
 */
export interface SchemasCreateJobDoneLabelPayload {
    /**
     * 
     * @type {string}
     * @memberof SchemasCreateJobDoneLabelPayload
     */
    jobDoneUuid: string;
    /**
     * 
     * @type {string}
     * @memberof SchemasCreateJobDoneLabelPayload
     */
    labelUuid: string;
}

/**
 * Check if a given object implements the SchemasCreateJobDoneLabelPayload interface.
 */
export function instanceOfSchemasCreateJobDoneLabelPayload(
    value: object
): boolean {
    let isInstance = true;
    isInstance = isInstance && "jobDoneUuid" in value;
    isInstance = isInstance && "labelUuid" in value;

    return isInstance;
}

export function SchemasCreateJobDoneLabelPayloadFromJSON(json: any): SchemasCreateJobDoneLabelPayload {
    return SchemasCreateJobDoneLabelPayloadFromJSONTyped(json, false);
}

export function SchemasCreateJobDoneLabelPayloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SchemasCreateJobDoneLabelPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobDoneUuid': json['jobDoneUuid'],
        'labelUuid': json['labelUuid'],
    };
}


export function SchemasCreateJobDoneLabelPayloadToJSON(value?: SchemasCreateJobDoneLabelPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobDoneUuid': value.jobDoneUuid,
        'labelUuid': value.labelUuid,
    };
}

