/*
Masters way chat API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwChatBffInternalSchemasUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwChatBffInternalSchemasUserResponse{}

// MwChatBffInternalSchemasUserResponse struct for MwChatBffInternalSchemasUserResponse
type MwChatBffInternalSchemasUserResponse struct {
	ImageUrl string `json:"imageUrl"`
	Name string `json:"name"`
	Role string `json:"role"`
	UserId string `json:"userId"`
}

type _MwChatBffInternalSchemasUserResponse MwChatBffInternalSchemasUserResponse

// NewMwChatBffInternalSchemasUserResponse instantiates a new MwChatBffInternalSchemasUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwChatBffInternalSchemasUserResponse(imageUrl string, name string, role string, userId string) *MwChatBffInternalSchemasUserResponse {
	this := MwChatBffInternalSchemasUserResponse{}
	this.ImageUrl = imageUrl
	this.Name = name
	this.Role = role
	this.UserId = userId
	return &this
}

// NewMwChatBffInternalSchemasUserResponseWithDefaults instantiates a new MwChatBffInternalSchemasUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwChatBffInternalSchemasUserResponseWithDefaults() *MwChatBffInternalSchemasUserResponse {
	this := MwChatBffInternalSchemasUserResponse{}
	return &this
}

// GetImageUrl returns the ImageUrl field value
func (o *MwChatBffInternalSchemasUserResponse) GetImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value
// and a boolean to check if the value has been set.
func (o *MwChatBffInternalSchemasUserResponse) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageUrl, true
}

// SetImageUrl sets field value
func (o *MwChatBffInternalSchemasUserResponse) SetImageUrl(v string) {
	o.ImageUrl = v
}

// GetName returns the Name field value
func (o *MwChatBffInternalSchemasUserResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MwChatBffInternalSchemasUserResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MwChatBffInternalSchemasUserResponse) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *MwChatBffInternalSchemasUserResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *MwChatBffInternalSchemasUserResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *MwChatBffInternalSchemasUserResponse) SetRole(v string) {
	o.Role = v
}

// GetUserId returns the UserId field value
func (o *MwChatBffInternalSchemasUserResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *MwChatBffInternalSchemasUserResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *MwChatBffInternalSchemasUserResponse) SetUserId(v string) {
	o.UserId = v
}

func (o MwChatBffInternalSchemasUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwChatBffInternalSchemasUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageUrl"] = o.ImageUrl
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

func (o *MwChatBffInternalSchemasUserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"imageUrl",
		"name",
		"role",
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwChatBffInternalSchemasUserResponse := _MwChatBffInternalSchemasUserResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwChatBffInternalSchemasUserResponse)

	if err != nil {
		return err
	}

	*o = MwChatBffInternalSchemasUserResponse(varMwChatBffInternalSchemasUserResponse)

	return err
}

type NullableMwChatBffInternalSchemasUserResponse struct {
	value *MwChatBffInternalSchemasUserResponse
	isSet bool
}

func (v NullableMwChatBffInternalSchemasUserResponse) Get() *MwChatBffInternalSchemasUserResponse {
	return v.value
}

func (v *NullableMwChatBffInternalSchemasUserResponse) Set(val *MwChatBffInternalSchemasUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMwChatBffInternalSchemasUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMwChatBffInternalSchemasUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwChatBffInternalSchemasUserResponse(val *MwChatBffInternalSchemasUserResponse) *NullableMwChatBffInternalSchemasUserResponse {
	return &NullableMwChatBffInternalSchemasUserResponse{value: val, isSet: true}
}

func (v NullableMwChatBffInternalSchemasUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwChatBffInternalSchemasUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


