/*
Masters way training API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwTrainingInternalSchemasGetRoomsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwTrainingInternalSchemasGetRoomsResponse{}

// MwTrainingInternalSchemasGetRoomsResponse struct for MwTrainingInternalSchemasGetRoomsResponse
type MwTrainingInternalSchemasGetRoomsResponse struct {
	Rooms []MwTrainingInternalSchemasRoomPreviewResponse
	Size int32
}

type _MwTrainingInternalSchemasGetRoomsResponse MwTrainingInternalSchemasGetRoomsResponse

// NewMwTrainingInternalSchemasGetRoomsResponse instantiates a new MwTrainingInternalSchemasGetRoomsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwTrainingInternalSchemasGetRoomsResponse(rooms []MwTrainingInternalSchemasRoomPreviewResponse, size int32) *MwTrainingInternalSchemasGetRoomsResponse {
	this := MwTrainingInternalSchemasGetRoomsResponse{}
	this.Rooms = rooms
	this.Size = size
	return &this
}

// NewMwTrainingInternalSchemasGetRoomsResponseWithDefaults instantiates a new MwTrainingInternalSchemasGetRoomsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwTrainingInternalSchemasGetRoomsResponseWithDefaults() *MwTrainingInternalSchemasGetRoomsResponse {
	this := MwTrainingInternalSchemasGetRoomsResponse{}
	return &this
}

// GetRooms returns the Rooms field value
func (o *MwTrainingInternalSchemasGetRoomsResponse) GetRooms() []MwTrainingInternalSchemasRoomPreviewResponse {
	if o == nil {
		var ret []MwTrainingInternalSchemasRoomPreviewResponse
		return ret
	}

	return o.Rooms
}

// GetRoomsOk returns a tuple with the Rooms field value
// and a boolean to check if the value has been set.
func (o *MwTrainingInternalSchemasGetRoomsResponse) GetRoomsOk() ([]MwTrainingInternalSchemasRoomPreviewResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rooms, true
}

// SetRooms sets field value
func (o *MwTrainingInternalSchemasGetRoomsResponse) SetRooms(v []MwTrainingInternalSchemasRoomPreviewResponse) {
	o.Rooms = v
}

// GetSize returns the Size field value
func (o *MwTrainingInternalSchemasGetRoomsResponse) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *MwTrainingInternalSchemasGetRoomsResponse) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *MwTrainingInternalSchemasGetRoomsResponse) SetSize(v int32) {
	o.Size = v
}

func (o MwTrainingInternalSchemasGetRoomsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwTrainingInternalSchemasGetRoomsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rooms"] = o.Rooms
	toSerialize["size"] = o.Size
	return toSerialize, nil
}

func (o *MwTrainingInternalSchemasGetRoomsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rooms",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwTrainingInternalSchemasGetRoomsResponse := _MwTrainingInternalSchemasGetRoomsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwTrainingInternalSchemasGetRoomsResponse)

	if err != nil {
		return err
	}

	*o = MwTrainingInternalSchemasGetRoomsResponse(varMwTrainingInternalSchemasGetRoomsResponse)

	return err
}

type NullableMwTrainingInternalSchemasGetRoomsResponse struct {
	value *MwTrainingInternalSchemasGetRoomsResponse
	isSet bool
}

func (v NullableMwTrainingInternalSchemasGetRoomsResponse) Get() *MwTrainingInternalSchemasGetRoomsResponse {
	return v.value
}

func (v *NullableMwTrainingInternalSchemasGetRoomsResponse) Set(val *MwTrainingInternalSchemasGetRoomsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMwTrainingInternalSchemasGetRoomsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMwTrainingInternalSchemasGetRoomsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwTrainingInternalSchemasGetRoomsResponse(val *MwTrainingInternalSchemasGetRoomsResponse) *NullableMwTrainingInternalSchemasGetRoomsResponse {
	return &NullableMwTrainingInternalSchemasGetRoomsResponse{value: val, isSet: true}
}

func (v NullableMwTrainingInternalSchemasGetRoomsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwTrainingInternalSchemasGetRoomsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


