/*
Masters way chat API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MwChatInternalSchemasCreateRoomPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MwChatInternalSchemasCreateRoomPayload{}

// MwChatInternalSchemasCreateRoomPayload struct for MwChatInternalSchemasCreateRoomPayload
type MwChatInternalSchemasCreateRoomPayload struct {
	Name NullableString
	RoomType string
	UserId NullableString
}

type _MwChatInternalSchemasCreateRoomPayload MwChatInternalSchemasCreateRoomPayload

// NewMwChatInternalSchemasCreateRoomPayload instantiates a new MwChatInternalSchemasCreateRoomPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMwChatInternalSchemasCreateRoomPayload(roomType string) *MwChatInternalSchemasCreateRoomPayload {
	this := MwChatInternalSchemasCreateRoomPayload{}
	this.RoomType = roomType
	return &this
}

// NewMwChatInternalSchemasCreateRoomPayloadWithDefaults instantiates a new MwChatInternalSchemasCreateRoomPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMwChatInternalSchemasCreateRoomPayloadWithDefaults() *MwChatInternalSchemasCreateRoomPayload {
	this := MwChatInternalSchemasCreateRoomPayload{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MwChatInternalSchemasCreateRoomPayload) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MwChatInternalSchemasCreateRoomPayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *MwChatInternalSchemasCreateRoomPayload) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *MwChatInternalSchemasCreateRoomPayload) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *MwChatInternalSchemasCreateRoomPayload) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *MwChatInternalSchemasCreateRoomPayload) UnsetName() {
	o.Name.Unset()
}

// GetRoomType returns the RoomType field value
func (o *MwChatInternalSchemasCreateRoomPayload) GetRoomType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoomType
}

// GetRoomTypeOk returns a tuple with the RoomType field value
// and a boolean to check if the value has been set.
func (o *MwChatInternalSchemasCreateRoomPayload) GetRoomTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoomType, true
}

// SetRoomType sets field value
func (o *MwChatInternalSchemasCreateRoomPayload) SetRoomType(v string) {
	o.RoomType = v
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MwChatInternalSchemasCreateRoomPayload) GetUserId() string {
	if o == nil || IsNil(o.UserId.Get()) {
		var ret string
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MwChatInternalSchemasCreateRoomPayload) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *MwChatInternalSchemasCreateRoomPayload) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableString and assigns it to the UserId field.
func (o *MwChatInternalSchemasCreateRoomPayload) SetUserId(v string) {
	o.UserId.Set(&v)
}
// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *MwChatInternalSchemasCreateRoomPayload) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *MwChatInternalSchemasCreateRoomPayload) UnsetUserId() {
	o.UserId.Unset()
}

func (o MwChatInternalSchemasCreateRoomPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MwChatInternalSchemasCreateRoomPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["roomType"] = o.RoomType
	if o.UserId.IsSet() {
		toSerialize["userId"] = o.UserId.Get()
	}
	return toSerialize, nil
}

func (o *MwChatInternalSchemasCreateRoomPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roomType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMwChatInternalSchemasCreateRoomPayload := _MwChatInternalSchemasCreateRoomPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMwChatInternalSchemasCreateRoomPayload)

	if err != nil {
		return err
	}

	*o = MwChatInternalSchemasCreateRoomPayload(varMwChatInternalSchemasCreateRoomPayload)

	return err
}

type NullableMwChatInternalSchemasCreateRoomPayload struct {
	value *MwChatInternalSchemasCreateRoomPayload
	isSet bool
}

func (v NullableMwChatInternalSchemasCreateRoomPayload) Get() *MwChatInternalSchemasCreateRoomPayload {
	return v.value
}

func (v *NullableMwChatInternalSchemasCreateRoomPayload) Set(val *MwChatInternalSchemasCreateRoomPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableMwChatInternalSchemasCreateRoomPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableMwChatInternalSchemasCreateRoomPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMwChatInternalSchemasCreateRoomPayload(val *MwChatInternalSchemasCreateRoomPayload) *NullableMwChatInternalSchemasCreateRoomPayload {
	return &NullableMwChatInternalSchemasCreateRoomPayload{value: val, isSet: true}
}

func (v NullableMwChatInternalSchemasCreateRoomPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMwChatInternalSchemasCreateRoomPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


