{
 "title": "all_databeses",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "General_db_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT 1 AS is_alive" }
   ]
  },
  {
   "title": "general_db_size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_db');\n"
    }
   ]
  },
  {
   "title": "Version and user-tables-count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "\nSELECT version();\n" }
   ]
  },
  {
   "title": "Chat_db_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT 1 AS is_alive" }
   ]
  },
  {
   "title": "chat_db_size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_chat_db');\n"
    }
   ]
  },
  {
   "title": "Version and user-tables-count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "\nSELECT version();\n" }
   ]
  },
  {
   "title": "Training_db_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT 1 AS is_alive" }
   ]
  },
  {
   "title": "training_db_size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_training_db');\n"
    }
   ]
  },
  {
   "title": "Version and user-tables-count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "\nSELECT version();\n" }
   ]
  },
  {
   "title": "Storage_db_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT 1 AS is_alive" }
   ]
  },
  {
   "title": "storage_db_size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_storage_db');\n"
    }
   ]
  },
  {
   "title": "Version and user-tables-count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "\nSELECT version();\n" }
   ]
  },
  {
   "title": "Survey_db_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT 1 AS is_alive" }
   ]
  },
  {
   "title": "survey_db_size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_survey_db');\n"
    }
   ]
  },
  {
   "title": "Version and user-tables-count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "\nSELECT version();\n" }
   ]
  },
  {
   "title": "Notification_db_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT 1 AS is_alive" }
   ]
  },
  {
   "title": "survey_db_size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_notification_db');\n"
    }
   ]
  },
  {
   "title": "Version and user-tables-count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "\nSELECT version();\n" }
   ]
  },
  {
   "title": "Mail_db_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT 1 AS is_alive" }
   ]
  },
  {
   "title": "mail_db_size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_mail_db');\n"
    }
   ]
  },
  {
   "title": "Version and user-tables-count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "\nSELECT version();\n" }
   ]
  }
 ]
}