{
 "title": "chat_db",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "chat_db_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT 1 AS is_alive, now() AS time"
    }
   ]
  },
  {
   "title": "Database Started",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pg_postmaster_start_time();"
    }
   ]
  },
  {
   "title": "Buffer Cache Hit Ratio",
   "type": "table",
   "description": "99-100%\tExcellent\t\n95-98%\tVery Good\t\n85-95%\tGood\tMonitor for changes\n70-85%\tAdequate  (Consider memory increase if workload grows)\n50-70% Concerning Investigate memory needs\n<50%\tPoor\tImmediate attention needed",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND(blks_hit * 100.0 / NULLIF(blks_hit + blks_read, 0), 2) as cache_hit_ratio\nFROM pg_stat_database\nWHERE datname = current_database();"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "table",
   "description": "PostgreSQL naturally maintains several connections such as Autovacuum workers, Background writer, Statistics collector, WAL writer, Replication connections (if configured)",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(*) as active_connections,\n    (SELECT setting::int FROM pg_settings WHERE name = 'max_connections') as max_connections,\n    ROUND(COUNT(*) * 100.0 / (SELECT setting::int FROM pg_settings WHERE name = 'max_connections'), 1) as percentage_used\nFROM pg_stat_activity;"
    }
   ]
  },
  {
   "title": "chat_db_size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_chat_db');\n"
    }
   ]
  },
  {
   "title": "Transaction Rates",
   "type": "table",
   "description": "Transaction metrics measure the database's ability to process data modifications reliably and efficiently. ",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n    datname,\n    xact_commit as commits,\n    xact_rollback as rollbacks,\n    xact_commit + xact_rollback as total,\n    ROUND(xact_rollback * 100.0 / NULLIF(xact_commit + xact_rollback, 0), 2) as rollback_percentage\nFROM pg_stat_database \nWHERE datname = current_database();"
    }
   ]
  },
  {
   "title": "Version and user-tables-count",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "rawSql": "\nSELECT version();\n" },
    {
     "rawSql": "SELECT \n    COUNT(*) AS user_tables_count \nFROM pg_tables \nWHERE schemaname NOT IN ('pg_catalog', 'information_schema');"
    },
    { "rawSql": "SELECT 1" }
   ]
  },
  {
   "title": "Database Configuration",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "-- Important configuration parameters\nSELECT name, setting, unit, context, short_desc\nFROM pg_settings\nWHERE name IN (\n    'max_connections', 'shared_buffers', 'work_mem', 'maintenance_work_mem',\n    'effective_cache_size', 'max_wal_size', 'checkpoint_timeout',\n    'random_page_cost', 'effective_io_concurrency', 'autovacuum',\n    'log_min_duration_statement'\n)\nORDER BY name;"
    }
   ]
  },
  {
   "title": "Index Usage Metrics",
   "type": "table",
   "description": "Index usage metrics measure how frequently PostgreSQL uses indexes versus sequential table scans when retrieving data.",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n    relname as table_name,\n    idx_scan as index_scans,\n    seq_scan as sequential_scans,\n    CASE WHEN seq_scan + idx_scan != 0 \n        THEN round(100.0 * idx_scan / (seq_scan + idx_scan), 2)\n        ELSE 0 END AS percent_index_use\nFROM pg_stat_user_tables \nORDER BY n_live_tup DESC;\n"
    }
   ]
  },
  {
   "title": "Long-Running Queries",
   "type": "stat",
   "description": "Longer than 5 seconds, If many, database needs attention",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n    pid,\n    usename,\n    application_name,\n    client_addr,\n    state,\n    extract(epoch from (now() - query_start)) as duration_seconds,\n    query\nFROM pg_stat_activity \nWHERE state = 'active'\n  AND (now() - query_start) > interval '1 seconds'\nORDER BY duration_seconds DESC;\n"
    }
   ]
  }
 ]
}