{
 "title": "System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(*) AS active_connections\nFROM pg_stat_activity\nWHERE datname = 'mastersway_db'\n  AND state = 'active';\n\n"
    },
    {
     "rawSql": "SELECT\n  xact_commit + xact_rollback AS total_transactions\nFROM pg_stat_database\nWHERE datname = 'mastersway_db';"
    }
   ]
  },
  {
   "title": "pg_stat_activity",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_activity;\n"
    }
   ]
  },
  {
   "title": "pg_stat_database",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_database;\n"
    }
   ]
  },
  {
   "title": "Mastersway_db_status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT 1 AS is_alive, now() AS time"
    }
   ]
  },
  {
   "title": "Masters_way_db_size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('mastersway_db');\n"
    }
   ]
  }
 ]
}